INSERT INTO category (categoryName, categoryImageUrl) VALUES 
('Breakfast', '/images/categories/breakfast-60x60.png'),
('Lunch', '/images/categories/lunch-60x60.png'),
('Dinner', '/images/categories/dinner-60x60.png'),
('Desserts', '/images/categories/desserts-60x60.png');

-- Insert common diet types
INSERT INTO diet (dietName, dietDescription) VALUES
('Vegetarian', 'No meat, fish, or poultry'),
('Vegan', 'No animal products'),
('Gluten-Free', 'No gluten-containing ingredients'),
('Keto', 'Low-carb, high-fat diet'),
('Paleo', 'Based on foods presumed eaten during the Paleolithic era'),
('Pescatarian', 'Vegetarian diet that includes fish'),
('Dairy-Free', 'No dairy products'),
('Low-Carb', 'Reduced carbohydrate intake'),
('None', 'No specific dietary restrictions');

-- Insert cuisine types
INSERT INTO cuisine (cuisineName, cuisineDescription) VALUES 
('Italian', 'Traditional Italian dishes including pasta, pizza, and Mediterranean flavors'),
('Chinese', 'Various regional Chinese cuisines featuring stir-fries, noodles, and rice dishes'),
('Mexican', 'Traditional Mexican dishes with tortillas, beans, and diverse spices'),
('Indian', 'Rich and diverse Indian cuisine with curries, tandoor dishes, and flatbreads'),
('Japanese', 'Japanese cuisine featuring sushi, noodles, and traditional dishes'),
('Thai', 'Thai dishes with sweet, sour, and spicy flavors'),
('Mediterranean', 'Healthy Mediterranean diet with olive oil, fresh vegetables, and seafood'),
('American', 'Classic American comfort food and regional specialties'),
('French', 'Elegant French cuisine with rich sauces and sophisticated techniques'),
('Korean', 'Korean dishes featuring kimchi, barbecue, and rice-based meals'),
('Vietnamese', 'Fresh Vietnamese cuisine with herbs and light preparations'),
('Middle Eastern', 'Middle Eastern fare with kebabs, hummus, and aromatic spices'),
('Greek', 'Traditional Greek dishes with olives, feta, and Mediterranean herbs'),
('Spanish', 'Spanish cuisine featuring paella, tapas, and seafood dishes');

-- Insert into recipe
INSERT INTO recipe (recipeName, description, userId, prep_time, cook_time, servings, categoryId, dietId, cookingLevel, cuisineId) VALUES
('Marry Me Shrimp Pasta', 'Cook pasta; sauté shrimp in garlic butter; add cream and parmesan; toss with pasta.', 1, 15, 20, 4, 4, 9, 'Intermediate', 1),
('Avocado Toast', 'Toast bread; smash avocado with lemon and salt; spread on toast; top with chili flakes.', 2, 5, 0, 1, 2, 1, 'Beginner', 8),
('Chicken Burrito Bowl', 'Grill chicken; cook rice; layer with beans, salsa, cheese, and lettuce in a bowl.', 3, 15, 20, 2, 3, 9, 'Intermediate', 3),
('Vegan Pancakes', 'Mix flour, baking powder, almond milk; cook pancakes until golden; serve with syrup.', 4, 10, 15, 2, 2, 2, 'Beginner', 8),
('Beef Stroganoff', 'Brown beef; cook onions and mushrooms; stir in sour cream; serve over noodles.', 5, 20, 30, 4, 4, 9, 'Intermediate', 9),
('Tofu Stir Fry', 'Sauté tofu cubes; add mixed veggies; stir in soy sauce and garlic; cook until tender.', 6, 15, 15, 3, 3, 2, 'Beginner', 2),
('Keto Egg Muffins', 'Whisk eggs with veggies and cheese; pour into muffin tins; bake until set.', 7, 10, 20, 4, 2, 4, 'Beginner', 8),
('Gluten-Free Brownies', 'Mix gluten-free flour, cocoa, sugar, and eggs; bake until fudgy; cool before slicing.', 8, 15, 25, 6, 5, 3, 'Intermediate', 8),
('Grilled Salmon with Veggies', 'Season salmon; grill with veggies until cooked; drizzle with lemon and olive oil.', 2, 10, 20, 2, 4, 7, 'Intermediate', 7),
('Kimchi Fried Rice', 'Sauté kimchi and rice; add soy sauce and sesame oil; top with fried egg.', 1, 10, 15, 2, 3, 9, 'Beginner', 10),
('Caprese Salad', 'Slice tomatoes and mozzarella; layer with basil; drizzle with balsamic and olive oil.', 1, 10, 0, 2, 3, 1, 'Beginner', 1),
('Vegan Buddha Bowl', 'Cook quinoa; roast chickpeas and veggies; serve with tahini dressing.', 2, 15, 25, 2, 3, 2, 'Beginner', 7),
('French Onion Soup', 'Caramelize onions; add broth; simmer; top with toasted bread and melted cheese.', 3, 20, 45, 4, 4, 9, 'Intermediate', 9),
('Pad Thai', 'Sauté tofu and shrimp; add rice noodles and sauce; top with peanuts and lime.', 4, 15, 20, 3, 4, 9, 'Intermediate', 6),
('Miso Soup', 'Heat dashi broth; stir in miso paste; add tofu and seaweed; serve hot.', 5, 5, 10, 2, 3, 1, 'Beginner', 5),
('Avocado Sushi Rolls', 'Lay rice and avocado on nori; roll tightly; slice and serve with soy sauce.', 6, 20, 0, 2, 3, 2, 'Intermediate', 5),
('Shakshuka', 'Sauté onions and peppers; add tomatoes and spices; crack in eggs; cook until set.', 7, 10, 20, 3, 2, 1, 'Intermediate', 12),
('Greek Salad', 'Chop cucumbers, tomatoes, onions; toss with olives, feta, and vinaigrette.', 8, 10, 0, 2, 3, 1, 'Beginner', 13),
('BBQ Pulled Pork', 'Slow cook pork with BBQ sauce; shred and serve on buns.', 9, 15, 480, 6, 4, 9, 'Intermediate', 8),
('Falafel Wraps', 'Blend chickpeas with herbs; shape balls; fry and stuff in pita with veggies.', 10, 20, 15, 4, 3, 1, 'Intermediate', 12),
('Vegetable Lasagna', 'Layer noodles with ricotta, spinach, and marinara; bake until bubbly.', 1, 30, 45, 6, 4, 1, 'Intermediate', 1),
('Egg Fried Rice', 'Scramble eggs; add rice and veggies; stir-fry with soy sauce.', 2, 10, 15, 3, 3, 9, 'Beginner', 2),
('Pancit Bihon', 'Sauté pork and veggies; add rice noodles and broth; cook until tender.', 3, 15, 20, 4, 3, 9, 'Intermediate', 2),
('Spinach & Feta Omelette', 'Whisk eggs; cook with spinach and feta; fold and serve.', 4, 5, 10, 1, 2, 1, 'Beginner', 8),
('Korean Bibimbap', 'Arrange rice with sautéed veggies, beef, and fried egg; serve with gochujang.', 5, 25, 20, 3, 3, 9, 'Intermediate', 10),
('Chicken Tikka Masala', 'Marinate chicken; grill and simmer in creamy tomato sauce.', 6, 30, 40, 4, 4, 9, 'Intermediate', 4),
('Gazpacho', 'Blend tomatoes, cucumbers, peppers; chill and serve cold.', 7, 15, 0, 2, 3, 1, 'Beginner', 14),
('Cauliflower Rice', 'Pulse cauliflower in processor; sauté lightly with olive oil.', 8, 10, 5, 2, 3, 4, 'Beginner', 8),
('Churros', 'Mix dough; pipe into hot oil; fry until golden; roll in cinnamon sugar.', 9, 15, 20, 4, 5, 9, 'Intermediate', 14),
('Turkey Meatballs', 'Mix turkey with herbs; roll into balls; bake until golden.', 10, 15, 25, 4, 4, 9, 'Beginner', 8),
('Sweet and Sour Chicken', 'Coat chicken in batter; fry; toss with pineapple and sweet-sour sauce.', 1, 20, 25, 3, 4, 9, 'Intermediate', 2),
('Ratatouille', 'Sauté eggplant, zucchini, and peppers; simmer in tomato sauce.', 2, 15, 35, 4, 4, 1, 'Intermediate', 9),
('Pesto Pasta', 'Boil pasta; blend basil, pine nuts, and parmesan; toss together.', 3, 10, 15, 2, 3, 1, 'Beginner', 1),
('Shrimp Tacos', 'Sauté shrimp with spices; serve in tortillas with slaw and lime.', 4, 15, 10, 3, 3, 6, 'Intermediate', 3),
('Eggplant Parmesan', 'Bread and fry eggplant; layer with sauce and cheese; bake.', 5, 25, 35, 4, 4, 1, 'Intermediate', 1),
('Mapo Tofu', 'Cook ground pork; add tofu and spicy sauce; simmer and serve.', 6, 10, 20, 3, 4, 9, 'Intermediate', 2),
('Thai Green Curry', 'Sauté curry paste; add coconut milk, chicken, and veggies; simmer.', 7, 15, 25, 4, 4, 9, 'Intermediate', 6),
('Tuna Nicoise Salad', 'Arrange greens with tuna, eggs, potatoes, and olives; drizzle vinaigrette.', 8, 20, 10, 2, 3, 6, 'Intermediate', 9),
('Stuffed Bell Peppers', 'Fill peppers with rice and beef; bake with tomato sauce.', 9, 20, 40, 4, 4, 9, 'Intermediate', 8),
('Kale Chips', 'Toss kale with oil and salt; bake until crisp.', 10, 5, 15, 2, 5, 1, 'Beginner', 8),
('Lentil Soup', 'Simmer lentils with carrots, celery, and spices until tender.', 1, 15, 40, 4, 3, 1, 'Beginner', 12),
('Beef Bulgogi', 'Marinate beef; grill or pan-fry; serve with rice.', 2, 30, 15, 3, 4, 9, 'Intermediate', 10),
('Fish and Chips', 'Batter and fry fish; serve with fries and tartar sauce.', 3, 20, 25, 3, 4, 9, 'Intermediate', 8),
('Chocolate Mousse', 'Whip cream; fold into melted chocolate; chill until set.', 4, 15, 0, 4, 5, 9, 'Intermediate', 9),
('Vietnamese Spring Rolls', 'Wrap shrimp, noodles, and herbs in rice paper; serve with dipping sauce.', 5, 20, 0, 3, 3, 6, 'Intermediate', 11),
('Butternut Squash Soup', 'Roast squash; blend with broth and cream; season.', 6, 15, 30, 4, 3, 1, 'Beginner', 8),
('Paneer Butter Masala', 'Cook paneer in creamy tomato sauce with spices.', 7, 15, 25, 3, 4, 1, 'Intermediate', 4),
('Croque Monsieur', 'Assemble ham and cheese sandwich; grill with béchamel sauce.', 8, 10, 15, 2, 3, 9, 'Intermediate', 9),
('Enchiladas', 'Roll chicken in tortillas; cover with sauce and cheese; bake.', 9, 20, 25, 4, 4, 9, 'Intermediate', 3),
('Tom Yum Soup', 'Simmer shrimp with lemongrass, lime, and chili in broth.', 10, 10, 20, 3, 3, 6, 'Intermediate', 6),
('Bruschetta', 'Toast bread; top with tomatoes, garlic, and basil.', 1, 10, 5, 2, 3, 1, 'Beginner', 1),
('Baked Ziti', 'Cook pasta; layer with ricotta, sauce, and mozzarella; bake.', 2, 15, 30, 4, 4, 1, 'Intermediate', 1),
('Cabbage Rolls', 'Fill cabbage leaves with rice and meat; simmer in tomato sauce.', 3, 30, 60, 4, 4, 9, 'Intermediate', 8),
('Japanese Curry', 'Brown meat and veggies; add curry roux and simmer.', 4, 20, 30, 4, 4, 9, 'Intermediate', 5),
('Roasted Veggie Medley', 'Toss mixed veggies with oil and herbs; roast until tender.', 5, 10, 25, 3, 3, 1, 'Beginner', 8),
('Pumpkin Pie', 'Mix pumpkin puree with spices; bake in pie crust.', 6, 20, 50, 6, 5, 9, 'Intermediate', 8),
('Lamb Kebabs', 'Skewer lamb chunks; grill until charred.', 7, 15, 15, 3, 4, 9, 'Intermediate', 12),
('Kimchi Stew', 'Simmer kimchi with pork, tofu, and broth.', 8, 10, 30, 3, 3, 9, 'Intermediate', 10),
('Spanish Omelette', 'Cook potatoes and onions; add eggs; fry until golden.', 9, 15, 20, 2, 2, 9, 'Intermediate', 14),
('Peach Cobbler', 'Layer peaches with batter; bake until golden.', 10, 15, 40, 4, 5, 9, 'Intermediate', 8),
('Chicken Caesar Salad', 'Toss lettuce with grilled chicken, croutons, and Caesar dressing.', 1, 10, 5, 2, 3, 9, 'Beginner', 8),
('Vegan Pancakes', 'Mix flour, almond milk, and baking powder; cook pancakes on griddle.', 2, 10, 15, 2, 2, 2, 'Beginner', 2),
('Margherita Pizza', 'Top dough with tomatoes, mozzarella, and basil; bake in oven.', 3, 20, 15, 2, 3, 1, 'Intermediate', 1),
('Crispy Chickpea Salad', 'Roast chickpeas; mix with greens, avocado, and tahini dressing.', 4, 10, 30, 2, 3, 2, 'Beginner', 7),
('Beef Stroganoff', 'Cook beef in sour cream sauce; serve over egg noodles.', 5, 15, 25, 4, 4, 9, 'Intermediate', 9),
('Vegetable Samosas', 'Stuff pastry with spiced potatoes and peas; deep fry until crispy.', 6, 20, 30, 6, 5, 1, 'Intermediate', 4),
('Sushi Rolls', 'Roll rice, nori, and fish or veggies; slice into pieces.', 7, 20, 0, 2, 2, 1, 'Intermediate', 5),
('Chicken Tenders', 'Bread chicken strips; deep fry until golden and crispy.', 8, 15, 20, 3, 4, 9, 'Intermediate', 8),
('Zucchini Fritters', 'Grate zucchini; mix with eggs and flour; fry in oil.', 9, 15, 10, 2, 3, 1, 'Beginner', 8),
('Pasta Primavera', 'Sauté mixed veggies; toss with cooked pasta and olive oil.', 10, 10, 20, 3, 4, 9, 'Beginner', 1),
('Stuffed Mushrooms', 'Fill mushroom caps with cream cheese and herbs; bake until soft.', 1, 15, 20, 4, 5, 1, 'Intermediate', 9),
('Tom Kha Gai', 'Simmer chicken with coconut milk, lemongrass, and chili.', 2, 15, 30, 3, 4, 6, 'Intermediate', 6),
('Lamb Curry', 'Simmer lamb with curry spices, tomatoes, and coconut milk.', 3, 20, 40, 4, 4, 9, 'Intermediate', 4),
('Falafel Salad', 'Serve homemade falafel on greens with tahini sauce.', 4, 20, 25, 3, 3, 2, 'Intermediate', 12),
('Crispy Tofu Stir-Fry', 'Stir-fry tofu with veggies; serve with rice.', 5, 15, 20, 3, 3, 2, 'Intermediate', 2),
('Mushroom Risotto', 'Cook mushrooms and rice with broth until creamy.', 6, 15, 30, 4, 4, 9, 'Intermediate', 9),
('Chicken Shawarma', 'Marinate chicken in spices; grill and serve with pita and veggies.', 7, 25, 25, 4, 4, 9, 'Intermediate', 12),
('Beef Tacos', 'Cook ground beef with taco seasoning; fill tortillas with beef, lettuce, and cheese.', 8, 10, 15, 3, 4, 9, 'Beginner', 3),
('Pasta Carbonara', 'Cook pasta; toss with egg, cheese, pancetta, and pepper.', 9, 10, 15, 3, 4, 9, 'Intermediate', 1),
('Vegetable Frittata', 'Whisk eggs with veggies; bake until golden.', 10, 10, 25, 4, 3, 1, 'Beginner', 8),
('Tomato Basil Soup', 'Simmer tomatoes and basil; blend until smooth.', 1, 15, 30, 4, 3, 1, 'Beginner', 9),
('Grilled Cheese Sandwich', 'Grill bread with butter and melted cheese inside.', 2, 5, 10, 1, 2, 1, 'Beginner', 8),
('Pork Schnitzel', 'Bread and fry pork cutlets; serve with lemon wedges.', 3, 20, 25, 4, 4, 9, 'Intermediate', 9),
('Lentil Tacos', 'Cook lentils with taco seasoning; serve in tortillas with toppings.', 4, 15, 20, 4, 3, 2, 'Beginner', 3),
('Beef and Broccoli', 'Stir-fry beef with broccoli and soy sauce.', 5, 10, 15, 3, 3, 9, 'Intermediate', 2),
('Carrot Cake', 'Mix carrots with flour, sugar, and spices; bake and frost with cream cheese icing.', 6, 15, 40, 6, 5, 9, 'Intermediate', 8),
('Chicken Parmesan', 'Bread and fry chicken; top with marinara and cheese; bake.', 7, 20, 30, 4, 4, 9, 'Intermediate', 1),
('Ramen Noodles', 'Cook ramen noodles in broth with soy sauce and veggies.', 8, 10, 5, 2, 3, 9, 'Beginner', 5),
('Baked Salmon', 'Season salmon with herbs and bake until flaky.', 9, 10, 20, 3, 4, 9, 'Intermediate', 5),
('Chicken Alfredo', 'Cook pasta; mix with chicken and creamy Alfredo sauce.', 10, 10, 20, 3, 4, 9, 'Intermediate', 1),
('Roast Chicken', 'Season whole chicken and roast until golden and crispy.', 1, 20, 90, 6, 4, 9, 'Intermediate', 8),
('Spinach Artichoke Dip', 'Mix spinach, artichokes, and cheese; bake until bubbly.', 2, 15, 30, 4, 5, 1, 'Intermediate', 9),
('Lamb Shawarma', 'Marinate lamb; grill and serve with pita and tahini sauce.', 3, 25, 30, 4, 4, 9, 'Intermediate', 12),
('Sweet Potato Fries', 'Cut sweet potatoes; toss with olive oil and bake until crispy.', 4, 10, 25, 3, 3, 1, 'Beginner', 8),
('Buffalo Wings', 'Toss wings in buffalo sauce; bake or fry until crispy.', 5, 10, 30, 4, 4, 9, 'Intermediate', 8),
('Chili', 'Simmer ground beef, beans, and spices in tomato sauce.', 6, 15, 60, 6, 3, 1, 'Intermediate', 8),
('Pumpkin Soup', 'Simmer pumpkin with spices and cream; blend until smooth.', 7, 10, 30, 4, 3, 1, 'Beginner', 8),
('Chicken Fajitas', 'Sauté chicken, peppers, and onions; serve in tortillas with toppings.', 8, 15, 15, 4, 4, 9, 'Intermediate', 3),
('Vegetarian Chili', 'Cook beans, veggies, and spices in tomato sauce.', 9, 15, 45, 4, 3, 2, 'Beginner', 8),
('Chicken and Rice', 'Cook chicken with rice, broth, and seasonings until tender.', 10, 15, 30, 4, 4, 9, 'Beginner', 8),
('Eggplant Parmesan Sandwich', 'Bread and fry eggplant; top with marinara and cheese; serve on a bun.', 1, 20, 30, 2, 4, 1, 'Intermediate', 9),
('Baked Potatoes', 'Pierce potatoes and bake until tender; top with butter and sour cream.', 2, 5, 45, 4, 3, 1, 'Beginner', 8),
('Fettuccine Alfredo', 'Cook pasta; toss with a creamy Parmesan sauce.', 3, 10, 15, 3, 4, 9, 'Intermediate', 1),
('Chicken Kiev', 'Stuff chicken with garlic butter; bread and fry until crispy.', 4, 20, 30, 4, 4, 9, 'Intermediate', 9),
('Beef Bulgogi', 'Marinate beef in soy sauce and sesame oil; grill with vegetables.', 1, 15, 20, 4, 4, 9, 'Intermediate', 10),
('Chickpea Curry', 'Simmer chickpeas with coconut milk, tomatoes, and spices.', 2, 15, 25, 4, 3, 2, 'Intermediate', 4),
('Stuffed Peppers', 'Fill bell peppers with ground turkey, rice, and spices; bake.', 3, 15, 30, 4, 4, 9, 'Intermediate', 8),
('Pulled Jackfruit Tacos', 'Shred jackfruit and cook with taco seasoning; serve in tortillas.', 4, 10, 20, 4, 5, 2, 'Beginner', 3),
('Mango Sticky Rice', 'Cook sticky rice with coconut milk; serve with fresh mango slices.', 5, 15, 20, 2, 5, 2, 'Beginner', 6),
('Lemon Herb Salmon', 'Season salmon with lemon and herbs; bake or grill until done.', 6, 10, 15, 4, 4, 9, 'Intermediate', 5),
('Crispy Tofu', 'Toss tofu in cornstarch and fry until crispy; serve with dipping sauce.', 7, 10, 15, 3, 3, 2, 'Beginner', 2),
('Coconut Lentil Soup', 'Simmer lentils in coconut milk with curry spices and vegetables.', 9, 10, 30, 4, 3, 2, 'Beginner', 4),
('Vegetable Tempura', 'Dip vegetables in batter and deep fry until golden and crispy.', 10, 15, 20, 4, 3, 2, 'Intermediate', 5),
('Shrimp Scampi', 'Cook shrimp with garlic, lemon, and butter; serve with pasta.', 2, 10, 15, 3, 4, 9, 'Intermediate', 1),
('Spaghetti Carbonara', 'Toss pasta with eggs, cheese, pancetta, and pepper.', 3, 10, 15, 4, 4, 9, 'Intermediate', 1),
('Fajita Bowls', 'Grill seasoned chicken or steak with peppers; serve over rice.', 4, 15, 20, 4, 4, 9, 'Beginner', 3),
('Pork Schnitzel', 'Bread and fry pork cutlets until crispy; serve with lemon wedges.', 5, 20, 30, 4, 4, 9, 'Intermediate', 9),
('Carrot Ginger Soup', 'Simmer carrots and ginger in broth; blend until smooth.', 6, 15, 30, 4, 3, 1, 'Beginner', 8),
('Veggie Pizza', 'Top pizza dough with vegetables, tomato sauce, and cheese; bake.', 7, 10, 15, 2, 3, 2, 'Beginner', 1),
('Chili Con Carne', 'Simmer ground beef, beans, and spices in a tomato sauce.', 8, 15, 45, 4, 4, 9, 'Intermediate', 8),
('Eggplant Stir Fry', 'Stir-fry sliced eggplant with soy sauce and garlic.', 9, 10, 15, 4, 3, 2, 'Beginner', 2),
('Banana Bread', 'Mix mashed bananas with flour, sugar, and eggs; bake until golden.', 1, 10, 60, 4, 5, 9, 'Beginner', 8),
('Zucchini Noodles', 'Toss zucchini noodles with marinara sauce and parmesan cheese.', 2, 10, 15, 3, 3, 2, 'Beginner', 7),
('Falafel', 'Blend chickpeas with herbs; form into balls and fry until crispy.', 4, 15, 30, 4, 3, 2, 'Intermediate', 12),
('Grilled Cheese and Bacon', 'Grill cheese sandwich with crispy bacon inside.', 5, 10, 10, 3, 4, 9, 'Beginner', 9),
('Chicken Parmesan', 'Bread chicken, fry, and top with marinara and cheese; bake.', 6, 15, 30, 4, 4, 9, 'Intermediate', 1),
('Vegan Pancakes', 'Make pancakes with plant-based milk and egg replacer; serve with syrup.', 7, 10, 15, 3, 3, 2, 'Beginner', 7),
('Pasta Primavera', 'Cook pasta with mixed vegetables and olive oil; serve with parmesan.', 8, 10, 20, 4, 3, 9, 'Beginner', 1),
('Meatball Subs', 'Make meatballs and bake with marinara sauce; serve on a sub roll with cheese.', 9, 15, 30, 4, 4, 9, 'Intermediate', 8),
('Baked Avocado Eggs', 'Bake an egg inside half an avocado; season with spices.', 10, 10, 15, 2, 3, 1, 'Beginner', 7),
('Mushroom Risotto', 'Simmer rice with mushrooms, butter, and parmesan until creamy.', 1, 15, 30, 4, 4, 9, 'Intermediate', 9),
('Peking Duck', 'Roast duck until crispy; serve with pancakes and hoisin sauce.', 2, 20, 60, 6, 4, 9, 'Advanced', 2),
('Crispy Fish Tacos', 'Fry battered fish fillets and serve in tortillas with cabbage and salsa.', 3, 15, 20, 3, 4, 9, 'Intermediate', 5),
('Pumpkin Soup', 'Simmer pumpkin with onions, garlic, and stock; blend until smooth.', 4, 15, 30, 4, 3, 1, 'Beginner', 8),
('Shakshuka with Feta', 'Poach eggs in a tomato sauce with onions and spices; serve with feta and bread.', 5, 10, 25, 4, 3, 1, 'Beginner', 12),
('BBQ Chicken Wings', 'Grill chicken wings with BBQ sauce until crispy.', 6, 10, 25, 4, 4, 9, 'Intermediate', 8),
('Vegan Burrito Bowl', 'Layer rice, beans, veggies, and salsa in a bowl; top with avocado.', 7, 10, 15, 3, 3, 2, 'Beginner', 3),
('Pulled Beef Nachos', 'Layer chips with pulled beef, cheese, and jalapenos; bake until melted.', 8, 15, 20, 4, 4, 9, 'Intermediate', 8),
('Oatmeal with Berries', 'Cook oats with milk or water; top with fresh berries and honey.', 9, 5, 10, 2, 3, 2, 'Beginner', 7),
('Moussaka', 'Layer eggplant, ground beef, and béchamel sauce; bake until golden.', 10, 20, 45, 4, 4, 9, 'Intermediate', 13),
('Chicken Shawarma', 'Season chicken with spices; roast and serve with pita and vegetables.', 1, 15, 30, 4, 4, 9, 'Intermediate', 12),
('Vegetable Paella', 'Simmer rice with saffron, peas, and bell peppers until tender.', 2, 15, 35, 4, 3, 2, 'Intermediate', 14),
('Pasta Alfredo', 'Toss pasta in a creamy sauce made of butter, cream, and parmesan.', 3, 10, 20, 4, 4, 9, 'Beginner', 1),
('Baked Apples', 'Core apples, stuff with cinnamon and sugar; bake until tender.', 4, 10, 30, 4, 5, 9, 'Beginner', 8),
('Korean BBQ', 'Grill marinated meats; serve with rice, kimchi, and dipping sauces.', 5, 20, 30, 4, 4, 9, 'Intermediate', 10),
('Panzanella Salad', 'Toss stale bread, tomatoes, cucumbers, and basil with vinaigrette.', 6, 10, 10, 3, 3, 2, 'Beginner', 13),
('Salmon Poke Bowl', 'Layer salmon, rice, avocado, and soy sauce in a bowl.', 7, 10, 15, 3, 4, 9, 'Beginner', 5),
('Beef Empanadas', 'Fill pastry with seasoned ground beef and vegetables; bake until golden.', 8, 15, 30, 4, 4, 9, 'Intermediate', 14),
('Roasted Vegetables', 'Roast mixed vegetables like carrots, potatoes, and zucchini with herbs.', 9, 15, 40, 4, 3, 1, 'Beginner', 7),
('Lamb Koftas', 'Grill ground lamb mixed with spices; serve with yogurt sauce.', 10, 15, 20, 4, 4, 9, 'Intermediate', 4),
('Spicy Black Bean Burgers', 'Mash black beans with spices and breadcrumbs; form patties; pan-fry until browned.', 3, 25, 20, 6, 3, 2, 'Intermediate', 3),
('Salmon Nigiri', 'Prepare sushi rice; slice fresh salmon; form rice balls and top with salmon.', 5, 20, 10, 2, 5, 6, 'Intermediate', 5),
('Pad See Ew', 'Stir-fry wide rice noodles with Chinese broccoli, egg, and soy sauce.', 6, 15, 15, 2, 3, 9, 'Intermediate', 6),
('Greek Salad', 'Combine tomatoes, cucumbers, olives, feta cheese, and a simple vinaigrette.', 7, 10, 0, 4, 3, 1, 'Beginner', 13),
('Mushroom Risotto', 'Sauté mushrooms and Arborio rice; gradually add broth until creamy.', 9, 20, 30, 4, 1, 1, 'Advanced', 1),
('Lemon Herb Roasted Chicken', 'Roast a whole chicken with lemon, herbs, and vegetables.', 10, 15, 60, 6, 4, 9, 'Intermediate', 8),
('Chocolate Lava Cakes', 'Prepare rich chocolate batter; bake until edges are set and center is molten.', 11, 20, 15, 4, 5, 9, 'Advanced', 9),
('Spring Rolls with Peanut Sauce', 'Assemble fresh rice paper rolls with shrimp, vegetables, and herbs; serve with peanut sauce.', 13, 30, 0, 4, 3, 9, 'Intermediate', 11),
('Lamb Kebabs with Tzatziki', 'Marinate lamb cubes; grill on skewers; serve with refreshing cucumber-yogurt sauce.', 14, 25, 20, 4, 4, 9, 'Intermediate', 12),
('Tofu Scramble', 'Crumble tofu and sauté with vegetables and turmeric for a breakfast scramble.', 17, 10, 15, 2, 2, 2, 'Beginner', 8),
('Gazpacho', 'Blend fresh tomatoes, cucumbers, peppers, and garlic for a chilled soup.', 18, 15, 0, 4, 3, 9, 'Beginner', 14),
('Chicken Fajitas', 'Slice chicken and peppers; sauté with onions and fajita seasoning; serve with tortillas.', 19, 20, 25, 4, 4, 9, 'Intermediate', 3),
('Peanut Noodles', 'Cook noodles; toss with a creamy peanut sauce and vegetables.', 21, 15, 15, 2, 3, 2, 'Beginner', 6),
('Moussaka', 'Layer eggplant, ground meat, and béchamel sauce; bake until golden brown.', 22, 40, 60, 6, 4, 9, 'Advanced', 13),
('Corn Chowder', 'Sauté vegetables and corn in a creamy broth; season to taste.', 23, 15, 25, 4, 3, 1, 'Beginner', 8),
('Steak with Chimichurri', 'Grill steak to desired doneness; top with fresh herb-garlic chimichurri sauce.', 24, 10, 20, 2, 4, 9, 'Intermediate', 7),
('Fruit Salad with Honey-Lime Dressing', 'Combine various fresh fruits; drizzle with a honey-lime dressing.', 25, 15, 0, 4, 5, 9, 'Beginner', 8),
('Pho', 'Prepare a flavorful broth; add rice noodles, herbs, and thinly sliced beef or tofu.', 27, 30, 60, 4, 3, 9, 'Advanced', 11),
('Falafel with Pita and Hummus', 'Grind chickpeas and spices; form into patties and fry or bake; serve in pita with hummus.', 28, 35, 20, 4, 3, 2, 'Intermediate', 12),
('Spanakopita', 'Layer phyllo dough with a spinach and feta cheese filling; bake until golden.', 29, 30, 40, 6, 1, 1, 'Intermediate', 13),
('Paella', 'Cook rice with saffron, seafood, vegetables, and meat in a large shallow pan.', 30, 30, 45, 6, 4, 9, 'Advanced', 14),
('French Onion Soup', 'Caramelize onions; simmer in beef broth with thyme; top with bread and melted cheese.', 31, 20, 40, 4, 3, 9, 'Intermediate', 9),
('Black Forest Cake', 'Layer chocolate cake with whipped cream and cherries; decorate with chocolate shavings.', 33, 45, 30, 8, 5, 9, 'Advanced', 9),
('Banh Mi (Vietnamese Sandwich)', 'Fill a baguette with pickled vegetables, cilantro, jalapeños, and grilled meat or tofu.', 35, 25, 10, 2, 3, 9, 'Intermediate', 11),
('Shakshuka', 'Poach eggs in a flavorful tomato sauce with peppers and spices.', 36, 15, 20, 2, 2, 1, 'Beginner', 12),
('Tabbouleh', 'Combine bulgur wheat, parsley, mint, tomatoes, cucumbers, lemon juice, and olive oil.', 37, 20, 0, 4, 3, 2, 'Beginner', 12),
('Tortilla Soup', 'Simmer tomatoes, onions, garlic, and broth; serve with tortilla strips, avocado, and cheese.', 38, 20, 30, 4, 3, 9, 'Intermediate', 3),
('Tempura Vegetables', 'Dip assorted vegetables in a light batter and deep-fry until crispy.', 39, 20, 15, 3, 1, 2, 'Intermediate', 5),
('Feta and Spinach Stuffed Chicken', 'Stuff chicken breasts with feta cheese and spinach; bake until cooked through.', 41, 20, 30, 4, 4, 9, 'Intermediate', 13),
('Creme brulee', 'Prepare a rich custard base; caramelize a sugar topping with a torch.', 43, 25, 40, 4, 5, 7, 'Advanced', 9),
('Chicken Satay with Peanut Sauce', 'Marinate chicken skewers; grill or bake; serve with a flavorful peanut sauce.', 44, 25, 15, 4, 4, 9, 'Intermediate', 6),
('Savory Vegetable Stir Fry Delight', 'Cook rice; stir in beans and herbs; serve with avocado.', 7, 3, 5, 21, 7, 2, 5, 'Easy'),
('Zesty Tofu Stir Fry Skillet', 'Season chicken; grill until golden; serve with side salad.', 6, 2, 18, 20, 3, 4, 4, 'Intermediate'),
('Hearty Tofu Stir Fry Medley', 'Toast bread; layer with avocado and egg; season and serve.', 5, 3, 26, 26, 5, 1, 4, 'Easy'),
('Hearty Lentil Soup Fusion', 'Roast vegetables; toss with quinoa and feta; drizzle dressing.', 1, 5, 11, 48, 1, 3, 4, 'Intermediate'),
('Tangy Tofu Stir Fry Special', 'Toast bread; layer with avocado and egg; season and serve.', 8, 1, 20, 54, 3, 3, 3, 'Easy'),
('Low-Carb Beef Tacos Medley', 'Marinate beef; pan-sear; serve with mashed potatoes.', 5, 5, 30, 16, 3, 4, 2, 'Advanced'),
('Classic Grilled Chicken Salad and Chickpeas', 'Roast vegetables; toss with quinoa and feta; drizzle dressing.', 7, 5, 15, 32, 5, 5, 5, 'Advanced'),
('Simple Spaghetti Bolognese Bake', 'Sauté onions; add ground beef and sauce; stuff into peppers.', 2, 5, 21, 38, 7, 2, 4, 'Intermediate'),
('Low-Carb Vegetable Stir Fry Surprise', 'Sauté onions; add ground beef and sauce; stuff into peppers.', 2, 2, 16, 47, 6, 4, 3, 'Advanced'),
('Creamy Beef Tacos and Chickpeas', 'Chop vegetables; stir fry with tofu; drizzle with soy sauce.', 4, 4, 9, 11, 8, 5, 3, 'Easy'),
('Tangy Grilled Chicken Salad with Rice', 'Cook shrimp in garlic butter; add cream; toss with pasta.', 7, 1, 8, 31, 1, 2, 1, 'Advanced'),
('Creamy Grilled Chicken Salad Skillet', 'Simmer tomatoes; blend into sauce; pour over pasta.', 6, 4, 10, 33, 6, 5, 2, 'Advanced'),
('Vegan Spaghetti Bolognese with Cheese', 'Cook shrimp in garlic butter; add cream; toss with pasta.', 5, 3, 29, 16, 4, 3, 2, 'Easy'),
('Fresh Chicken Curry Fusion', 'Season chicken; grill until golden; serve with side salad.', 3, 4, 12, 25, 2, 5, 2, 'Intermediate'),
('Classic Tofu Stir Fry Special', 'Cook lentils; add spices and simmer; serve hot with bread.', 3, 5, 17, 22, 7, 1, 3, 'Intermediate'),
('Smoky Shrimp Alfredo Medley', 'Cook lentils; add spices and simmer; serve hot with bread.', 4, 5, 13, 59, 1, 4, 1, 'Advanced'),
('Hearty Lentil Soup Skillet', 'Simmer tomatoes; blend into sauce; pour over pasta.', 5, 5, 21, 34, 1, 2, 5, 'Advanced'),
('Classic Grilled Chicken Salad Bake', 'Mix batter; bake until golden; cool and serve.', 2, 4, 16, 49, 5, 4, 4, 'Intermediate'),
('Savory Spaghetti Bolognese with Rice', 'Marinate beef; pan-sear; serve with mashed potatoes.', 3, 1, 9, 51, 6, 2, 4, 'Advanced'),
('Smoky Grilled Chicken Salad Fiesta', 'Whisk eggs; cook in nonstick pan; sprinkle with cheese.', 8, 2, 26, 44, 4, 2, 5, 'Advanced'),
('Simple Quinoa Bowl Fiesta', 'Chop vegetables; stir fry with tofu; drizzle with soy sauce.', 9, 3, 10, 45, 7, 1, 2, 'Advanced'),
('Crunchy Tofu Stir Fry and Chickpeas', 'Toast bread; layer with avocado and egg; season and serve.', 5, 5, 11, 35, 1, 4, 1, 'Advanced'),
('Hearty Quinoa Bowl with Rice', 'Simmer tomatoes; blend into sauce; pour over pasta.', 2, 3, 17, 49, 1, 1, 3, 'Advanced'),
('Zesty Spaghetti Bolognese with Basil', 'Sauté onions; add ground beef and sauce; stuff into peppers.', 9, 1, 30, 27, 2, 1, 2, 'Advanced'),
('Spicy Grilled Chicken Salad Special', 'Chop vegetables; stir fry with tofu; drizzle with soy sauce.', 1, 4, 24, 51, 6, 4, 4, 'Intermediate'),
('Zesty Quinoa Bowl and Chickpeas', 'Toast bread; layer with avocado and egg; season and serve.', 7, 5, 22, 12, 2, 2, 5, 'Intermediate'),
('Fresh Quinoa Bowl Special', 'Cook lentils; add spices and simmer; serve hot with bread.', 8, 4, 14, 36, 3, 1, 4, 'Easy'),
('Tangy Chicken Curry Bake', 'Sauté onions; add ground beef and sauce; stuff into peppers.', 2, 3, 28, 34, 7, 3, 5, 'Easy'),
('Spicy Chicken Curry Wraps', 'Cook lentils; add spices and simmer; serve hot with bread.', 6, 4, 5, 42, 1, 3, 4, 'Easy'),
('Smoky Beef Tacos Delight', 'Toast bread; layer with avocado and egg; season and serve.', 9, 5, 9, 22, 6, 1, 4, 'Advanced'),
('Hearty Tofu Stir Fry Wraps', 'Boil pasta; sauté vegetables; mix with sauce and serve.', 2, 5, 22, 32, 4, 1, 1, 'Easy'),
('Spicy Pasta Primavera with Rice', 'Boil potatoes; mash with butter and cream; season to taste.', 3, 5, 14, 57, 7, 2, 2, 'Advanced'),
('Low-Carb Shrimp Alfredo Medley', 'Toast bread; layer with avocado and egg; season and serve.', 9, 4, 5, 47, 6, 3, 4, 'Advanced'),
('Savory Shrimp Alfredo Medley', 'Cook rice; stir in beans and herbs; serve with avocado.', 6, 5, 16, 19, 1, 5, 1, 'Intermediate'),
('Spicy Lentil Soup and Chickpeas', 'Cook rice; stir in beans and herbs; serve with avocado.', 3, 2, 29, 18, 3, 2, 1, 'Advanced'),
('Gluten-Free Quinoa Bowl with Rice', 'Roast vegetables; toss with quinoa and feta; drizzle dressing.', 1, 3, 29, 34, 7, 4, 4, 'Advanced'),
('Simple Vegetable Stir Fry and Chickpeas', 'Whisk eggs; cook in nonstick pan; sprinkle with cheese.', 2, 3, 9, 20, 5, 2, 3, 'Easy'),
('Low-Carb Grilled Chicken Salad with Cheese', 'Marinate beef; pan-sear; serve with mashed potatoes.', 3, 5, 10, 22, 5, 5, 5, 'Intermediate'),
('Classic Spaghetti Bolognese and Chickpeas', 'Sauté onions; add ground beef and sauce; stuff into peppers.', 9, 3, 24, 46, 8, 2, 2, 'Intermediate'),
('Crunchy Pasta Primavera Surprise', 'Cook shrimp in garlic butter; add cream; toss with pasta.', 6, 2, 11, 12, 7, 5, 4, 'Advanced'),
('Fresh Chicken Curry Surprise', 'Sauté onions; add ground beef and sauce; stuff into peppers.', 9, 5, 14, 40, 5, 3, 1, 'Advanced'),
('Simple Grilled Chicken Salad Fusion', 'Whisk eggs; cook in nonstick pan; sprinkle with cheese.', 2, 1, 6, 54, 5, 2, 3, 'Advanced'),
('Crunchy Vegetable Stir Fry Delight', 'Simmer tomatoes; blend into sauce; pour over pasta.', 6, 4, 23, 20, 8, 4, 1, 'Easy'),
('Creamy Pasta Primavera Wraps', 'Grill salmon; glaze with teriyaki; serve with steamed rice.', 8, 3, 18, 21, 7, 3, 1, 'Intermediate'),
('Crunchy Spaghetti Bolognese Skillet', 'Cook shrimp in garlic butter; add cream; toss with pasta.', 6, 2, 8, 60, 6, 2, 3, 'Intermediate'),
('Simple Grilled Chicken Salad Wraps', 'Grill salmon; glaze with teriyaki; serve with steamed rice.', 9, 5, 16, 45, 6, 2, 5, 'Advanced'),
('Vegan Shrimp Alfredo with Basil', 'Boil pasta; sauté vegetables; mix with sauce and serve.', 7, 5, 29, 39, 7, 4, 2, 'Easy'),
('Fresh Spaghetti Bolognese Toppers', 'Chop vegetables; stir fry with tofu; drizzle with soy sauce.', 2, 4, 25, 45, 2, 2, 4, 'Advanced'),
('Vegan Vegetable Stir Fry Fusion', 'Boil pasta; sauté vegetables; mix with sauce and serve.', 9, 2, 8, 53, 1, 3, 3, 'Advanced'),
('Fresh Pasta Primavera Fusion', 'Toast bread; layer with avocado and egg; season and serve.', 3, 2, 13, 28, 5, 1, 3, 'Easy'),
('Gluten-Free Tofu Stir Fry Fiesta', 'Season chicken; grill until golden; serve with side salad.', 6, 4, 26, 40, 7, 2, 5, 'Advanced'),
('Spicy Spaghetti Bolognese with Cheese', 'Boil potatoes; mash with butter and cream; season to taste.', 6, 2, 16, 43, 7, 1, 1, 'Easy'),
('Vegan Grilled Chicken Salad Bake', 'Sauté onions; add ground beef and sauce; stuff into peppers.', 9, 4, 16, 54, 1, 5, 2, 'Advanced'),
('Zesty Vegetable Stir Fry Fusion', 'Roast vegetables; toss with quinoa and feta; drizzle dressing.', 4, 2, 24, 21, 4, 4, 4, 'Intermediate'),
('Low-Carb Pasta Primavera with Rice', 'Cook lentils; add spices and simmer; serve hot with bread.', 10, 4, 10, 48, 3, 2, 4, 'Advanced'),
('Tangy Chicken Curry Special', 'Boil pasta; sauté vegetables; mix with sauce and serve.', 8, 5, 26, 33, 1, 5, 4, 'Easy'),
('Hearty Lentil Soup with Basil', 'Marinate beef; pan-sear; serve with mashed potatoes.', 9, 3, 19, 43, 3, 5, 2, 'Advanced'),
('Low-Carb Vegetable Stir Fry Medley', 'Grill salmon; glaze with teriyaki; serve with steamed rice.', 6, 3, 14, 36, 3, 5, 5, 'Intermediate'),
('Vegan Tofu Stir Fry Medley', 'Toast bread; layer with avocado and egg; season and serve.', 3, 2, 17, 38, 2, 2, 5, 'Advanced'),
('Tangy Spaghetti Bolognese with Rice', 'Whisk eggs; cook in nonstick pan; sprinkle with cheese.', 9, 2, 14, 14, 1, 1, 4, 'Easy'),
('Simple Lentil Soup with Cheese', 'Marinate beef; pan-sear; serve with mashed potatoes.', 5, 4, 10, 31, 8, 5, 1, 'Easy'),
('Low-Carb Lentil Soup Wraps', 'Marinate beef; pan-sear; serve with mashed potatoes.', 1, 4, 24, 34, 2, 3, 5, 'Advanced'),
('Hearty Quinoa Bowl Surprise', 'Roast vegetables; toss with quinoa and feta; drizzle dressing.', 3, 4, 19, 22, 1, 2, 1, 'Easy'),
('Zesty Vegetable Stir Fry Skillet', 'Toast bread; layer with avocado and egg; season and serve.', 3, 4, 16, 56, 8, 4, 1, 'Easy'),
('Creamy Vegetable Stir Fry Fiesta', 'Whisk eggs; cook in nonstick pan; sprinkle with cheese.', 6, 3, 5, 57, 6, 4, 2, 'Easy'),
('Vegan Spaghetti Bolognese Skillet', 'Cook rice; stir in beans and herbs; serve with avocado.', 2, 3, 12, 52, 3, 3, 2, 'Easy'),
('Hearty Shrimp Alfredo Delight', 'Roast vegetables; toss with quinoa and feta; drizzle dressing.', 7, 1, 23, 49, 1, 4, 4, 'Advanced'),
('Vegan Chicken Curry Skillet', 'Grill salmon; glaze with teriyaki; serve with steamed rice.', 6, 4, 14, 32, 2, 4, 5, 'Intermediate'),
('Low-Carb Chicken Curry with Basil', 'Cook lentils; add spices and simmer; serve hot with bread.', 8, 2, 10, 58, 4, 2, 5, 'Easy'),
('Crunchy Lentil Soup Surprise', 'Grill salmon; glaze with teriyaki; serve with steamed rice.', 7, 3, 23, 40, 3, 1, 2, 'Easy'),
('Gluten-Free Lentil Soup Fusion', 'Boil potatoes; mash with butter and cream; season to taste.', 7, 1, 19, 53, 2, 1, 3, 'Easy'),
('Crunchy Lentil Soup Delight', 'Cook shrimp in garlic butter; add cream; toss with pasta.', 10, 3, 16, 36, 6, 5, 4, 'Easy'),
('Zesty Lentil Soup Fusion', 'Chop vegetables; stir fry with tofu; drizzle with soy sauce.', 7, 4, 18, 36, 6, 4, 1, 'Advanced'),
('Crunchy Quinoa Bowl Surprise', 'Marinate beef; pan-sear; serve with mashed potatoes.', 3, 4, 11, 60, 8, 3, 4, 'Easy'),
('Simple Chicken Curry Delight', 'Cook rice; stir in beans and herbs; serve with avocado.', 9, 2, 6, 60, 4, 2, 1, 'Advanced'),
('Zesty Chicken Curry Delight', 'Boil pasta; sauté vegetables; mix with sauce and serve.', 7, 1, 15, 48, 2, 5, 1, 'Easy'),
('Vegan Spaghetti Bolognese Fusion', 'Sauté onions; add ground beef and sauce; stuff into peppers.', 4, 3, 30, 38, 3, 2, 4, 'Intermediate'),
('Gluten-Free Chicken Curry Skillet', 'Roast vegetables; toss with quinoa and feta; drizzle dressing.', 10, 1, 19, 44, 2, 3, 2, 'Advanced'),
('Tangy Lentil Soup Medley', 'Boil potatoes; mash with butter and cream; season to taste.', 4, 1, 6, 25, 1, 3, 2, 'Intermediate'),
('Low-Carb Pasta Primavera Surprise', 'Grill salmon; glaze with teriyaki; serve with steamed rice.', 5, 2, 25, 34, 1, 3, 4, 'Easy'),
('Low-Carb Beef Tacos with Cheese', 'Sauté onions; add ground beef and sauce; stuff into peppers.', 1, 3, 14, 29, 5, 3, 4, 'Advanced'),
('Spicy Vegetable Stir Fry Bake', 'Boil pasta; sauté vegetables; mix with sauce and serve.', 10, 1, 27, 12, 6, 2, 1, 'Intermediate'),
('Tangy Shrimp Alfredo Fusion', 'Marinate beef; pan-sear; serve with mashed potatoes.', 7, 4, 9, 27, 3, 5, 5, 'Easy'),
('Savory Shrimp Alfredo Wraps', 'Boil potatoes; mash with butter and cream; season to taste.', 5, 5, 10, 43, 3, 3, 4, 'Intermediate'),
('Simple Lentil Soup Wraps', 'Grill salmon; glaze with teriyaki; serve with steamed rice.', 9, 4, 23, 23, 3, 5, 5, 'Advanced'),
('Smoky Beef Tacos and Chickpeas', 'Boil potatoes; mash with butter and cream; season to taste.', 4, 5, 24, 60, 2, 3, 4, 'Easy'),
('Savory Quinoa Bowl Surprise', 'Roast vegetables; toss with quinoa and feta; drizzle dressing.', 10, 1, 8, 42, 5, 2, 3, 'Easy'),
('Simple Chicken Curry Surprise', 'Marinate beef; pan-sear; serve with mashed potatoes.', 1, 5, 26, 53, 6, 2, 2, 'Easy'),
('Hearty Pasta Primavera Fusion', 'Mix batter; bake until golden; cool and serve.', 2, 4, 27, 27, 3, 5, 5, 'Intermediate'),
('Vegan Shrimp Alfredo Wraps', 'Sauté onions; add ground beef and sauce; stuff into peppers.', 4, 5, 7, 59, 6, 2, 3, 'Easy'),
('Tangy Grilled Chicken Salad with Cheese', 'Cook rice; stir in beans and herbs; serve with avocado.', 2, 4, 13, 15, 8, 5, 2, 'Intermediate'),
('Tangy Chicken Curry with Cheese', 'Toast bread; layer with avocado and egg; season and serve.', 1, 3, 24, 50, 5, 4, 4, 'Intermediate'),
('Crunchy Grilled Chicken Salad Special', 'Sauté onions; add ground beef and sauce; stuff into peppers.', 8, 4, 7, 35, 4, 4, 1, 'Intermediate'),
('Low-Carb Spaghetti Bolognese with Cheese', 'Cook rice; stir in beans and herbs; serve with avocado.', 8, 5, 27, 24, 3, 5, 4, 'Easy'),
('Spicy Spaghetti Bolognese and Chickpeas', 'Sauté onions; add ground beef and sauce; stuff into peppers.', 3, 2, 12, 13, 8, 3, 1, 'Easy'),
('Hearty Pasta Primavera Medley', 'Cook rice; stir in beans and herbs; serve with avocado.', 6, 2, 29, 34, 7, 2, 5, 'Easy'),
('Fresh Beef Tacos Bake', 'Season chicken; grill until golden; serve with side salad.', 8, 2, 8, 59, 5, 2, 3, 'Easy'),
('Savory Quinoa Bowl with Cheese', 'Chop vegetables; stir fry with tofu; drizzle with soy sauce.', 6, 4, 14, 41, 8, 2, 5, 'Easy'),
('Gluten-Free Vegetable Stir Fry Toppers', 'Boil potatoes; mash with butter and cream; season to taste.', 10, 3, 23, 17, 3, 1, 2, 'Intermediate'),
('Hearty Grilled Chicken Salad Skillet', 'Sauté onions; add ground beef and sauce; stuff into peppers.', 9, 2, 21, 24, 6, 3, 3, 'Easy'),
('Creamy Lentil Soup with Rice', 'Marinate beef; pan-sear; serve with mashed potatoes.', 10, 2, 18, 36, 8, 1, 3, 'Easy'),
('Fresh Chicken Curry and Chickpeas', 'Cook lentils; add spices and simmer; serve hot with bread.', 9, 2, 29, 46, 3, 3, 5, 'Easy'),
('Hearty Lentil Soup with Rice', 'Sauté onions; add ground beef and sauce; stuff into peppers.', 10, 5, 19, 27, 7, 1, 3, 'Intermediate'),
('Low-Carb Spaghetti Bolognese Medley', 'Cook rice; stir in beans and herbs; serve with avocado.', 7, 4, 6, 51, 5, 4, 1, 'Easy'),
('Fresh Tofu Stir Fry Delight', 'Boil pasta; sauté vegetables; mix with sauce and serve.', 1, 2, 11, 16, 5, 5, 5, 'Intermediate'),
('Vegan Beef Tacos with Basil', 'Cook shrimp in garlic butter; add cream; toss with pasta.', 9, 2, 17, 45, 8, 3, 2, 'Easy'),
('Fresh Spaghetti Bolognese and Chickpeas', 'Cook shrimp in garlic butter; add cream; toss with pasta.', 6, 3, 19, 56, 6, 4, 5, 'Advanced'),
('Vegan Quinoa Bowl Delight', 'Cook lentils; add spices and simmer; serve hot with bread.', 5, 1, 19, 17, 3, 3, 4, 'Intermediate'),
('Fresh Vegetable Stir Fry Wraps', 'Roast vegetables; toss with quinoa and feta; drizzle dressing.', 10, 3, 21, 60, 3, 3, 3, 'Intermediate'),
('Vegan Chicken Curry and Chickpeas', 'Toast bread; layer with avocado and egg; season and serve.', 9, 4, 22, 20, 4, 3, 5, 'Easy'),
('Simple Shrimp Alfredo Bake', 'Marinate beef; pan-sear; serve with mashed potatoes.', 10, 1, 11, 39, 4, 2, 1, 'Advanced'),
('Smoky Beef Tacos Fiesta', 'Cook rice; stir in beans and herbs; serve with avocado.', 7, 1, 13, 29, 4, 4, 3, 'Intermediate'),
('Hearty Vegetable Stir Fry Toppers', 'Boil potatoes; mash with butter and cream; season to taste.', 4, 5, 6, 22, 5, 5, 5, 'Advanced'),
('Hearty Lentil Soup Toppers', 'Cook lentils; add spices and simmer; serve hot with bread.', 2, 4, 17, 16, 5, 1, 1, 'Advanced'),
('Low-Carb Quinoa Bowl and Chickpeas', 'Whisk eggs; cook in nonstick pan; sprinkle with cheese.', 1, 3, 24, 12, 1, 3, 3, 'Intermediate'),
('Creamy Beef Tacos Delight', 'Mix batter; bake until golden; cool and serve.', 5, 2, 28, 50, 5, 2, 5, 'Intermediate'),
('Tangy Vegetable Stir Fry Special', 'Cook rice; stir in beans and herbs; serve with avocado.', 8, 4, 27, 26, 8, 5, 3, 'Easy'),
('Simple Shrimp Alfredo Medley', 'Cook lentils; add spices and simmer; serve hot with bread.', 4, 3, 7, 26, 1, 3, 3, 'Advanced'),
('Hearty Chicken Curry Fiesta', 'Toast bread; layer with avocado and egg; season and serve.', 2, 2, 11, 50, 1, 2, 1, 'Intermediate'),
('Classic Beef Tacos with Basil', 'Simmer tomatoes; blend into sauce; pour over pasta.', 3, 4, 29, 56, 6, 2, 3, 'Intermediate'),
('Vegan Chicken Curry Wraps', 'Cook shrimp in garlic butter; add cream; toss with pasta.', 7, 4, 5, 20, 7, 2, 2, 'Advanced'),
('Simple Spaghetti Bolognese and Chickpeas', 'Season chicken; grill until golden; serve with side salad.', 1, 5, 5, 32, 4, 5, 1, 'Advanced'),
('Simple Vegetable Stir Fry Fiesta', 'Chop vegetables; stir fry with tofu; drizzle with soy sauce.', 4, 2, 10, 41, 4, 3, 4, 'Easy'),
('Hearty Shrimp Alfredo Special', 'Mix batter; bake until golden; cool and serve.', 6, 5, 26, 41, 7, 1, 1, 'Intermediate'),
('Tangy Beef Tacos and Chickpeas', 'Cook lentils; add spices and simmer; serve hot with bread.', 5, 5, 10, 21, 7, 2, 1, 'Advanced'),
('Crunchy Lentil Soup Fusion', 'Boil pasta; sauté vegetables; mix with sauce and serve.', 1, 3, 11, 41, 3, 2, 1, 'Intermediate'),
('Zesty Quinoa Bowl Special', 'Sauté onions; add ground beef and sauce; stuff into peppers.', 8, 2, 6, 18, 5, 3, 3, 'Easy'),
('Fresh Quinoa Bowl Skillet', 'Grill salmon; glaze with teriyaki; serve with steamed rice.', 10, 5, 13, 35, 8, 2, 5, 'Advanced'),
('Crunchy Beef Tacos Surprise', 'Season chicken; grill until golden; serve with side salad.', 7, 5, 17, 44, 1, 4, 1, 'Advanced'),
('Spicy Lentil Soup Wraps', 'Boil pasta; sauté vegetables; mix with sauce and serve.', 7, 2, 22, 45, 2, 4, 4, 'Intermediate'),
('Vegan Lentil Soup Delight', 'Sauté onions; add ground beef and sauce; stuff into peppers.', 9, 4, 16, 47, 7, 2, 3, 'Easy'),
('Savory Shrimp Alfredo Skillet', 'Boil potatoes; mash with butter and cream; season to taste.', 4, 2, 27, 30, 6, 4, 1, 'Advanced'),
('Tangy Shrimp Alfredo with Cheese', 'Season chicken; grill until golden; serve with side salad.', 7, 1, 12, 30, 2, 1, 2, 'Easy'),
('Creamy Chicken Curry with Cheese', 'Season chicken; grill until golden; serve with side salad.', 2, 1, 18, 56, 4, 3, 4, 'Advanced'),
('Simple Pasta Primavera with Basil', 'Grill salmon; glaze with teriyaki; serve with steamed rice.', 6, 3, 10, 22, 6, 5, 2, 'Intermediate'),
('Classic Lentil Soup Special', 'Simmer tomatoes; blend into sauce; pour over pasta.', 5, 2, 26, 27, 8, 1, 4, 'Advanced'),
('Classic Grilled Chicken Salad Delight', 'Roast vegetables; toss with quinoa and feta; drizzle dressing.', 10, 1, 8, 10, 1, 3, 5, 'Advanced'),
('Zesty Quinoa Bowl Fiesta', 'Cook rice; stir in beans and herbs; serve with avocado.', 3, 1, 11, 28, 2, 2, 5, 'Intermediate'),
('Tangy Tofu Stir Fry Fiesta', 'Marinate beef; pan-sear; serve with mashed potatoes.', 4, 2, 8, 43, 6, 5, 1, 'Intermediate'),
('Savory Grilled Chicken Salad Fiesta', 'Simmer tomatoes; blend into sauce; pour over pasta.', 9, 5, 5, 50, 6, 3, 2, 'Intermediate'),
('Vegan Chicken Curry Bake', 'Boil pasta; sauté vegetables; mix with sauce and serve.', 3, 2, 16, 33, 7, 2, 5, 'Easy'),
('Savory Grilled Chicken Salad Medley', 'Boil potatoes; mash with butter and cream; season to taste.', 10, 1, 30, 51, 1, 5, 2, 'Advanced'),
('Spicy Vegetable Stir Fry with Rice', 'Cook rice; stir in beans and herbs; serve with avocado.', 6, 2, 28, 33, 4, 3, 3, 'Advanced'),
('Gluten-Free Grilled Chicken Salad Surprise', 'Mix batter; bake until golden; cool and serve.', 9, 4, 25, 45, 1, 4, 3, 'Easy'),
('Zesty Beef Tacos Wraps', 'Whisk eggs; cook in nonstick pan; sprinkle with cheese.', 6, 2, 14, 28, 7, 2, 2, 'Advanced'),
('Spicy Lentil Soup Fusion', 'Toast bread; layer with avocado and egg; season and serve.', 8, 3, 20, 11, 3, 2, 3, 'Intermediate'),
('Zesty Tofu Stir Fry Toppers', 'Boil pasta; sauté vegetables; mix with sauce and serve.', 4, 1, 19, 47, 6, 5, 1, 'Intermediate'),
('Fresh Tofu Stir Fry with Basil', 'Marinate beef; pan-sear; serve with mashed potatoes.', 1, 1, 18, 51, 4, 1, 4, 'Advanced'),
('Savory Tofu Stir Fry Special', 'Season chicken; grill until golden; serve with side salad.', 2, 5, 18, 24, 8, 2, 4, 'Advanced'),
('Hearty Grilled Chicken Salad Wraps', 'Mix batter; bake until golden; cool and serve.', 7, 5, 12, 38, 6, 1, 2, 'Easy'),
('Creamy Chicken Curry Wraps', 'Boil pasta; sauté vegetables; mix with sauce and serve.', 2, 4, 19, 22, 8, 5, 5, 'Easy'),
('Hearty Quinoa Bowl with Basil', 'Simmer tomatoes; blend into sauce; pour over pasta.', 1, 5, 26, 27, 8, 2, 1, 'Advanced'),
('Creamy Pasta Primavera Toppers', 'Boil potatoes; mash with butter and cream; season to taste.', 3, 3, 11, 17, 5, 5, 5, 'Easy'),
('Gluten-Free Pasta Primavera Fiesta', 'Roast vegetables; toss with quinoa and feta; drizzle dressing.', 10, 2, 10, 23, 8, 2, 5, 'Intermediate'),
('Spicy Lentil Soup Skillet', 'Chop vegetables; stir fry with tofu; drizzle with soy sauce.', 2, 2, 28, 11, 4, 1, 5, 'Easy'),
('Creamy Chicken Curry Toppers', 'Boil potatoes; mash with butter and cream; season to taste.', 6, 1, 27, 31, 8, 4, 2, 'Intermediate'),
('Vegan Shrimp Alfredo Bake', 'Chop vegetables; stir fry with tofu; drizzle with soy sauce.', 7, 3, 25, 27, 6, 4, 5, 'Easy'),
('Tangy Quinoa Bowl Fiesta', 'Cook shrimp in garlic butter; add cream; toss with pasta.', 2, 2, 23, 46, 8, 5, 3, 'Intermediate'),
('Simple Vegetable Stir Fry Fusion', 'Boil pasta; sauté vegetables; mix with sauce and serve.', 4, 3, 8, 47, 8, 4, 3, 'Intermediate'),
('Smoky Spaghetti Bolognese Special', 'Grill salmon; glaze with teriyaki; serve with steamed rice.', 6, 2, 29, 16, 7, 1, 5, 'Advanced'),
('Fresh Pasta Primavera with Basil', 'Sauté onions; add ground beef and sauce; stuff into peppers.', 4, 4, 21, 18, 5, 4, 1, 'Advanced'),
('Fresh Vegetable Stir Fry with Cheese', 'Cook lentils; add spices and simmer; serve hot with bread.', 9, 2, 14, 39, 5, 3, 3, 'Intermediate'),
('Low-Carb Tofu Stir Fry Skillet', 'Grill salmon; glaze with teriyaki; serve with steamed rice.', 5, 3, 23, 29, 2, 5, 4, 'Intermediate'),
('Savory Tofu Stir Fry Surprise', 'Grill salmon; glaze with teriyaki; serve with steamed rice.', 5, 1, 16, 22, 8, 5, 3, 'Advanced'),
('Classic Grilled Chicken Salad with Rice', 'Sauté onions; add ground beef and sauce; stuff into peppers.', 5, 1, 26, 43, 6, 3, 5, 'Advanced'),
('Gluten-Free Shrimp Alfredo and Chickpeas', 'Marinate beef; pan-sear; serve with mashed potatoes.', 2, 5, 5, 23, 8, 5, 1, 'Advanced'),
('Spicy Vegetable Stir Fry Wraps', 'Cook rice; stir in beans and herbs; serve with avocado.', 1, 3, 26, 46, 3, 5, 4, 'Easy'),
('Spicy Tofu Stir Fry Wraps', 'Whisk eggs; cook in nonstick pan; sprinkle with cheese.', 7, 4, 8, 21, 8, 5, 5, 'Advanced'),
('Simple Quinoa Bowl Fusion', 'Simmer tomatoes; blend into sauce; pour over pasta.', 10, 4, 27, 29, 8, 4, 5, 'Easy'),
('Vegan Grilled Chicken Salad with Rice', 'Cook lentils; add spices and simmer; serve hot with bread.', 2, 4, 25, 19, 5, 3, 5, 'Advanced'),
('Classic Chicken Curry with Rice', 'Cook rice; stir in beans and herbs; serve with avocado.', 6, 1, 29, 37, 8, 1, 4, 'Intermediate'),
('Low-Carb Shrimp Alfredo Surprise', 'Boil potatoes; mash with butter and cream; season to taste.', 8, 3, 29, 12, 4, 3, 2, 'Easy'),
('Crunchy Shrimp Alfredo Toppers', 'Boil potatoes; mash with butter and cream; season to taste.', 7, 4, 14, 54, 6, 1, 2, 'Easy'),
('Vegan Tofu Stir Fry Toppers', 'Chop vegetables; stir fry with tofu; drizzle with soy sauce.', 1, 2, 12, 42, 3, 3, 1, 'Intermediate'),
('Creamy Grilled Chicken Salad Fiesta', 'Grill salmon; glaze with teriyaki; serve with steamed rice.', 9, 5, 17, 24, 8, 4, 4, 'Intermediate'),
('Savory Shrimp Alfredo Surprise', 'Boil pasta; sauté vegetables; mix with sauce and serve.', 9, 2, 21, 38, 5, 4, 3, 'Easy'),
('Spicy Chicken Curry Surprise', 'Mix batter; bake until golden; cool and serve.', 7, 4, 6, 24, 4, 3, 2, 'Easy'),
('Tangy Chicken Curry Toppers', 'Roast vegetables; toss with quinoa and feta; drizzle dressing.', 2, 5, 11, 12, 4, 2, 4, 'Intermediate'),
('Hearty Lentil Soup Bake', 'Boil pasta; sauté vegetables; mix with sauce and serve.', 8, 1, 28, 14, 1, 2, 4, 'Intermediate'),
('Hearty Tofu Stir Fry Special', 'Mix batter; bake until golden; cool and serve.', 5, 5, 30, 21, 7, 2, 5, 'Easy'),
('Tangy Shrimp Alfredo Bake', 'Season chicken; grill until golden; serve with side salad.', 5, 1, 6, 46, 6, 2, 2, 'Easy'),
('Crunchy Lentil Soup with Rice', 'Sauté onions; add ground beef and sauce; stuff into peppers.', 9, 2, 22, 26, 4, 1, 1, 'Easy'),
('Zesty Spaghetti Bolognese Fusion', 'Marinate beef; pan-sear; serve with mashed potatoes.', 2, 4, 19, 55, 2, 5, 3, 'Intermediate'),
('Fresh Shrimp Alfredo Medley', 'Cook shrimp in garlic butter; add cream; toss with pasta.', 3, 1, 17, 17, 7, 1, 1, 'Intermediate'),
('Smoky Lentil Soup with Basil', 'Cook lentils; add spices and simmer; serve hot with bread.', 3, 2, 19, 60, 3, 1, 1, 'Easy'),
('Gluten-Free Beef Tacos with Rice', 'Toast bread; layer with avocado and egg; season and serve.', 5, 4, 26, 20, 1, 2, 5, 'Advanced'),
('Crunchy Vegetable Stir Fry Toppers', 'Whisk eggs; cook in nonstick pan; sprinkle with cheese.', 5, 3, 16, 46, 4, 4, 4, 'Intermediate'),
('Hearty Chicken Curry Toppers', 'Whisk eggs; cook in nonstick pan; sprinkle with cheese.', 3, 4, 12, 48, 1, 1, 5, 'Advanced'),
('Vegan Pasta Primavera Fiesta', 'Toast bread; layer with avocado and egg; season and serve.', 3, 5, 10, 23, 4, 4, 1, 'Advanced'),
('Fresh Chicken Curry with Basil', 'Boil pasta; sauté vegetables; mix with sauce and serve.', 8, 2, 18, 48, 1, 3, 5, 'Easy'),
('Crunchy Chicken Curry with Rice', 'Season chicken; grill until golden; serve with side salad.', 9, 3, 6, 44, 1, 3, 2, 'Intermediate'),
('Savory Chicken Curry Fusion', 'Mix batter; bake until golden; cool and serve.', 3, 4, 18, 54, 1, 3, 2, 'Easy'),
('Fresh Beef Tacos with Basil', 'Chop vegetables; stir fry with tofu; drizzle with soy sauce.', 3, 4, 30, 47, 2, 3, 2, 'Intermediate'),
('Hearty Tofu Stir Fry and Chickpeas', 'Simmer tomatoes; blend into sauce; pour over pasta.', 9, 4, 22, 30, 8, 5, 3, 'Advanced'),
('Smoky Chicken Curry with Basil', 'Roast vegetables; toss with quinoa and feta; drizzle dressing.', 9, 2, 5, 29, 6, 3, 1, 'Intermediate'),
('Creamy Pasta Primavera with Cheese', 'Grill salmon; glaze with teriyaki; serve with steamed rice.', 5, 3, 22, 19, 3, 2, 4, 'Easy'),
('Crunchy Shrimp Alfredo with Cheese', 'Mix batter; bake until golden; cool and serve.', 7, 3, 17, 11, 6, 3, 4, 'Intermediate'),
('Fresh Grilled Chicken Salad with Cheese', 'Sauté onions; add ground beef and sauce; stuff into peppers.', 7, 2, 8, 14, 4, 4, 4, 'Advanced'),
('Hearty Pasta Primavera Wraps', 'Boil potatoes; mash with butter and cream; season to taste.', 2, 1, 12, 22, 6, 1, 2, 'Easy'),
('Gluten-Free Spaghetti Bolognese Bake', 'Roast vegetables; toss with quinoa and feta; drizzle dressing.', 6, 5, 7, 18, 2, 3, 2, 'Intermediate'),
('Vegan Vegetable Stir Fry Bake', 'Boil potatoes; mash with butter and cream; season to taste.', 7, 3, 19, 30, 3, 3, 4, 'Advanced'),
('Smoky Pasta Primavera Wraps', 'Boil pasta; sauté vegetables; mix with sauce and serve.', 3, 1, 14, 32, 4, 2, 5, 'Easy'),
('Smoky Quinoa Bowl Medley', 'Toast bread; layer with avocado and egg; season and serve.', 9, 4, 20, 59, 4, 4, 2, 'Advanced'),
('Simple Grilled Chicken Salad Delight', 'Cook lentils; add spices and simmer; serve hot with bread.', 3, 4, 23, 22, 3, 3, 1, 'Easy'),
('Smoky Chicken Curry and Chickpeas', 'Season chicken; grill until golden; serve with side salad.', 5, 2, 29, 29, 5, 4, 3, 'Intermediate'),
('Crunchy Grilled Chicken Salad Wraps', 'Cook lentils; add spices and simmer; serve hot with bread.', 7, 2, 30, 35, 1, 3, 4, 'Advanced'),
('Spicy Beef Tacos Fiesta', 'Sauté onions; add ground beef and sauce; stuff into peppers.', 7, 3, 7, 16, 5, 4, 1, 'Intermediate'),
('Classic Pasta Primavera Delight', 'Season chicken; grill until golden; serve with side salad.', 1, 5, 13, 45, 4, 2, 1, 'Easy'),
('Creamy Spaghetti Bolognese Special', 'Mix batter; bake until golden; cool and serve.', 8, 2, 6, 47, 2, 2, 3, 'Intermediate'),
('Tangy Chicken Curry Fusion', 'Boil pasta; sauté vegetables; mix with sauce and serve.', 5, 4, 10, 23, 8, 5, 3, 'Intermediate'),
('Smoky Quinoa Bowl with Rice', 'Cook shrimp in garlic butter; add cream; toss with pasta.', 6, 3, 7, 42, 6, 5, 4, 'Advanced'),
('Spicy Quinoa Bowl Wraps', 'Cook shrimp in garlic butter; add cream; toss with pasta.', 5, 5, 14, 24, 7, 3, 2, 'Easy'),
('Vegan Quinoa Bowl and Chickpeas', 'Cook shrimp in garlic butter; add cream; toss with pasta.', 2, 1, 22, 47, 3, 1, 4, 'Advanced'),
('Simple Vegetable Stir Fry Special', 'Toast bread; layer with avocado and egg; season and serve.', 8, 4, 30, 28, 6, 3, 5, 'Advanced'),
('Tangy Beef Tacos Fiesta', 'Chop vegetables; stir fry with tofu; drizzle with soy sauce.', 8, 2, 9, 24, 6, 1, 4, 'Intermediate'),
('Zesty Tofu Stir Fry Fusion', 'Season chicken; grill until golden; serve with side salad.', 1, 5, 5, 38, 1, 4, 5, 'Easy'),
('Classic Shrimp Alfredo Delight', 'Cook shrimp in garlic butter; add cream; toss with pasta.', 4, 3, 20, 44, 8, 4, 1, 'Easy'),
('Vegan Beef Tacos Toppers', 'Toast bread; layer with avocado and egg; season and serve.', 10, 4, 30, 44, 4, 3, 4, 'Advanced'),
('Smoky Shrimp Alfredo Bake', 'Sauté onions; add ground beef and sauce; stuff into peppers.', 10, 4, 21, 33, 2, 2, 1, 'Advanced'),
('Crunchy Lentil Soup with Basil', 'Boil pasta; sauté vegetables; mix with sauce and serve.', 10, 4, 8, 20, 8, 4, 2, 'Intermediate'),
('Simple Lentil Soup Surprise', 'Sauté onions; add ground beef and sauce; stuff into peppers.', 1, 2, 8, 56, 1, 3, 5, 'Intermediate'),
('Low-Carb Spaghetti Bolognese Delight', 'Cook lentils; add spices and simmer; serve hot with bread.', 7, 3, 16, 29, 1, 1, 2, 'Intermediate'),
('Low-Carb Vegetable Stir Fry and Chickpeas', 'Cook lentils; add spices and simmer; serve hot with bread.', 2, 1, 30, 13, 2, 3, 1, 'Advanced'),
('Tangy Quinoa Bowl Toppers', 'Chop vegetables; stir fry with tofu; drizzle with soy sauce.', 1, 4, 27, 48, 7, 3, 5, 'Easy'),
('Gluten-Free Chicken Curry with Rice', 'Mix batter; bake until golden; cool and serve.', 4, 2, 5, 20, 7, 2, 1, 'Intermediate'),
('Simple Vegetable Stir Fry Surprise', 'Boil pasta; sauté vegetables; mix with sauce and serve.', 1, 5, 27, 59, 8, 4, 2, 'Easy'),
('Creamy Chicken Curry Skillet', 'Roast vegetables; toss with quinoa and feta; drizzle dressing.', 7, 4, 16, 18, 4, 3, 2, 'Easy'),
('Spicy Chicken Curry Special', 'Season chicken; grill until golden; serve with side salad.', 2, 2, 24, 47, 2, 5, 1, 'Advanced'),
('Gluten-Free Grilled Chicken Salad Toppers', 'Mix batter; bake until golden; cool and serve.', 6, 2, 17, 55, 8, 2, 1, 'Intermediate'),
('Spicy Vegetable Stir Fry and Chickpeas', 'Roast vegetables; toss with quinoa and feta; drizzle dressing.', 3, 4, 9, 20, 7, 5, 4, 'Intermediate'),
('Simple Quinoa Bowl Wraps', 'Toast bread; layer with avocado and egg; season and serve.', 4, 5, 27, 57, 7, 3, 2, 'Intermediate'),
('Zesty Beef Tacos Surprise', 'Roast vegetables; toss with quinoa and feta; drizzle dressing.', 8, 3, 20, 38, 5, 1, 1, 'Easy'),
('Smoky Spaghetti Bolognese with Rice', 'Toast bread; layer with avocado and egg; season and serve.', 2, 4, 7, 38, 2, 1, 1, 'Intermediate'),
('Gluten-Free Vegetable Stir Fry with Cheese', 'Boil potatoes; mash with butter and cream; season to taste.', 8, 4, 14, 45, 4, 4, 5, 'Easy'),
('Tangy Pasta Primavera with Cheese', 'Boil potatoes; mash with butter and cream; season to taste.', 3, 2, 17, 50, 7, 1, 2, 'Intermediate'),
('Low-Carb Grilled Chicken Salad Delight', 'Chop vegetables; stir fry with tofu; drizzle with soy sauce.', 3, 4, 23, 39, 2, 1, 2, 'Intermediate'),
('Smoky Tofu Stir Fry Toppers', 'Grill salmon; glaze with teriyaki; serve with steamed rice.', 2, 5, 18, 46, 2, 3, 3, 'Advanced'),
('Creamy Quinoa Bowl with Cheese', 'Cook lentils; add spices and simmer; serve hot with bread.', 1, 5, 9, 37, 6, 1, 4, 'Intermediate'),
('Vegan Shrimp Alfredo Fiesta', 'Cook rice; stir in beans and herbs; serve with avocado.', 8, 5, 27, 30, 1, 3, 2, 'Easy'),
('Spicy Lentil Soup Delight', 'Boil pasta; sauté vegetables; mix with sauce and serve.', 6, 5, 5, 36, 7, 2, 3, 'Intermediate'),
('Smoky Lentil Soup Bake', 'Season chicken; grill until golden; serve with side salad.', 5, 4, 18, 20, 5, 1, 1, 'Intermediate'),
('Creamy Shrimp Alfredo Skillet', 'Chop vegetables; stir fry with tofu; drizzle with soy sauce.', 4, 5, 19, 50, 5, 1, 3, 'Advanced'),
('Creamy Chicken Curry Special', 'Simmer tomatoes; blend into sauce; pour over pasta.', 1, 2, 28, 43, 8, 2, 3, 'Easy'),
('Vegan Vegetable Stir Fry Skillet', 'Marinate beef; pan-sear; serve with mashed potatoes.', 10, 3, 27, 59, 4, 5, 1, 'Intermediate'),
('Savory Shrimp Alfredo Delight', 'Cook lentils; add spices and simmer; serve hot with bread.', 9, 3, 6, 14, 2, 3, 3, 'Intermediate'),
('Hearty Chicken Curry with Rice', 'Boil pasta; sauté vegetables; mix with sauce and serve.', 4, 1, 23, 21, 6, 2, 3, 'Easy'),
('Vegan Shrimp Alfredo Delight', 'Boil potatoes; mash with butter and cream; season to taste.', 10, 2, 9, 52, 6, 1, 2, 'Advanced'),
('Simple Chicken Curry Wraps', 'Cook rice; stir in beans and herbs; serve with avocado.', 4, 5, 17, 20, 7, 5, 2, 'Easy'),
('Hearty Chicken Curry Delight', 'Boil pasta; sauté vegetables; mix with sauce and serve.', 1, 1, 19, 51, 6, 3, 4, 'Intermediate'),
('Savory Tofu Stir Fry Bake', 'Simmer tomatoes; blend into sauce; pour over pasta.', 7, 3, 25, 40, 7, 4, 5, 'Advanced'),
('Creamy Lentil Soup and Chickpeas', 'Mix batter; bake until golden; cool and serve.', 9, 3, 29, 18, 6, 2, 3, 'Easy'),
('Smoky Lentil Soup Medley', 'Grill salmon; glaze with teriyaki; serve with steamed rice.', 8, 2, 18, 46, 3, 3, 3, 'Easy'),
('Gluten-Free Chicken Curry with Cheese', 'Grill salmon; glaze with teriyaki; serve with steamed rice.', 6, 3, 16, 30, 4, 1, 3, 'Intermediate'),
('Zesty Beef Tacos Delight', 'Boil potatoes; mash with butter and cream; season to taste.', 4, 2, 30, 37, 4, 5, 1, 'Intermediate'),
('Gluten-Free Tofu Stir Fry with Rice', 'Boil pasta; sauté vegetables; mix with sauce and serve.', 8, 1, 28, 54, 1, 1, 3, 'Intermediate'),
('Vegan Beef Tacos Delight', 'Mix batter; bake until golden; cool and serve.', 7, 5, 23, 36, 4, 1, 5, 'Intermediate'),
('Gluten-Free Shrimp Alfredo Fiesta', 'Simmer tomatoes; blend into sauce; pour over pasta.', 6, 4, 13, 49, 8, 3, 2, 'Advanced'),
('Gluten-Free Chicken Curry Delight', 'Chop vegetables; stir fry with tofu; drizzle with soy sauce.', 1, 4, 19, 53, 8, 3, 4, 'Advanced'),
('Gluten-Free Grilled Chicken Salad Wraps', 'Sauté onions; add ground beef and sauce; stuff into peppers.', 3, 2, 27, 50, 3, 1, 2, 'Advanced'),
('Fresh Pasta Primavera Fiesta', 'Boil potatoes; mash with butter and cream; season to taste.', 3, 3, 28, 27, 5, 5, 2, 'Easy'),
('Gluten-Free Pasta Primavera Surprise', 'Boil potatoes; mash with butter and cream; season to taste.', 4, 3, 21, 39, 4, 4, 1, 'Easy'),
('Savory Lentil Soup and Chickpeas', 'Simmer tomatoes; blend into sauce; pour over pasta.', 3, 5, 22, 33, 6, 1, 5, 'Advanced'),
('Tangy Pasta Primavera Fusion', 'Sauté onions; add ground beef and sauce; stuff into peppers.', 3, 4, 27, 56, 2, 2, 3, 'Advanced'),
('Classic Chicken Curry Special', 'Boil potatoes; mash with butter and cream; season to taste.', 2, 2, 20, 27, 2, 3, 4, 'Easy'),
('Gluten-Free Vegetable Stir Fry with Basil', 'Boil pasta; sauté vegetables; mix with sauce and serve.', 2, 5, 27, 51, 6, 3, 1, 'Intermediate'),
('Gluten-Free Lentil Soup Surprise', 'Grill salmon; glaze with teriyaki; serve with steamed rice.', 4, 4, 26, 22, 6, 3, 4, 'Intermediate'),
('Tangy Spaghetti Bolognese Fusion', 'Toast bread; layer with avocado and egg; season and serve.', 6, 2, 14, 37, 7, 2, 5, 'Intermediate'),
('Zesty Tofu Stir Fry Bake', 'Cook shrimp in garlic butter; add cream; toss with pasta.', 4, 4, 27, 15, 4, 5, 3, 'Advanced'),
('Creamy Spaghetti Bolognese with Cheese', 'Season chicken; grill until golden; serve with side salad.', 4, 2, 20, 22, 6, 5, 1, 'Intermediate'),
('Tangy Quinoa Bowl Bake', 'Toast bread; layer with avocado and egg; season and serve.', 1, 4, 14, 35, 3, 5, 2, 'Easy'),
('Creamy Lentil Soup Medley', 'Sauté onions; add ground beef and sauce; stuff into peppers.', 1, 3, 6, 57, 5, 5, 3, 'Advanced'),
('Spicy Shrimp Alfredo Fusion', 'Cook lentils; add spices and simmer; serve hot with bread.', 7, 1, 9, 29, 8, 4, 5, 'Intermediate'),
('Smoky Shrimp Alfredo Delight', 'Boil pasta; sauté vegetables; mix with sauce and serve.', 1, 5, 13, 52, 5, 1, 1, 'Intermediate'),
('Vegan Lentil Soup with Basil', 'Season chicken; grill until golden; serve with side salad.', 2, 5, 23, 45, 1, 3, 1, 'Intermediate'),
('Fresh Grilled Chicken Salad Surprise', 'Whisk eggs; cook in nonstick pan; sprinkle with cheese.', 1, 2, 12, 58, 4, 3, 1, 'Intermediate'),
('Spicy Tofu Stir Fry Special', 'Mix batter; bake until golden; cool and serve.', 1, 2, 21, 11, 2, 3, 3, 'Intermediate'),
('Fresh Quinoa Bowl Wraps', 'Boil potatoes; mash with butter and cream; season to taste.', 10, 1, 10, 55, 8, 4, 5, 'Easy'),
('Hearty Quinoa Bowl Fusion', 'Roast vegetables; toss with quinoa and feta; drizzle dressing.', 3, 2, 8, 35, 2, 2, 1, 'Easy'),
('Savory Lentil Soup Wraps', 'Whisk eggs; cook in nonstick pan; sprinkle with cheese.', 8, 5, 8, 44, 2, 1, 1, 'Advanced'),
('Simple Lentil Soup Medley', 'Season chicken; grill until golden; serve with side salad.', 9, 4, 27, 16, 1, 4, 5, 'Easy'),
('Zesty Beef Tacos Special', 'Grill salmon; glaze with teriyaki; serve with steamed rice.', 7, 3, 22, 25, 1, 4, 1, 'Easy'),
('Zesty Shrimp Alfredo Skillet', 'Marinate beef; pan-sear; serve with mashed potatoes.', 10, 3, 15, 56, 6, 2, 1, 'Advanced'),
('Smoky Spaghetti Bolognese Bake', 'Cook shrimp in garlic butter; add cream; toss with pasta.', 1, 2, 27, 12, 1, 2, 1, 'Intermediate'),
('Vegan Spaghetti Bolognese Fiesta', 'Simmer tomatoes; blend into sauce; pour over pasta.', 10, 5, 24, 55, 8, 4, 4, 'Intermediate'),
('Vegan Lentil Soup Bake', 'Simmer tomatoes; blend into sauce; pour over pasta.', 6, 3, 10, 46, 8, 5, 4, 'Easy'),
('Classic Grilled Chicken Salad Wraps', 'Mix batter; bake until golden; cool and serve.', 6, 3, 11, 35, 1, 5, 2, 'Advanced'),
('Hearty Beef Tacos Delight', 'Season chicken; grill until golden; serve with side salad.', 4, 1, 22, 22, 4, 4, 2, 'Advanced'),
('Simple Shrimp Alfredo with Basil', 'Chop vegetables; stir fry with tofu; drizzle with soy sauce.', 3, 1, 12, 16, 4, 4, 4, 'Advanced'),
('Hearty Vegetable Stir Fry Special', 'Chop vegetables; stir fry with tofu; drizzle with soy sauce.', 2, 2, 18, 32, 2, 5, 1, 'Intermediate'),
('Savory Chicken Curry with Rice', 'Toast bread; layer with avocado and egg; season and serve.', 5, 1, 13, 54, 1, 1, 3, 'Easy'),
('Gluten-Free Shrimp Alfredo with Basil', 'Simmer tomatoes; blend into sauce; pour over pasta.', 10, 3, 9, 22, 3, 4, 3, 'Advanced'),
('Simple Beef Tacos Medley', 'Cook shrimp in garlic butter; add cream; toss with pasta.', 1, 2, 14, 27, 4, 3, 3, 'Intermediate'),
('Vegan Vegetable Stir Fry and Chickpeas', 'Simmer tomatoes; blend into sauce; pour over pasta.', 6, 2, 30, 58, 1, 1, 3, 'Intermediate'),
('Crunchy Grilled Chicken Salad Medley', 'Cook rice; stir in beans and herbs; serve with avocado.', 9, 5, 30, 43, 7, 1, 3, 'Advanced'),
('Gluten-Free Tofu Stir Fry Wraps', 'Cook rice; stir in beans and herbs; serve with avocado.', 3, 5, 21, 50, 7, 3, 2, 'Advanced'),
('Smoky Tofu Stir Fry Medley', 'Mix batter; bake until golden; cool and serve.', 10, 3, 14, 60, 3, 2, 5, 'Intermediate'),
('Savory Shrimp Alfredo with Cheese', 'Toast bread; layer with avocado and egg; season and serve.', 3, 4, 12, 60, 5, 4, 3, 'Advanced'),
('Zesty Pasta Primavera Toppers', 'Mix batter; bake until golden; cool and serve.', 7, 2, 22, 27, 1, 4, 5, 'Easy'),
('Crunchy Beef Tacos Skillet', 'Simmer tomatoes; blend into sauce; pour over pasta.', 5, 3, 12, 19, 7, 2, 5, 'Easy'),
('Simple Shrimp Alfredo Fiesta', 'Mix batter; bake until golden; cool and serve.', 7, 4, 12, 12, 7, 4, 4, 'Easy'),
('Low-Carb Chicken Curry Special', 'Cook rice; stir in beans and herbs; serve with avocado.', 8, 5, 13, 55, 7, 2, 1, 'Intermediate'),
('Creamy Beef Tacos with Cheese', 'Season chicken; grill until golden; serve with side salad.', 2, 3, 20, 33, 2, 2, 4, 'Intermediate'),
('Smoky Chicken Curry Delight', 'Marinate beef; pan-sear; serve with mashed potatoes.', 7, 1, 8, 52, 4, 2, 3, 'Intermediate'),
('Tangy Grilled Chicken Salad Fusion', 'Boil pasta; sauté vegetables; mix with sauce and serve.', 10, 1, 13, 46, 4, 2, 4, 'Intermediate'),
('Low-Carb Beef Tacos Fiesta', 'Chop vegetables; stir fry with tofu; drizzle with soy sauce.', 1, 5, 13, 17, 2, 4, 1, 'Intermediate'),
('Simple Chicken Curry Fiesta', 'Boil potatoes; mash with butter and cream; season to taste.', 7, 5, 27, 27, 5, 5, 4, 'Easy'),
('Smoky Beef Tacos Wraps', 'Boil pasta; sauté vegetables; mix with sauce and serve.', 2, 1, 11, 12, 1, 2, 3, 'Advanced'),
('Classic Pasta Primavera Toppers', 'Cook lentils; add spices and simmer; serve hot with bread.', 9, 4, 9, 38, 5, 2, 1, 'Intermediate'),
('Fresh Grilled Chicken Salad Wraps', 'Toast bread; layer with avocado and egg; season and serve.', 3, 5, 16, 32, 5, 2, 5, 'Intermediate'),
('Zesty Quinoa Bowl with Basil', 'Grill salmon; glaze with teriyaki; serve with steamed rice.', 4, 1, 15, 18, 2, 5, 3, 'Easy'),
('Classic Tofu Stir Fry Toppers', 'Mix batter; bake until golden; cool and serve.', 1, 5, 29, 54, 6, 3, 2, 'Easy'),
('Hearty Vegetable Stir Fry with Cheese', 'Whisk eggs; cook in nonstick pan; sprinkle with cheese.', 6, 2, 8, 59, 5, 4, 4, 'Advanced'),
('Classic Spaghetti Bolognese Medley', 'Simmer tomatoes; blend into sauce; pour over pasta.', 3, 3, 12, 20, 7, 1, 2, 'Advanced'),
('Crunchy Tofu Stir Fry with Basil', 'Toast bread; layer with avocado and egg; season and serve.', 4, 5, 28, 26, 6, 1, 4, 'Advanced'),
('Gluten-Free Tofu Stir Fry Skillet', 'Season chicken; grill until golden; serve with side salad.', 10, 3, 25, 19, 1, 2, 5, 'Advanced'),
('Creamy Beef Tacos with Rice', 'Boil potatoes; mash with butter and cream; season to taste.', 3, 1, 19, 48, 6, 3, 5, 'Easy'),
('Low-Carb Shrimp Alfredo Wraps', 'Roast vegetables; toss with quinoa and feta; drizzle dressing.', 8, 3, 15, 12, 6, 4, 1, 'Easy'),
('Smoky Quinoa Bowl Toppers', 'Cook lentils; add spices and simmer; serve hot with bread.', 10, 3, 9, 14, 3, 5, 1, 'Intermediate'),
('Hearty Vegetable Stir Fry with Rice', 'Cook rice; stir in beans and herbs; serve with avocado.', 10, 2, 21, 13, 4, 1, 2, 'Easy'),
('Creamy Spaghetti Bolognese Medley', 'Whisk eggs; cook in nonstick pan; sprinkle with cheese.', 1, 2, 23, 40, 3, 5, 1, 'Easy'),
('Low-Carb Quinoa Bowl Toppers', 'Toast bread; layer with avocado and egg; season and serve.', 9, 4, 8, 58, 3, 4, 1, 'Easy'),
('Gluten-Free Grilled Chicken Salad with Cheese', 'Season chicken; grill until golden; serve with side salad.', 4, 2, 8, 57, 6, 3, 5, 'Intermediate'),
('Simple Shrimp Alfredo Wraps', 'Simmer tomatoes; blend into sauce; pour over pasta.', 9, 3, 27, 55, 4, 2, 5, 'Easy'),
('Smoky Beef Tacos with Cheese', 'Toast bread; layer with avocado and egg; season and serve.', 9, 1, 11, 21, 7, 4, 3, 'Advanced'),
('Gluten-Free Tofu Stir Fry Fusion', 'Sauté onions; add ground beef and sauce; stuff into peppers.', 2, 1, 13, 12, 3, 4, 3, 'Advanced'),
('Hearty Beef Tacos with Cheese', 'Mix batter; bake until golden; cool and serve.', 8, 3, 21, 14, 1, 4, 1, 'Easy'),
('Crunchy Tofu Stir Fry Wraps', 'Mix batter; bake until golden; cool and serve.', 7, 1, 30, 44, 6, 5, 5, 'Intermediate'),
('Crunchy Quinoa Bowl Fusion', 'Cook rice; stir in beans and herbs; serve with avocado.', 9, 2, 20, 43, 4, 4, 2, 'Intermediate'),
('Zesty Quinoa Bowl Delight', 'Mix batter; bake until golden; cool and serve.', 4, 1, 19, 30, 2, 1, 5, 'Advanced'),
('Spicy Shrimp Alfredo Wraps', 'Cook lentils; add spices and simmer; serve hot with bread.', 6, 5, 11, 48, 1, 3, 1, 'Easy'),
('Spicy Tofu Stir Fry Fusion', 'Grill salmon; glaze with teriyaki; serve with steamed rice.', 6, 5, 14, 41, 3, 2, 4, 'Intermediate'),
('Smoky Lentil Soup with Rice', 'Toast bread; layer with avocado and egg; season and serve.', 8, 4, 23, 44, 6, 4, 4, 'Advanced'),
('Simple Chicken Curry Medley', 'Cook shrimp in garlic butter; add cream; toss with pasta.', 2, 4, 14, 42, 4, 2, 5, 'Easy'),
('Savory Grilled Chicken Salad Bake', 'Toast bread; layer with avocado and egg; season and serve.', 5, 5, 29, 26, 5, 4, 3, 'Advanced'),
('Tangy Spaghetti Bolognese and Chickpeas', 'Toast bread; layer with avocado and egg; season and serve.', 8, 4, 22, 48, 6, 4, 1, 'Intermediate'),
('Savory Spaghetti Bolognese Wraps', 'Roast vegetables; toss with quinoa and feta; drizzle dressing.', 1, 5, 8, 32, 8, 3, 2, 'Advanced'),
('Fresh Shrimp Alfredo with Rice', 'Whisk eggs; cook in nonstick pan; sprinkle with cheese.', 3, 1, 26, 38, 8, 5, 1, 'Intermediate'),
('Simple Spaghetti Bolognese Wraps', 'Mix batter; bake until golden; cool and serve.', 2, 4, 10, 29, 3, 5, 1, 'Advanced'),
('Creamy Vegetable Stir Fry with Rice', 'Sauté onions; add ground beef and sauce; stuff into peppers.', 10, 1, 11, 11, 5, 2, 3, 'Intermediate'),
('Hearty Shrimp Alfredo Surprise', 'Marinate beef; pan-sear; serve with mashed potatoes.', 10, 2, 22, 44, 8, 4, 2, 'Intermediate'),
('Creamy Quinoa Bowl Wraps', 'Mix batter; bake until golden; cool and serve.', 6, 2, 19, 49, 3, 3, 5, 'Advanced'),
('Smoky Tofu Stir Fry Bake', 'Whisk eggs; cook in nonstick pan; sprinkle with cheese.', 5, 1, 29, 54, 1, 3, 4, 'Intermediate'),
('Simple Tofu Stir Fry Delight', 'Simmer tomatoes; blend into sauce; pour over pasta.', 5, 4, 16, 38, 7, 3, 3, 'Advanced'),
('Smoky Shrimp Alfredo Wraps', 'Season chicken; grill until golden; serve with side salad.', 10, 5, 18, 52, 3, 5, 4, 'Intermediate'),
('Classic Quinoa Bowl with Rice', 'Simmer tomatoes; blend into sauce; pour over pasta.', 1, 4, 7, 12, 8, 5, 5, 'Intermediate'),
('Gluten-Free Quinoa Bowl Special', 'Sauté onions; add ground beef and sauce; stuff into peppers.', 8, 3, 21, 37, 4, 1, 1, 'Easy'),
('Creamy Shrimp Alfredo Bake', 'Grill salmon; glaze with teriyaki; serve with steamed rice.', 3, 5, 21, 15, 8, 1, 3, 'Intermediate'),
('Classic Grilled Chicken Salad Special', 'Chop vegetables; stir fry with tofu; drizzle with soy sauce.', 6, 2, 8, 47, 7, 1, 5, 'Advanced'),
('Savory Spaghetti Bolognese Surprise', 'Cook rice; stir in beans and herbs; serve with avocado.', 3, 3, 27, 42, 2, 1, 2, 'Advanced'),
('Hearty Spaghetti Bolognese Toppers', 'Simmer tomatoes; blend into sauce; pour over pasta.', 1, 4, 19, 19, 3, 1, 5, 'Easy'),
('Tangy Grilled Chicken Salad with Basil', 'Grill salmon; glaze with teriyaki; serve with steamed rice.', 8, 5, 28, 40, 1, 1, 3, 'Advanced'),
('Savory Quinoa Bowl Fiesta', 'Season chicken; grill until golden; serve with side salad.', 3, 4, 17, 31, 7, 4, 2, 'Advanced'),
('Simple Quinoa Bowl with Rice', 'Chop vegetables; stir fry with tofu; drizzle with soy sauce.', 1, 2, 21, 40, 6, 3, 5, 'Advanced'),
('Classic Vegetable Stir Fry Wraps', 'Cook rice; stir in beans and herbs; serve with avocado.', 7, 1, 26, 15, 8, 5, 4, 'Intermediate'),
('Hearty Pasta Primavera Delight', 'Roast vegetables; toss with quinoa and feta; drizzle dressing.', 9, 5, 24, 50, 1, 2, 2, 'Advanced'),
('Fresh Shrimp Alfredo Wraps', 'Boil pasta; sauté vegetables; mix with sauce and serve.', 10, 1, 10, 18, 8, 2, 5, 'Easy'),
('Low-Carb Pasta Primavera Fiesta', 'Toast bread; layer with avocado and egg; season and serve.', 6, 3, 23, 15, 1, 3, 5, 'Intermediate'),
('Spicy Quinoa Bowl Fusion', 'Chop vegetables; stir fry with tofu; drizzle with soy sauce.', 4, 4, 28, 53, 8, 4, 5, 'Easy'),
('Creamy Beef Tacos Medley', 'Season chicken; grill until golden; serve with side salad.', 5, 2, 25, 11, 5, 4, 3, 'Easy'),
('Fresh Lentil Soup with Cheese', 'Whisk eggs; cook in nonstick pan; sprinkle with cheese.', 9, 4, 14, 59, 3, 3, 1, 'Advanced'),
('Fresh Quinoa Bowl Fusion', 'Cook lentils; add spices and simmer; serve hot with bread.', 10, 5, 13, 15, 8, 5, 2, 'Intermediate'),
('Creamy Spaghetti Bolognese and Chickpeas', 'Roast vegetables; toss with quinoa and feta; drizzle dressing.', 8, 1, 23, 19, 4, 2, 2, 'Easy'),
('Classic Beef Tacos and Chickpeas', 'Season chicken; grill until golden; serve with side salad.', 6, 1, 15, 13, 6, 4, 5, 'Advanced'),
('Gluten-Free Lentil Soup Delight', 'Cook rice; stir in beans and herbs; serve with avocado.', 9, 3, 9, 44, 6, 2, 5, 'Advanced'),
('Low-Carb Spaghetti Bolognese with Basil', 'Simmer tomatoes; blend into sauce; pour over pasta.', 1, 2, 29, 42, 3, 5, 4, 'Intermediate'),
('Gluten-Free Beef Tacos with Basil', 'Grill salmon; glaze with teriyaki; serve with steamed rice.', 1, 3, 16, 38, 6, 1, 4, 'Intermediate'),
('Spicy Vegetable Stir Fry Medley', 'Whisk eggs; cook in nonstick pan; sprinkle with cheese.', 10, 3, 22, 13, 6, 2, 2, 'Intermediate'),
('Crunchy Beef Tacos Special', 'Cook lentils; add spices and simmer; serve hot with bread.', 6, 4, 21, 56, 1, 1, 4, 'Easy'),
('Smoky Beef Tacos with Basil', 'Mix batter; bake until golden; cool and serve.', 7, 5, 18, 40, 6, 5, 1, 'Intermediate'),
('Creamy Chicken Curry with Basil', 'Chop vegetables; stir fry with tofu; drizzle with soy sauce.', 9, 2, 11, 34, 5, 2, 5, 'Advanced'),
('Savory Tofu Stir Fry Fiesta', 'Marinate beef; pan-sear; serve with mashed potatoes.', 3, 4, 23, 14, 3, 4, 1, 'Intermediate'),
('Smoky Quinoa Bowl with Cheese', 'Toast bread; layer with avocado and egg; season and serve.', 7, 4, 9, 53, 3, 4, 4, 'Advanced'),
('Spicy Lentil Soup Toppers', 'Toast bread; layer with avocado and egg; season and serve.', 7, 3, 13, 45, 2, 4, 5, 'Intermediate'),
('Simple Pasta Primavera with Rice', 'Cook shrimp in garlic butter; add cream; toss with pasta.', 7, 4, 17, 60, 2, 2, 1, 'Easy'),
('Crunchy Quinoa Bowl with Cheese', 'Simmer tomatoes; blend into sauce; pour over pasta.', 5, 5, 17, 14, 5, 3, 2, 'Advanced'),
('Fresh Vegetable Stir Fry Fiesta', 'Season chicken; grill until golden; serve with side salad.', 4, 4, 13, 50, 2, 2, 4, 'Easy'),
('Gluten-Free Tofu Stir Fry Bake', 'Chop vegetables; stir fry with tofu; drizzle with soy sauce.', 8, 4, 23, 38, 5, 2, 1, 'Advanced'),
('Low-Carb Chicken Curry with Cheese', 'Roast vegetables; toss with quinoa and feta; drizzle dressing.', 6, 5, 23, 53, 7, 1, 1, 'Intermediate'),
('Simple Pasta Primavera Fusion', 'Cook shrimp in garlic butter; add cream; toss with pasta.', 4, 2, 23, 52, 4, 2, 2, 'Intermediate'),
('Creamy Grilled Chicken Salad Surprise', 'Grill salmon; glaze with teriyaki; serve with steamed rice.', 1, 2, 28, 26, 6, 5, 4, 'Easy'),
('Hearty Pasta Primavera and Chickpeas', 'Mix batter; bake until golden; cool and serve.', 7, 4, 6, 21, 5, 2, 3, 'Advanced'),
('Smoky Spaghetti Bolognese Medley', 'Cook rice; stir in beans and herbs; serve with avocado.', 3, 1, 29, 39, 7, 3, 5, 'Advanced'),
('Fresh Spaghetti Bolognese Medley', 'Whisk eggs; cook in nonstick pan; sprinkle with cheese.', 3, 3, 28, 57, 5, 4, 3, 'Advanced'),
('Low-Carb Vegetable Stir Fry Wraps', 'Mix batter; bake until golden; cool and serve.', 2, 4, 8, 40, 2, 5, 2, 'Intermediate'),
('Gluten-Free Beef Tacos Special', 'Sauté onions; add ground beef and sauce; stuff into peppers.', 1, 4, 23, 43, 7, 5, 4, 'Advanced'),
('Simple Shrimp Alfredo with Rice', 'Boil potatoes; mash with butter and cream; season to taste.', 10, 3, 10, 34, 2, 2, 3, 'Advanced'),
('Creamy Tofu Stir Fry Fiesta', 'Cook lentils; add spices and simmer; serve hot with bread.', 7, 2, 21, 20, 1, 4, 2, 'Easy'),
('Tangy Quinoa Bowl Special', 'Cook rice; stir in beans and herbs; serve with avocado.', 9, 1, 25, 17, 6, 2, 1, 'Advanced'),
('Fresh Grilled Chicken Salad Fusion', 'Cook shrimp in garlic butter; add cream; toss with pasta.', 7, 3, 14, 37, 1, 3, 4, 'Easy'),
('Crunchy Beef Tacos Fiesta', 'Boil potatoes; mash with butter and cream; season to taste.', 4, 4, 14, 51, 5, 4, 4, 'Advanced'),
('Fresh Chicken Curry Fiesta', 'Chop vegetables; stir fry with tofu; drizzle with soy sauce.', 2, 4, 23, 15, 3, 3, 1, 'Easy'),
('Spicy Shrimp Alfredo with Basil', 'Season chicken; grill until golden; serve with side salad.', 6, 2, 30, 52, 6, 1, 2, 'Easy'),
('Low-Carb Vegetable Stir Fry with Basil', 'Roast vegetables; toss with quinoa and feta; drizzle dressing.', 9, 5, 7, 24, 2, 1, 3, 'Easy'),
('Tangy Vegetable Stir Fry Skillet', 'Whisk eggs; cook in nonstick pan; sprinkle with cheese.', 5, 3, 14, 55, 1, 2, 5, 'Easy'),
('Simple Spaghetti Bolognese Medley', 'Cook lentils; add spices and simmer; serve hot with bread.', 7, 3, 27, 36, 2, 3, 5, 'Advanced'),
('Low-Carb Beef Tacos Special', 'Chop vegetables; stir fry with tofu; drizzle with soy sauce.', 5, 4, 16, 36, 3, 4, 2, 'Easy'),
('Hearty Grilled Chicken Salad with Cheese', 'Chop vegetables; stir fry with tofu; drizzle with soy sauce.', 2, 2, 22, 17, 6, 3, 5, 'Easy'),
('Tangy Tofu Stir Fry Medley', 'Sauté onions; add ground beef and sauce; stuff into peppers.', 8, 4, 28, 34, 2, 2, 1, 'Intermediate'),
('Smoky Tofu Stir Fry with Basil', 'Season chicken; grill until golden; serve with side salad.', 9, 4, 22, 59, 4, 5, 3, 'Intermediate'),
('Vegan Tofu Stir Fry Bake', 'Boil potatoes; mash with butter and cream; season to taste.', 8, 4, 11, 29, 4, 5, 5, 'Advanced'),
('Simple Pasta Primavera Delight', 'Cook shrimp in garlic butter; add cream; toss with pasta.', 3, 2, 24, 47, 5, 1, 3, 'Easy'),
('Fresh Chicken Curry Delight', 'Roast vegetables; toss with quinoa and feta; drizzle dressing.', 2, 3, 17, 52, 1, 4, 1, 'Easy'),
('Simple Grilled Chicken Salad with Rice', 'Grill salmon; glaze with teriyaki; serve with steamed rice.', 2, 4, 6, 53, 4, 3, 2, 'Intermediate'),
('Creamy Spaghetti Bolognese Skillet', 'Cook shrimp in garlic butter; add cream; toss with pasta.', 2, 1, 12, 26, 8, 1, 5, 'Intermediate'),
('Simple Lentil Soup with Basil', 'Boil pasta; sauté vegetables; mix with sauce and serve.', 8, 4, 25, 49, 4, 2, 1, 'Intermediate'),
('Spicy Shrimp Alfredo Skillet', 'Chop vegetables; stir fry with tofu; drizzle with soy sauce.', 2, 5, 11, 22, 8, 3, 1, 'Advanced'),
('Hearty Tofu Stir Fry with Cheese', 'Roast vegetables; toss with quinoa and feta; drizzle dressing.', 8, 4, 30, 24, 2, 5, 5, 'Easy'),
('Low-Carb Lentil Soup Toppers', 'Simmer tomatoes; blend into sauce; pour over pasta.', 10, 5, 6, 40, 2, 4, 4, 'Advanced'),
('Tangy Tofu Stir Fry Fusion', 'Whisk eggs; cook in nonstick pan; sprinkle with cheese.', 4, 1, 16, 11, 2, 1, 4, 'Intermediate'),
('Smoky Vegetable Stir Fry Surprise', 'Whisk eggs; cook in nonstick pan; sprinkle with cheese.', 10, 2, 12, 27, 6, 3, 3, 'Intermediate'),
('Savory Spaghetti Bolognese Special', 'Marinate beef; pan-sear; serve with mashed potatoes.', 2, 4, 20, 44, 8, 1, 3, 'Easy'),
('Gluten-Free Quinoa Bowl Surprise', 'Boil pasta; sauté vegetables; mix with sauce and serve.', 1, 2, 8, 23, 3, 5, 1, 'Intermediate'),
('Low-Carb Lentil Soup with Basil', 'Boil pasta; sauté vegetables; mix with sauce and serve.', 8, 5, 16, 39, 1, 3, 5, 'Intermediate'),
('Smoky Tofu Stir Fry Fusion', 'Cook shrimp in garlic butter; add cream; toss with pasta.', 1, 4, 20, 49, 5, 3, 5, 'Easy'),
('Savory Chicken Curry with Basil', 'Marinate beef; pan-sear; serve with mashed potatoes.', 9, 4, 11, 22, 7, 5, 3, 'Easy'),
('Tangy Spaghetti Bolognese Medley', 'Cook rice; stir in beans and herbs; serve with avocado.', 1, 3, 26, 21, 8, 4, 2, 'Advanced'),
('Low-Carb Quinoa Bowl Wraps', 'Season chicken; grill until golden; serve with side salad.', 4, 2, 16, 50, 2, 4, 3, 'Advanced'),
('Crunchy Shrimp Alfredo Surprise', 'Cook rice; stir in beans and herbs; serve with avocado.', 6, 5, 28, 31, 7, 4, 2, 'Easy'),
('Vegan Vegetable Stir Fry Special', 'Chop vegetables; stir fry with tofu; drizzle with soy sauce.', 6, 5, 17, 34, 2, 5, 1, 'Easy'),
('Zesty Spaghetti Bolognese with Cheese', 'Sauté onions; add ground beef and sauce; stuff into peppers.', 8, 2, 29, 17, 5, 3, 5, 'Intermediate'),
('Creamy Shrimp Alfredo with Basil', 'Cook shrimp in garlic butter; add cream; toss with pasta.', 5, 4, 16, 50, 7, 5, 4, 'Advanced'),
('Crunchy Spaghetti Bolognese Special', 'Sauté onions; add ground beef and sauce; stuff into peppers.', 3, 2, 15, 43, 1, 2, 3, 'Intermediate'),
('Gluten-Free Spaghetti Bolognese Toppers', 'Simmer tomatoes; blend into sauce; pour over pasta.', 5, 1, 27, 18, 7, 4, 3, 'Intermediate'),
('Zesty Spaghetti Bolognese Fiesta', 'Roast vegetables; toss with quinoa and feta; drizzle dressing.', 6, 3, 20, 58, 7, 2, 1, 'Easy'),
('Tangy Shrimp Alfredo with Rice', 'Toast bread; layer with avocado and egg; season and serve.', 6, 3, 27, 45, 7, 2, 3, 'Easy'),
('Hearty Shrimp Alfredo Wraps', 'Chop vegetables; stir fry with tofu; drizzle with soy sauce.', 3, 2, 27, 44, 2, 5, 4, 'Easy'),
('Gluten-Free Tofu Stir Fry Special', 'Roast vegetables; toss with quinoa and feta; drizzle dressing.', 10, 1, 14, 44, 3, 1, 1, 'Intermediate'),
('Savory Shrimp Alfredo Fiesta', 'Boil potatoes; mash with butter and cream; season to taste.', 2, 3, 13, 39, 6, 5, 4, 'Intermediate'),
('Spicy Beef Tacos Medley', 'Boil potatoes; mash with butter and cream; season to taste.', 2, 4, 6, 46, 6, 4, 3, 'Advanced'),
('Zesty Shrimp Alfredo Special', 'Whisk eggs; cook in nonstick pan; sprinkle with cheese.', 10, 1, 6, 51, 4, 3, 2, 'Advanced'),
('Crunchy Grilled Chicken Salad Delight', 'Cook lentils; add spices and simmer; serve hot with bread.', 2, 4, 13, 49, 8, 1, 3, 'Easy'),
('Classic Chicken Curry Surprise', 'Whisk eggs; cook in nonstick pan; sprinkle with cheese.', 6, 5, 16, 18, 2, 3, 3, 'Advanced'),
('Smoky Vegetable Stir Fry Bake', 'Simmer tomatoes; blend into sauce; pour over pasta.', 3, 5, 18, 59, 5, 3, 2, 'Advanced'),
('Smoky Tofu Stir Fry Fiesta', 'Boil pasta; sauté vegetables; mix with sauce and serve.', 1, 4, 28, 29, 7, 4, 5, 'Advanced'),
('Vegan Tofu Stir Fry with Basil', 'Roast vegetables; toss with quinoa and feta; drizzle dressing.', 5, 1, 15, 59, 4, 3, 2, 'Intermediate'),
('Spicy Lentil Soup Medley', 'Chop vegetables; stir fry with tofu; drizzle with soy sauce.', 3, 2, 30, 39, 6, 3, 1, 'Advanced'),
('Spicy Spaghetti Bolognese Surprise', 'Boil pasta; sauté vegetables; mix with sauce and serve.', 10, 1, 20, 44, 6, 3, 4, 'Easy'),
('Low-Carb Quinoa Bowl Delight', 'Sauté onions; add ground beef and sauce; stuff into peppers.', 6, 3, 8, 23, 3, 2, 3, 'Intermediate'),
('Savory Chicken Curry with Cheese', 'Mix batter; bake until golden; cool and serve.', 4, 1, 16, 35, 2, 3, 4, 'Intermediate'),
('Creamy Quinoa Bowl and Chickpeas', 'Cook shrimp in garlic butter; add cream; toss with pasta.', 9, 2, 23, 20, 5, 4, 2, 'Easy'),
('Zesty Grilled Chicken Salad and Chickpeas', 'Mix batter; bake until golden; cool and serve.', 6, 2, 30, 26, 1, 4, 5, 'Easy'),
('Low-Carb Spaghetti Bolognese Surprise', 'Whisk eggs; cook in nonstick pan; sprinkle with cheese.', 7, 5, 6, 48, 4, 5, 5, 'Easy'),
('Classic Pasta Primavera Skillet', 'Grill salmon; glaze with teriyaki; serve with steamed rice.', 6, 3, 24, 43, 4, 1, 4, 'Intermediate'),
('Low-Carb Pasta Primavera and Chickpeas', 'Boil pasta; sauté vegetables; mix with sauce and serve.', 2, 4, 24, 10, 8, 2, 3, 'Advanced'),
('Classic Grilled Chicken Salad Fiesta', 'Marinate beef; pan-sear; serve with mashed potatoes.', 4, 4, 14, 59, 4, 1, 3, 'Intermediate'),
('Classic Quinoa Bowl Special', 'Sauté onions; add ground beef and sauce; stuff into peppers.', 9, 3, 27, 11, 8, 2, 5, 'Advanced'),
('Tangy Vegetable Stir Fry Toppers', 'Cook rice; stir in beans and herbs; serve with avocado.', 9, 2, 15, 18, 7, 1, 3, 'Intermediate'),
('Spicy Spaghetti Bolognese Delight', 'Cook rice; stir in beans and herbs; serve with avocado.', 1, 1, 27, 38, 5, 4, 3, 'Intermediate'),
('Hearty Grilled Chicken Salad Fusion', 'Roast vegetables; toss with quinoa and feta; drizzle dressing.', 6, 5, 22, 18, 7, 5, 5, 'Advanced'),
('Savory Vegetable Stir Fry Medley', 'Roast vegetables; toss with quinoa and feta; drizzle dressing.', 9, 4, 27, 51, 2, 2, 3, 'Intermediate'),
('Crunchy Quinoa Bowl Fiesta', 'Cook shrimp in garlic butter; add cream; toss with pasta.', 9, 1, 13, 36, 6, 2, 3, 'Advanced'),
('Savory Vegetable Stir Fry Wraps', 'Cook lentils; add spices and simmer; serve hot with bread.', 1, 2, 5, 40, 7, 4, 1, 'Easy'),
('Tangy Pasta Primavera Special', 'Cook lentils; add spices and simmer; serve hot with bread.', 9, 1, 22, 42, 5, 1, 1, 'Advanced'),
('Spicy Spaghetti Bolognese Skillet', 'Boil potatoes; mash with butter and cream; season to taste.', 8, 2, 20, 23, 8, 2, 2, 'Intermediate'),
('Simple Vegetable Stir Fry Skillet', 'Sauté onions; add ground beef and sauce; stuff into peppers.', 1, 3, 23, 14, 1, 4, 3, 'Advanced'),
('Vegan Beef Tacos Special', 'Roast vegetables; toss with quinoa and feta; drizzle dressing.', 10, 1, 29, 44, 7, 5, 5, 'Easy'),
('Classic Spaghetti Bolognese with Cheese', 'Cook shrimp in garlic butter; add cream; toss with pasta.', 10, 5, 29, 57, 5, 3, 5, 'Advanced'),
('Zesty Chicken Curry Medley', 'Season chicken; grill until golden; serve with side salad.', 3, 1, 22, 45, 2, 1, 3, 'Easy'),
('Low-Carb Spaghetti Bolognese with Rice', 'Roast vegetables; toss with quinoa and feta; drizzle dressing.', 2, 4, 28, 23, 5, 1, 2, 'Intermediate'),
('Smoky Pasta Primavera Delight', 'Cook shrimp in garlic butter; add cream; toss with pasta.', 4, 4, 8, 40, 2, 2, 2, 'Easy'),
('Simple Lentil Soup Skillet', 'Whisk eggs; cook in nonstick pan; sprinkle with cheese.', 3, 5, 29, 24, 6, 1, 4, 'Intermediate'),
('Creamy Beef Tacos Fusion', 'Mix batter; bake until golden; cool and serve.', 5, 4, 9, 32, 8, 4, 5, 'Easy'),
('Tangy Spaghetti Bolognese Skillet', 'Whisk eggs; cook in nonstick pan; sprinkle with cheese.', 8, 3, 27, 52, 6, 2, 4, 'Advanced'),
('Low-Carb Shrimp Alfredo Fusion', 'Cook shrimp in garlic butter; add cream; toss with pasta.', 6, 3, 23, 57, 2, 3, 2, 'Advanced'),
('Spicy Shrimp Alfredo with Rice', 'Marinate beef; pan-sear; serve with mashed potatoes.', 3, 4, 9, 60, 6, 2, 3, 'Advanced'),
('Classic Vegetable Stir Fry Fusion', 'Cook shrimp in garlic butter; add cream; toss with pasta.', 1, 2, 28, 44, 2, 5, 4, 'Easy'),
('Gluten-Free Tofu Stir Fry Delight', 'Cook lentils; add spices and simmer; serve hot with bread.', 2, 1, 30, 36, 4, 3, 5, 'Easy'),
('Crunchy Beef Tacos Medley', 'Season chicken; grill until golden; serve with side salad.', 5, 5, 17, 19, 4, 1, 2, 'Advanced'),
('Spicy Shrimp Alfredo Surprise', 'Cook shrimp in garlic butter; add cream; toss with pasta.', 7, 3, 22, 46, 6, 3, 5, 'Easy'),
('Spicy Grilled Chicken Salad and Chickpeas', 'Whisk eggs; cook in nonstick pan; sprinkle with cheese.', 9, 3, 12, 40, 2, 5, 4, 'Easy'),
('Tangy Quinoa Bowl Medley', 'Chop vegetables; stir fry with tofu; drizzle with soy sauce.', 5, 4, 30, 53, 6, 2, 5, 'Intermediate'),
('Simple Grilled Chicken Salad Skillet', 'Chop vegetables; stir fry with tofu; drizzle with soy sauce.', 4, 1, 9, 22, 2, 4, 4, 'Advanced'),
('Classic Quinoa Bowl Wraps', 'Grill salmon; glaze with teriyaki; serve with steamed rice.', 5, 2, 26, 11, 7, 5, 5, 'Intermediate'),
('Tangy Beef Tacos Fusion', 'Boil potatoes; mash with butter and cream; season to taste.', 5, 5, 22, 19, 8, 1, 3, 'Advanced'),
('Zesty Pasta Primavera Surprise', 'Cook rice; stir in beans and herbs; serve with avocado.', 9, 1, 12, 52, 1, 1, 3, 'Advanced'),
('Savory Vegetable Stir Fry with Rice', 'Season chicken; grill until golden; serve with side salad.', 2, 4, 18, 18, 7, 4, 2, 'Intermediate'),
('Savory Chicken Curry and Chickpeas', 'Cook lentils; add spices and simmer; serve hot with bread.', 6, 3, 28, 31, 3, 1, 4, 'Advanced'),
('Tangy Pasta Primavera Medley', 'Mix batter; bake until golden; cool and serve.', 6, 5, 8, 59, 7, 1, 2, 'Advanced'),
('Spicy Grilled Chicken Salad with Basil', 'Whisk eggs; cook in nonstick pan; sprinkle with cheese.', 4, 5, 19, 35, 4, 2, 1, 'Easy'),
('Simple Chicken Curry and Chickpeas', 'Roast vegetables; toss with quinoa and feta; drizzle dressing.', 3, 5, 17, 22, 8, 3, 1, 'Intermediate'),
('Savory Beef Tacos Fiesta', 'Marinate beef; pan-sear; serve with mashed potatoes.', 7, 3, 13, 47, 1, 4, 4, 'Intermediate'),
('Fresh Shrimp Alfredo Surprise', 'Cook shrimp in garlic butter; add cream; toss with pasta.', 8, 1, 5, 19, 3, 5, 1, 'Easy'),
('Gluten-Free Pasta Primavera Fusion', 'Cook shrimp in garlic butter; add cream; toss with pasta.', 5, 5, 11, 57, 2, 3, 1, 'Easy'),
('Gluten-Free Lentil Soup Special', 'Whisk eggs; cook in nonstick pan; sprinkle with cheese.', 3, 4, 18, 52, 5, 5, 5, 'Advanced'),
('Smoky Beef Tacos Medley', 'Season chicken; grill until golden; serve with side salad.', 5, 5, 25, 27, 8, 2, 3, 'Intermediate'),
('Smoky Vegetable Stir Fry with Basil', 'Boil pasta; sauté vegetables; mix with sauce and serve.', 3, 3, 10, 41, 6, 3, 1, 'Easy'),
('Gluten-Free Grilled Chicken Salad with Basil', 'Simmer tomatoes; blend into sauce; pour over pasta.', 4, 4, 17, 19, 3, 2, 1, 'Advanced'),
('Smoky Vegetable Stir Fry Delight', 'Whisk eggs; cook in nonstick pan; sprinkle with cheese.', 8, 4, 18, 30, 3, 5, 3, 'Advanced'),
('Smoky Quinoa Bowl Delight', 'Toast bread; layer with avocado and egg; season and serve.', 10, 4, 6, 26, 5, 3, 1, 'Easy'),
('Low-Carb Vegetable Stir Fry Special', 'Season chicken; grill until golden; serve with side salad.', 7, 3, 13, 36, 5, 5, 4, 'Easy'),
('Simple Tofu Stir Fry Fusion', 'Chop vegetables; stir fry with tofu; drizzle with soy sauce.', 6, 5, 21, 11, 6, 3, 2, 'Easy'),
('Fresh Beef Tacos Skillet', 'Boil potatoes; mash with butter and cream; season to taste.', 3, 4, 24, 57, 8, 3, 4, 'Advanced'),
('Crunchy Pasta Primavera Toppers', 'Sauté onions; add ground beef and sauce; stuff into peppers.', 1, 2, 12, 45, 2, 3, 5, 'Easy'),
('Crunchy Quinoa Bowl Toppers', 'Whisk eggs; cook in nonstick pan; sprinkle with cheese.', 7, 1, 15, 18, 1, 2, 3, 'Easy'),
('Tangy Chicken Curry Wraps', 'Mix batter; bake until golden; cool and serve.', 8, 2, 22, 29, 3, 4, 3, 'Advanced'),
('Fresh Lentil Soup Delight', 'Grill salmon; glaze with teriyaki; serve with steamed rice.', 10, 5, 29, 14, 1, 3, 3, 'Intermediate'),
('Crunchy Pasta Primavera Medley', 'Boil potatoes; mash with butter and cream; season to taste.', 7, 3, 19, 37, 7, 3, 3, 'Intermediate'),
('Hearty Grilled Chicken Salad Surprise', 'Chop vegetables; stir fry with tofu; drizzle with soy sauce.', 1, 4, 23, 18, 7, 2, 4, 'Advanced'),
('Zesty Spaghetti Bolognese Bake', 'Whisk eggs; cook in nonstick pan; sprinkle with cheese.', 6, 2, 27, 45, 7, 1, 2, 'Intermediate'),
('Crunchy Grilled Chicken Salad Surprise', 'Mix batter; bake until golden; cool and serve.', 2, 4, 13, 45, 2, 1, 3, 'Intermediate');