INSERT INTO category (categoryName, categoryImageUrl) VALUES 
('Breakfast', '/images/categories/breakfast-60x60.png'),
('Lunch', '/images/categories/lunch-60x60.png'),
('Dinner', '/images/categories/dinner-60x60.png'),
('Desserts', '/images/categories/desserts-60x60.png');

-- Insert common diet types
INSERT INTO diet (dietName, dietDescription) VALUES
('Vegetarian', 'No meat, fish, or poultry'),
('Vegan', 'No animal products'),
('Gluten-Free', 'No gluten-containing ingredients'),
('Keto', 'Low-carb, high-fat diet'),
('Paleo', 'Based on foods presumed eaten during the Paleolithic era'),
('Pescatarian', 'Vegetarian diet that includes fish'),
('Dairy-Free', 'No dairy products'),
('Low-Carb', 'Reduced carbohydrate intake'),
('None', 'No specific dietary restrictions');

-- Insert cuisine types
INSERT INTO cuisine (cuisineName, cuisineDescription) VALUES 
('Italian', 'Traditional Italian dishes including pasta, pizza, and Mediterranean flavors'),
('Chinese', 'Various regional Chinese cuisines featuring stir-fries, noodles, and rice dishes'),
('Mexican', 'Traditional Mexican dishes with tortillas, beans, and diverse spices'),
('Indian', 'Rich and diverse Indian cuisine with curries, tandoor dishes, and flatbreads'),
('Japanese', 'Japanese cuisine featuring sushi, noodles, and traditional dishes'),
('Thai', 'Thai dishes with sweet, sour, and spicy flavors'),
('Mediterranean', 'Healthy Mediterranean diet with olive oil, fresh vegetables, and seafood'),
('American', 'Classic American comfort food and regional specialties'),
('French', 'Elegant French cuisine with rich sauces and sophisticated techniques'),
('Korean', 'Korean dishes featuring kimchi, barbecue, and rice-based meals'),
('Vietnamese', 'Fresh Vietnamese cuisine with herbs and light preparations'),
('Middle Eastern', 'Middle Eastern fare with kebabs, hummus, and aromatic spices'),
('Greek', 'Traditional Greek dishes with olives, feta, and Mediterranean herbs'),
('Spanish', 'Spanish cuisine featuring paella, tapas, and seafood dishes');

-- Insert into user
INSERT INTO user(userId, username, password, firstName, lastName, email) VALUES
(1, 'ahhchu', '$2b$12$jGfBiC88wECW91Q.OkvGl.cT2oSxsm0D.W7GTasvTwqya6qUaor3G', 'Catherine', 'Chu', 'user1@example.com'),
(2, 'khushiB', '$2b$12$yHBmnTxw6bjsFVF9YW6mTujY2U44O/5b4nXDraToFQdXzxUURJNSm', 'Khushi', 'Bhatamrekar', 'user2@example.com'),
(3, 'user3', '$2b$12$fQCY2rkveHZl.nSFR9KWBeOjwUQuJCriDT9D7qpVf0XhNSMyOVJSS', 'Christian', 'Rivas', 'user3@example.com'),
(4, 'user4', '$2b$12$VeGV04H0X92gziyEJ9QSUOVWzjwn0bH/rBqbJeVN.jU.ZhaeUlolO', 'Jeremy', 'Hernandez', 'user4@example.com'),
(5, 'user5', '$2b$12$0Ea.pGMJQbdScW00DM26g.KSGyuA6oKiVvsDJ2X7IRk6rTYDiI9Uq', 'Alexandra', 'Marsh', 'user5@example.com'),
(6, 'user6', '$2b$12$pPYpqKSuFTpxNweuXHn95ueLAMoCn9FuwbD64MGTVtMqvLKNm3u3O', 'Lindsey', 'Daniels', 'user6@example.com'),
(7, 'user7', '$2b$12$MGmfqMjL0P/mBEDDckwyWu3vBzdTn1f25KC1PGxEBEyVhXqgSmK.y', 'Hunter', 'Barton', 'user7@example.com'),
(8, 'user8', '$2b$12$rr6WeY6vK5uzkae.A6/Egejaw/zIULgqwiOSihTYjdpsT58S4jqYC', 'Alyssa', 'Brown', 'user8@example.com'),
(9, 'user9', '$2b$12$z2nxZbUN42Z/FgUo8VZlC.vlbq8Sf2owywjdi//5Ifah0M4B5pBKO', 'Yvonne', 'Pierce', 'user9@example.com'),
(10, 'user10', '$2b$12$G2xgnG6DMaYYdt1F.2mFE.v7urXeoZrm5E8Ln1fNRlWTUTK5o8COW', 'Julie', 'Wright', 'user10@example.com'),
(11, 'user11', '$2b$12$MZRK0nKLf4sxRVcYzxjl/OcrX4e1SrRdwDTZgpxKrHLgg5bHceCVi', 'Nancy', 'Bentley', 'user11@example.com');

imageUrl = 
-- Insert into recipe
INSERT INTO recipe (recipeName, description, userId, prep_time, cook_time, servings, categoryId, dietId, cookingLevel, cuisineId, imageUrl) VALUES
('Marry Me Shrimp Pasta', 'Cook pasta; sauté shrimp in garlic butter; add cream and parmesan; toss with pasta.', 1, 15, 20, 4, 4, 9, 'Intermediate', 1),
('Avocado Toast', 'Toast bread; smash avocado with lemon and salt; spread on toast; top with chili flakes.', 2, 5, 0, 1, 2, 1, 'Beginner', 8),
('Chicken Burrito Bowl', 'Grill chicken; cook rice; layer with beans, salsa, cheese, and lettuce in a bowl.', 3, 15, 20, 2, 3, 9, 'Intermediate', 3),
('Vegan Pancakes', 'Mix flour, baking powder, almond milk; cook pancakes until golden; serve with syrup.', 4, 10, 15, 2, 2, 2, 'Beginner', 8),
('Beef Stroganoff', 'Brown beef; cook onions and mushrooms; stir in sour cream; serve over noodles.', 5, 20, 30, 4, 4, 9, 'Intermediate', 9),
('Tofu Stir Fry', 'Sauté tofu cubes; add mixed veggies; stir in soy sauce and garlic; cook until tender.', 6, 15, 15, 3, 3, 2, 'Beginner', 2),
('Keto Egg Muffins', 'Whisk eggs with veggies and cheese; pour into muffin tins; bake until set.', 7, 10, 20, 4, 2, 4, 'Beginner', 8),
('Gluten-Free Brownies', 'Mix gluten-free flour, cocoa, sugar, and eggs; bake until fudgy; cool before slicing.', 8, 15, 25, 6, 5, 3, 'Intermediate', 8),
('Grilled Salmon with Veggies', 'Season salmon; grill with veggies until cooked; drizzle with lemon and olive oil.', 2, 10, 20, 2, 4, 7, 'Intermediate', 7),
('Kimchi Fried Rice', 'Sauté kimchi and rice; add soy sauce and sesame oil; top with fried egg.', 1, 10, 15, 2, 3, 9, 'Beginner', 10),
('Caprese Salad', 'Slice tomatoes and mozzarella; layer with basil; drizzle with balsamic and olive oil.', 1, 10, 0, 2, 3, 1, 'Beginner', 1),
('Vegan Buddha Bowl', 'Cook quinoa; roast chickpeas and veggies; serve with tahini dressing.', 2, 15, 25, 2, 3, 2, 'Beginner', 7),
('French Onion Soup', 'Caramelize onions; add broth; simmer; top with toasted bread and melted cheese.', 3, 20, 45, 4, 4, 9, 'Intermediate', 9),
('Pad Thai', 'Sauté tofu and shrimp; add rice noodles and sauce; top with peanuts and lime.', 4, 15, 20, 3, 4, 9, 'Intermediate', 6),
('Miso Soup', 'Heat dashi broth; stir in miso paste; add tofu and seaweed; serve hot.', 5, 5, 10, 2, 3, 1, 'Beginner', 5),
('Avocado Sushi Rolls', 'Lay rice and avocado on nori; roll tightly; slice and serve with soy sauce.', 6, 20, 0, 2, 3, 2, 'Intermediate', 5),
('Shakshuka', 'Sauté onions and peppers; add tomatoes and spices; crack in eggs; cook until set.', 7, 10, 20, 3, 2, 1, 'Intermediate', 12),
('Greek Salad', 'Chop cucumbers, tomatoes, onions; toss with olives, feta, and vinaigrette.', 8, 10, 0, 2, 3, 1, 'Beginner', 13),
('BBQ Pulled Pork', 'Slow cook pork with BBQ sauce; shred and serve on buns.', 9, 15, 480, 6, 4, 9, 'Intermediate', 8),
('Falafel Wraps', 'Blend chickpeas with herbs; shape balls; fry and stuff in pita with veggies.', 10, 20, 15, 4, 3, 1, 'Intermediate', 12),
('Vegetable Lasagna', 'Layer noodles with ricotta, spinach, and marinara; bake until bubbly.', 1, 30, 45, 6, 4, 1, 'Intermediate', 1),
('Egg Fried Rice', 'Scramble eggs; add rice and veggies; stir-fry with soy sauce.', 2, 10, 15, 3, 3, 9, 'Beginner', 2),
('Pancit Bihon', 'Sauté pork and veggies; add rice noodles and broth; cook until tender.', 3, 15, 20, 4, 3, 9, 'Intermediate', 2),
('Spinach & Feta Omelette', 'Whisk eggs; cook with spinach and feta; fold and serve.', 4, 5, 10, 1, 2, 1, 'Beginner', 8),
('Korean Bibimbap', 'Arrange rice with sautéed veggies, beef, and fried egg; serve with gochujang.', 5, 25, 20, 3, 3, 9, 'Intermediate', 10),
('Chicken Tikka Masala', 'Marinate chicken; grill and simmer in creamy tomato sauce.', 6, 30, 40, 4, 4, 9, 'Intermediate', 4),
('Gazpacho', 'Blend tomatoes, cucumbers, peppers; chill and serve cold.', 7, 15, 0, 2, 3, 1, 'Beginner', 14),
('Cauliflower Rice', 'Pulse cauliflower in processor; sauté lightly with olive oil.', 8, 10, 5, 2, 3, 4, 'Beginner', 8),
('Churros', 'Mix dough; pipe into hot oil; fry until golden; roll in cinnamon sugar.', 9, 15, 20, 4, 5, 9, 'Intermediate', 14),
('Turkey Meatballs', 'Mix turkey with herbs; roll into balls; bake until golden.', 10, 15, 25, 4, 4, 9, 'Beginner', 8),
('Sweet and Sour Chicken', 'Coat chicken in batter; fry; toss with pineapple and sweet-sour sauce.', 1, 20, 25, 3, 4, 9, 'Intermediate', 2),
('Ratatouille', 'Sauté eggplant, zucchini, and peppers; simmer in tomato sauce.', 2, 15, 35, 4, 4, 1, 'Intermediate', 9),
('Pesto Pasta', 'Boil pasta; blend basil, pine nuts, and parmesan; toss together.', 3, 10, 15, 2, 3, 1, 'Beginner', 1),
('Shrimp Tacos', 'Sauté shrimp with spices; serve in tortillas with slaw and lime.', 4, 15, 10, 3, 3, 6, 'Intermediate', 3),
('Eggplant Parmesan', 'Bread and fry eggplant; layer with sauce and cheese; bake.', 5, 25, 35, 4, 4, 1, 'Intermediate', 1),
('Mapo Tofu', 'Cook ground pork; add tofu and spicy sauce; simmer and serve.', 6, 10, 20, 3, 4, 9, 'Intermediate', 2),
('Thai Green Curry', 'Sauté curry paste; add coconut milk, chicken, and veggies; simmer.', 7, 15, 25, 4, 4, 9, 'Intermediate', 6),
('Tuna Nicoise Salad', 'Arrange greens with tuna, eggs, potatoes, and olives; drizzle vinaigrette.', 8, 20, 10, 2, 3, 6, 'Intermediate', 9),
('Stuffed Bell Peppers', 'Fill peppers with rice and beef; bake with tomato sauce.', 9, 20, 40, 4, 4, 9, 'Intermediate', 8),
('Kale Chips', 'Toss kale with oil and salt; bake until crisp.', 10, 5, 15, 2, 5, 1, 'Beginner', 8),
('Lentil Soup', 'Simmer lentils with carrots, celery, and spices until tender.', 1, 15, 40, 4, 3, 1, 'Beginner', 12),
('Beef Bulgogi', 'Marinate beef; grill or pan-fry; serve with rice.', 2, 30, 15, 3, 4, 9, 'Intermediate', 10),
('Fish and Chips', 'Batter and fry fish; serve with fries and tartar sauce.', 3, 20, 25, 3, 4, 9, 'Intermediate', 8),
('Chocolate Mousse', 'Whip cream; fold into melted chocolate; chill until set.', 4, 15, 0, 4, 5, 9, 'Intermediate', 9),
('Vietnamese Spring Rolls', 'Wrap shrimp, noodles, and herbs in rice paper; serve with dipping sauce.', 5, 20, 0, 3, 3, 6, 'Intermediate', 11),
('Butternut Squash Soup', 'Roast squash; blend with broth and cream; season.', 6, 15, 30, 4, 3, 1, 'Beginner', 8),
('Paneer Butter Masala', 'Cook paneer in creamy tomato sauce with spices.', 7, 15, 25, 3, 4, 1, 'Intermediate', 4),
('Croque Monsieur', 'Assemble ham and cheese sandwich; grill with béchamel sauce.', 8, 10, 15, 2, 3, 9, 'Intermediate', 9),
('Enchiladas', 'Roll chicken in tortillas; cover with sauce and cheese; bake.', 9, 20, 25, 4, 4, 9, 'Intermediate', 3),
('Tom Yum Soup', 'Simmer shrimp with lemongrass, lime, and chili in broth.', 10, 10, 20, 3, 3, 6, 'Intermediate', 6),
('Bruschetta', 'Toast bread; top with tomatoes, garlic, and basil.', 1, 10, 5, 2, 3, 1, 'Beginner', 1),
('Baked Ziti', 'Cook pasta; layer with ricotta, sauce, and mozzarella; bake.', 2, 15, 30, 4, 4, 1, 'Intermediate', 1),
('Cabbage Rolls', 'Fill cabbage leaves with rice and meat; simmer in tomato sauce.', 3, 30, 60, 4, 4, 9, 'Intermediate', 8),
('Japanese Curry', 'Brown meat and veggies; add curry roux and simmer.', 4, 20, 30, 4, 4, 9, 'Intermediate', 5),
('Roasted Veggie Medley', 'Toss mixed veggies with oil and herbs; roast until tender.', 5, 10, 25, 3, 3, 1, 'Beginner', 8),
('Pumpkin Pie', 'Mix pumpkin puree with spices; bake in pie crust.', 6, 20, 50, 6, 5, 9, 'Intermediate', 8),
('Lamb Kebabs', 'Skewer lamb chunks; grill until charred.', 7, 15, 15, 3, 4, 9, 'Intermediate', 12),
('Kimchi Stew', 'Simmer kimchi with pork, tofu, and broth.', 8, 10, 30, 3, 3, 9, 'Intermediate', 10),
('Spanish Omelette', 'Cook potatoes and onions; add eggs; fry until golden.', 9, 15, 20, 2, 2, 9, 'Intermediate', 14),
('Peach Cobbler', 'Layer peaches with batter; bake until golden.', 10, 15, 40, 4, 5, 9, 'Intermediate', 8),
('Chicken Caesar Salad', 'Toss lettuce with grilled chicken, croutons, and Caesar dressing.', 1, 10, 5, 2, 3, 9, 'Beginner', 8),
('Vegan Pancakes', 'Mix flour, almond milk, and baking powder; cook pancakes on griddle.', 2, 10, 15, 2, 2, 2, 'Beginner', 2),
('Margherita Pizza', 'Top dough with tomatoes, mozzarella, and basil; bake in oven.', 3, 20, 15, 2, 3, 1, 'Intermediate', 1),
('Crispy Chickpea Salad', 'Roast chickpeas; mix with greens, avocado, and tahini dressing.', 4, 10, 30, 2, 3, 2, 'Beginner', 7),
('Beef Stroganoff', 'Cook beef in sour cream sauce; serve over egg noodles.', 5, 15, 25, 4, 4, 9, 'Intermediate', 9),
('Vegetable Samosas', 'Stuff pastry with spiced potatoes and peas; deep fry until crispy.', 6, 20, 30, 6, 5, 1, 'Intermediate', 4),
('Sushi Rolls', 'Roll rice, nori, and fish or veggies; slice into pieces.', 7, 20, 0, 2, 2, 1, 'Intermediate', 5),
('Chicken Tenders', 'Bread chicken strips; deep fry until golden and crispy.', 8, 15, 20, 3, 4, 9, 'Intermediate', 8),
('Zucchini Fritters', 'Grate zucchini; mix with eggs and flour; fry in oil.', 9, 15, 10, 2, 3, 1, 'Beginner', 8),
('Pasta Primavera', 'Sauté mixed veggies; toss with cooked pasta and olive oil.', 10, 10, 20, 3, 4, 9, 'Beginner', 1),
('Stuffed Mushrooms', 'Fill mushroom caps with cream cheese and herbs; bake until soft.', 1, 15, 20, 4, 5, 1, 'Intermediate', 9),
('Tom Kha Gai', 'Simmer chicken with coconut milk, lemongrass, and chili.', 2, 15, 30, 3, 4, 6, 'Intermediate', 6),
('Lamb Curry', 'Simmer lamb with curry spices, tomatoes, and coconut milk.', 3, 20, 40, 4, 4, 9, 'Intermediate', 4),
('Falafel Salad', 'Serve homemade falafel on greens with tahini sauce.', 4, 20, 25, 3, 3, 2, 'Intermediate', 12),
('Crispy Tofu Stir-Fry', 'Stir-fry tofu with veggies; serve with rice.', 5, 15, 20, 3, 3, 2, 'Intermediate', 2),
('Mushroom Risotto', 'Cook mushrooms and rice with broth until creamy.', 6, 15, 30, 4, 4, 9, 'Intermediate', 9),
('Chicken Shawarma', 'Marinate chicken in spices; grill and serve with pita and veggies.', 7, 25, 25, 4, 4, 9, 'Intermediate', 12),
('Beef Tacos', 'Cook ground beef with taco seasoning; fill tortillas with beef, lettuce, and cheese.', 8, 10, 15, 3, 4, 9, 'Beginner', 3),
('Pasta Carbonara', 'Cook pasta; toss with egg, cheese, pancetta, and pepper.', 9, 10, 15, 3, 4, 9, 'Intermediate', 1),
('Vegetable Frittata', 'Whisk eggs with veggies; bake until golden.', 10, 10, 25, 4, 3, 1, 'Beginner', 8),
('Tomato Basil Soup', 'Simmer tomatoes and basil; blend until smooth.', 1, 15, 30, 4, 3, 1, 'Beginner', 9),
('Grilled Cheese Sandwich', 'Grill bread with butter and melted cheese inside.', 2, 5, 10, 1, 2, 1, 'Beginner', 8),
('Pork Schnitzel', 'Bread and fry pork cutlets; serve with lemon wedges.', 3, 20, 25, 4, 4, 9, 'Intermediate', 9),
('Lentil Tacos', 'Cook lentils with taco seasoning; serve in tortillas with toppings.', 4, 15, 20, 4, 3, 2, 'Beginner', 3),
('Beef and Broccoli', 'Stir-fry beef with broccoli and soy sauce.', 5, 10, 15, 3, 3, 9, 'Intermediate', 2),
('Carrot Cake', 'Mix carrots with flour, sugar, and spices; bake and frost with cream cheese icing.', 6, 15, 40, 6, 5, 9, 'Intermediate', 8),
('Chicken Parmesan', 'Bread and fry chicken; top with marinara and cheese; bake.', 7, 20, 30, 4, 4, 9, 'Intermediate', 1),
('Ramen Noodles', 'Cook ramen noodles in broth with soy sauce and veggies.', 8, 10, 5, 2, 3, 9, 'Beginner', 5),
('Baked Salmon', 'Season salmon with herbs and bake until flaky.', 9, 10, 20, 3, 4, 9, 'Intermediate', 5),
('Chicken Alfredo', 'Cook pasta; mix with chicken and creamy Alfredo sauce.', 10, 10, 20, 3, 4, 9, 'Intermediate', 1),
('Roast Chicken', 'Season whole chicken and roast until golden and crispy.', 1, 20, 90, 6, 4, 9, 'Intermediate', 8),
('Spinach Artichoke Dip', 'Mix spinach, artichokes, and cheese; bake until bubbly.', 2, 15, 30, 4, 5, 1, 'Intermediate', 9),
('Lamb Shawarma', 'Marinate lamb; grill and serve with pita and tahini sauce.', 3, 25, 30, 4, 4, 9, 'Intermediate', 12),
('Sweet Potato Fries', 'Cut sweet potatoes; toss with olive oil and bake until crispy.', 4, 10, 25, 3, 3, 1, 'Beginner', 8),
('Buffalo Wings', 'Toss wings in buffalo sauce; bake or fry until crispy.', 5, 10, 30, 4, 4, 9, 'Intermediate', 8),
('Chili', 'Simmer ground beef, beans, and spices in tomato sauce.', 6, 15, 60, 6, 3, 1, 'Intermediate', 8),
('Pumpkin Soup', 'Simmer pumpkin with spices and cream; blend until smooth.', 7, 10, 30, 4, 3, 1, 'Beginner', 8),
('Chicken Fajitas', 'Sauté chicken, peppers, and onions; serve in tortillas with toppings.', 8, 15, 15, 4, 4, 9, 'Intermediate', 3),
('Vegetarian Chili', 'Cook beans, veggies, and spices in tomato sauce.', 9, 15, 45, 4, 3, 2, 'Beginner', 8),
('Chicken and Rice', 'Cook chicken with rice, broth, and seasonings until tender.', 10, 15, 30, 4, 4, 9, 'Beginner', 8),
('Eggplant Parmesan Sandwich', 'Bread and fry eggplant; top with marinara and cheese; serve on a bun.', 1, 20, 30, 2, 4, 1, 'Intermediate', 9),
('Baked Potatoes', 'Pierce potatoes and bake until tender; top with butter and sour cream.', 2, 5, 45, 4, 3, 1, 'Beginner', 8),
('Fettuccine Alfredo', 'Cook pasta; toss with a creamy Parmesan sauce.', 3, 10, 15, 3, 4, 9, 'Intermediate', 1),
('Chicken Kiev', 'Stuff chicken with garlic butter; bread and fry until crispy.', 4, 20, 30, 4, 4, 9, 'Intermediate', 9),
('Beef Bulgogi', 'Marinate beef in soy sauce and sesame oil; grill with vegetables.', 1, 15, 20, 4, 4, 9, 'Intermediate', 10),
('Chickpea Curry', 'Simmer chickpeas with coconut milk, tomatoes, and spices.', 2, 15, 25, 4, 3, 2, 'Intermediate', 4),
('Stuffed Peppers', 'Fill bell peppers with ground turkey, rice, and spices; bake.', 3, 15, 30, 4, 4, 9, 'Intermediate', 8),
('Pulled Jackfruit Tacos', 'Shred jackfruit and cook with taco seasoning; serve in tortillas.', 4, 10, 20, 4, 5, 2, 'Beginner', 3),
('Mango Sticky Rice', 'Cook sticky rice with coconut milk; serve with fresh mango slices.', 5, 15, 20, 2, 5, 2, 'Beginner', 6),
('Lemon Herb Salmon', 'Season salmon with lemon and herbs; bake or grill until done.', 6, 10, 15, 4, 4, 9, 'Intermediate', 5),
('Crispy Tofu', 'Toss tofu in cornstarch and fry until crispy; serve with dipping sauce.', 7, 10, 15, 3, 3, 2, 'Beginner', 2),
('Coconut Lentil Soup', 'Simmer lentils in coconut milk with curry spices and vegetables.', 9, 10, 30, 4, 3, 2, 'Beginner', 4),
('Vegetable Tempura', 'Dip vegetables in batter and deep fry until golden and crispy.', 10, 15, 20, 4, 3, 2, 'Intermediate', 5),
('Shrimp Scampi', 'Cook shrimp with garlic, lemon, and butter; serve with pasta.', 2, 10, 15, 3, 4, 9, 'Intermediate', 1),
('Spaghetti Carbonara', 'Toss pasta with eggs, cheese, pancetta, and pepper.', 3, 10, 15, 4, 4, 9, 'Intermediate', 1),
('Fajita Bowls', 'Grill seasoned chicken or steak with peppers; serve over rice.', 4, 15, 20, 4, 4, 9, 'Beginner', 3),
('Pork Schnitzel', 'Bread and fry pork cutlets until crispy; serve with lemon wedges.', 5, 20, 30, 4, 4, 9, 'Intermediate', 9),
('Carrot Ginger Soup', 'Simmer carrots and ginger in broth; blend until smooth.', 6, 15, 30, 4, 3, 1, 'Beginner', 8),
('Veggie Pizza', 'Top pizza dough with vegetables, tomato sauce, and cheese; bake.', 7, 10, 15, 2, 3, 2, 'Beginner', 1),
('Chili Con Carne', 'Simmer ground beef, beans, and spices in a tomato sauce.', 8, 15, 45, 4, 4, 9, 'Intermediate', 8),
('Eggplant Stir Fry', 'Stir-fry sliced eggplant with soy sauce and garlic.', 9, 10, 15, 4, 3, 2, 'Beginner', 2),
('Banana Bread', 'Mix mashed bananas with flour, sugar, and eggs; bake until golden.', 1, 10, 60, 4, 5, 9, 'Beginner', 8),
('Zucchini Noodles', 'Toss zucchini noodles with marinara sauce and parmesan cheese.', 2, 10, 15, 3, 3, 2, 'Beginner', 7),
('Falafel', 'Blend chickpeas with herbs; form into balls and fry until crispy.', 4, 15, 30, 4, 3, 2, 'Intermediate', 12),
('Grilled Cheese and Bacon', 'Grill cheese sandwich with crispy bacon inside.', 5, 10, 10, 3, 4, 9, 'Beginner', 9),
('Chicken Parmesan', 'Bread chicken, fry, and top with marinara and cheese; bake.', 6, 15, 30, 4, 4, 9, 'Intermediate', 1),
('Vegan Pancakes', 'Make pancakes with plant-based milk and egg replacer; serve with syrup.', 7, 10, 15, 3, 3, 2, 'Beginner', 7),
('Pasta Primavera', 'Cook pasta with mixed vegetables and olive oil; serve with parmesan.', 8, 10, 20, 4, 3, 9, 'Beginner', 1),
('Meatball Subs', 'Make meatballs and bake with marinara sauce; serve on a sub roll with cheese.', 9, 15, 30, 4, 4, 9, 'Intermediate', 8),
('Baked Avocado Eggs', 'Bake an egg inside half an avocado; season with spices.', 10, 10, 15, 2, 3, 1, 'Beginner', 7),
('Mushroom Risotto', 'Simmer rice with mushrooms, butter, and parmesan until creamy.', 1, 15, 30, 4, 4, 9, 'Intermediate', 9),
('Peking Duck', 'Roast duck until crispy; serve with pancakes and hoisin sauce.', 2, 20, 60, 6, 4, 9, 'Advanced', 2),
('Crispy Fish Tacos', 'Fry battered fish fillets and serve in tortillas with cabbage and salsa.', 3, 15, 20, 3, 4, 9, 'Intermediate', 5),
('Pumpkin Soup', 'Simmer pumpkin with onions, garlic, and stock; blend until smooth.', 4, 15, 30, 4, 3, 1, 'Beginner', 8),
('Shakshuka with Feta', 'Poach eggs in a tomato sauce with onions and spices; serve with feta and bread.', 5, 10, 25, 4, 3, 1, 'Beginner', 12),
('BBQ Chicken Wings', 'Grill chicken wings with BBQ sauce until crispy.', 6, 10, 25, 4, 4, 9, 'Intermediate', 8),
('Vegan Burrito Bowl', 'Layer rice, beans, veggies, and salsa in a bowl; top with avocado.', 7, 10, 15, 3, 3, 2, 'Beginner', 3),
('Pulled Beef Nachos', 'Layer chips with pulled beef, cheese, and jalapenos; bake until melted.', 8, 15, 20, 4, 4, 9, 'Intermediate', 8),
('Oatmeal with Berries', 'Cook oats with milk or water; top with fresh berries and honey.', 9, 5, 10, 2, 3, 2, 'Beginner', 7),
('Moussaka', 'Layer eggplant, ground beef, and béchamel sauce; bake until golden.', 10, 20, 45, 4, 4, 9, 'Intermediate', 13),
('Chicken Shawarma', 'Season chicken with spices; roast and serve with pita and vegetables.', 1, 15, 30, 4, 4, 9, 'Intermediate', 12),
('Vegetable Paella', 'Simmer rice with saffron, peas, and bell peppers until tender.', 2, 15, 35, 4, 3, 2, 'Intermediate', 14),
('Pasta Alfredo', 'Toss pasta in a creamy sauce made of butter, cream, and parmesan.', 3, 10, 20, 4, 4, 9, 'Beginner', 1),
('Baked Apples', 'Core apples, stuff with cinnamon and sugar; bake until tender.', 4, 10, 30, 4, 5, 9, 'Beginner', 8),
('Korean BBQ', 'Grill marinated meats; serve with rice, kimchi, and dipping sauces.', 5, 20, 30, 4, 4, 9, 'Intermediate', 10),
('Panzanella Salad', 'Toss stale bread, tomatoes, cucumbers, and basil with vinaigrette.', 6, 10, 10, 3, 3, 2, 'Beginner', 13),
('Salmon Poke Bowl', 'Layer salmon, rice, avocado, and soy sauce in a bowl.', 7, 10, 15, 3, 4, 9, 'Beginner', 5),
('Beef Empanadas', 'Fill pastry with seasoned ground beef and vegetables; bake until golden.', 8, 15, 30, 4, 4, 9, 'Intermediate', 14),
('Roasted Vegetables', 'Roast mixed vegetables like carrots, potatoes, and zucchini with herbs.', 9, 15, 40, 4, 3, 1, 'Beginner', 7),
('Lamb Koftas', 'Grill ground lamb mixed with spices; serve with yogurt sauce.', 10, 15, 20, 4, 4, 9, 'Intermediate', 4),
('Spicy Black Bean Burgers', 'Mash black beans with spices and breadcrumbs; form patties; pan-fry until browned.', 3, 25, 20, 6, 3, 2, 'Intermediate', 3),
('Salmon Nigiri', 'Prepare sushi rice; slice fresh salmon; form rice balls and top with salmon.', 5, 20, 10, 2, 5, 6, 'Intermediate', 5),
('Pad See Ew', 'Stir-fry wide rice noodles with Chinese broccoli, egg, and soy sauce.', 6, 15, 15, 2, 3, 9, 'Intermediate', 6),
('Greek Salad', 'Combine tomatoes, cucumbers, olives, feta cheese, and a simple vinaigrette.', 7, 10, 0, 4, 3, 1, 'Beginner', 13),
('Mushroom Risotto', 'Sauté mushrooms and Arborio rice; gradually add broth until creamy.', 9, 20, 30, 4, 1, 1, 'Advanced', 1),
('Lemon Herb Roasted Chicken', 'Roast a whole chicken with lemon, herbs, and vegetables.', 10, 15, 60, 6, 4, 9, 'Intermediate', 8),
('Chocolate Lava Cakes', 'Prepare rich chocolate batter; bake until edges are set and center is molten.', 11, 20, 15, 4, 5, 9, 'Advanced', 9),
('Spring Rolls with Peanut Sauce', 'Assemble fresh rice paper rolls with shrimp, vegetables, and herbs; serve with peanut sauce.', 13, 30, 0, 4, 3, 9, 'Intermediate', 11),
('Lamb Kebabs with Tzatziki', 'Marinate lamb cubes; grill on skewers; serve with refreshing cucumber-yogurt sauce.', 14, 25, 20, 4, 4, 9, 'Intermediate', 12),
('Tofu Scramble', 'Crumble tofu and sauté with vegetables and turmeric for a breakfast scramble.', 17, 10, 15, 2, 2, 2, 'Beginner', 8),
('Gazpacho', 'Blend fresh tomatoes, cucumbers, peppers, and garlic for a chilled soup.', 18, 15, 0, 4, 3, 9, 'Beginner', 14),
('Chicken Fajitas', 'Slice chicken and peppers; sauté with onions and fajita seasoning; serve with tortillas.', 19, 20, 25, 4, 4, 9, 'Intermediate', 3),
('Peanut Noodles', 'Cook noodles; toss with a creamy peanut sauce and vegetables.', 21, 15, 15, 2, 3, 2, 'Beginner', 6),
('Moussaka', 'Layer eggplant, ground meat, and béchamel sauce; bake until golden brown.', 22, 40, 60, 6, 4, 9, 'Advanced', 13),
('Corn Chowder', 'Sauté vegetables and corn in a creamy broth; season to taste.', 23, 15, 25, 4, 3, 1, 'Beginner', 8),
('Steak with Chimichurri', 'Grill steak to desired doneness; top with fresh herb-garlic chimichurri sauce.', 24, 10, 20, 2, 4, 9, 'Intermediate', 7),
('Fruit Salad with Honey-Lime Dressing', 'Combine various fresh fruits; drizzle with a honey-lime dressing.', 25, 15, 0, 4, 5, 9, 'Beginner', 8),
('Pho', 'Prepare a flavorful broth; add rice noodles, herbs, and thinly sliced beef or tofu.', 27, 30, 60, 4, 3, 9, 'Advanced', 11),
('Falafel with Pita and Hummus', 'Grind chickpeas and spices; form into patties and fry or bake; serve in pita with hummus.', 28, 35, 20, 4, 3, 2, 'Intermediate', 12),
('Spanakopita', 'Layer phyllo dough with a spinach and feta cheese filling; bake until golden.', 29, 30, 40, 6, 1, 1, 'Intermediate', 13),
('Paella', 'Cook rice with saffron, seafood, vegetables, and meat in a large shallow pan.', 30, 30, 45, 6, 4, 9, 'Advanced', 14),
('French Onion Soup', 'Caramelize onions; simmer in beef broth with thyme; top with bread and melted cheese.', 31, 20, 40, 4, 3, 9, 'Intermediate', 9),
('Black Forest Cake', 'Layer chocolate cake with whipped cream and cherries; decorate with chocolate shavings.', 33, 45, 30, 8, 5, 9, 'Advanced', 9),
('Banh Mi (Vietnamese Sandwich)', 'Fill a baguette with pickled vegetables, cilantro, jalapeños, and grilled meat or tofu.', 35, 25, 10, 2, 3, 9, 'Intermediate', 11),
('Shakshuka', 'Poach eggs in a flavorful tomato sauce with peppers and spices.', 36, 15, 20, 2, 2, 1, 'Beginner', 12),
('Tabbouleh', 'Combine bulgur wheat, parsley, mint, tomatoes, cucumbers, lemon juice, and olive oil.', 37, 20, 0, 4, 3, 2, 'Beginner', 12),
('Tortilla Soup', 'Simmer tomatoes, onions, garlic, and broth; serve with tortilla strips, avocado, and cheese.', 38, 20, 30, 4, 3, 9, 'Intermediate', 3),
('Tempura Vegetables', 'Dip assorted vegetables in a light batter and deep-fry until crispy.', 39, 20, 15, 3, 1, 2, 'Intermediate', 5),
('Feta and Spinach Stuffed Chicken', 'Stuff chicken breasts with feta cheese and spinach; bake until cooked through.', 41, 20, 30, 4, 4, 9, 'Intermediate', 13),
('Creme brulee', 'Prepare a rich custard base; caramelize a sugar topping with a torch.', 43, 25, 40, 4, 5, 7, 'Advanced', 9),
('Chicken Satay with Peanut Sauce', 'Marinate chicken skewers; grill or bake; serve with a flavorful peanut sauce.', 44, 25, 15, 4, 4, 9, 'Intermediate', 6),
('Classic Lentil Bowl', 'Toast bread; layer with avocado and egg; season and serve.', 5, 17, 43, 5, 2, 4, 'Advanced', 2),
('Crispy Chicken Curry', 'Roast vegetables; toss with quinoa and feta; drizzle dressing.', 8, 20, 10, 6, 4, 4, 'Advanced', 8),
('Loaded Lentil Wrap', 'Scramble eggs with spinach; wrap in tortilla with salsa.', 9, 26, 26, 6, 4, 2, 'Intermediate', 8),
('Classic Egg Pizza', 'Cook rice; stir in beans and herbs; serve with avocado.', 1, 13, 42, 2, 1, 3, 'Beginner', 5),
('Zesty Beef Tacos', 'Cook rice; stir in beans and herbs; serve with avocado.', 6, 19, 15, 6, 2, 9, 'Beginner', 6),
('Hearty Beef Toast', 'Sauté mushrooms in garlic butter; serve over polenta.', 1, 26, 11, 5, 2, 1, 'Beginner', 5),
('Crispy Avocado Pizza', 'Season chicken; grill until golden; serve with side salad.', 4, 9, 15, 5, 5, 2, 'Beginner', 1),
('Spicy Sweet Potato Burger', 'Grill shrimp with lemon; plate over herbed couscous.', 5, 14, 40, 1, 1, 4, 'Advanced', 10),
('Spicy Turkey Pasta', 'Cook rice; stir in beans and herbs; serve with avocado.', 8, 22, 2, 4, 2, 1, 'Beginner', 3),
('Creamy Tofu Skillet', 'Scramble eggs with spinach; wrap in tortilla with salsa.', 2, 18, 21, 5, 2, 6, 'Beginner', 3),
('Tangy Zucchini Pizza', 'Roast vegetables; toss with quinoa and feta; drizzle dressing.', 3, 20, 6, 6, 1, 4, 'Intermediate', 9),
('Tangy Beef Salad', 'Roast vegetables; toss with quinoa and feta; drizzle dressing.', 6, 18, 27, 6, 2, 6, 'Beginner', 6),
('Fusion Beef Pizza', 'Fry tofu until golden; toss with teriyaki sauce and broccoli.', 2, 20, 5, 4, 4, 7, 'Advanced', 6),
('Hearty Beef Skillet', 'Grill shrimp with lemon; plate over herbed couscous.', 3, 8, 44, 1, 4, 4, 'Advanced', 3),
('Savory Sweet Potato Curry', 'Grill shrimp with lemon; plate over herbed couscous.', 9, 28, 20, 5, 5, 4, 'Intermediate', 1),
('Spicy Lentil Salad', 'Roast vegetables; toss with quinoa and feta; drizzle dressing.', 3, 18, 15, 5, 5, 6, 'Advanced', 10),
('Savory Avocado Tacos', 'Scramble eggs with spinach; wrap in tortilla with salsa.', 10, 12, 31, 6, 1, 5, 'Intermediate', 7),
('Fusion Lentil Tacos', 'Roast vegetables; toss with quinoa and feta; drizzle dressing.', 7, 10, 34, 6, 4, 3, 'Advanced', 5),
('Delight Lentil Salad', 'Fry tofu until golden; toss with teriyaki sauce and broccoli.', 6, 21, 41, 6, 1, 6, 'Advanced', 7),
('Classic Avocado Pasta', 'Roast vegetables; toss with quinoa and feta; drizzle dressing.', 5, 24, 30, 6, 1, 8, 'Advanced', 8),
('Savory Avocado Pasta', 'Roast vegetables; toss with quinoa and feta; drizzle dressing.', 1, 5, 1, 5, 4, 5, 'Advanced', 2),
('Zesty Zucchini Stir Fry', 'Toast bread; layer with avocado and egg; season and serve.', 2, 28, 5, 3, 3, 7, 'Advanced', 2),
('Savory Avocado Stir Fry', 'Simmer lentils with spices; top with yogurt and cilantro.', 1, 13, 0, 6, 3, 1, 'Intermediate', 4),
('Creamy Egg Pasta', 'Sauté mushrooms in garlic butter; serve over polenta.', 9, 16, 31, 4, 5, 5, 'Beginner', 1),
('Hearty Beef Pasta', 'Scramble eggs with spinach; wrap in tortilla with salsa.', 4, 30, 25, 1, 1, 7, 'Intermediate', 4),
('Fusion Chicken Stir Fry', 'Season chicken; grill until golden; serve with side salad.', 6, 29, 10, 2, 1, 1, 'Intermediate', 3),
('Creamy Sweet Potato Soup', 'Boil pasta; mix with creamy pesto and cherry tomatoes.', 6, 20, 36, 1, 3, 8, 'Advanced', 2),
('Creamy Tofu Pizza', 'Grill shrimp with lemon; plate over herbed couscous.', 2, 29, 5, 1, 3, 6, 'Beginner', 5),
('Toasty Egg Bowl', 'Grill shrimp with lemon; plate over herbed couscous.', 7, 9, 43, 4, 2, 6, 'Beginner', 9),
('Hearty Mushroom Pizza', 'Grill shrimp with lemon; plate over herbed couscous.', 8, 20, 40, 1, 4, 4, 'Intermediate', 8),
('Creamy Tofu Bowl', 'Simmer lentils with spices; top with yogurt and cilantro.', 8, 6, 28, 6, 2, 5, 'Beginner', 4),
('Toasty Turkey Skillet', 'Boil pasta; mix with creamy pesto and cherry tomatoes.', 4, 23, 6, 2, 1, 7, 'Advanced', 3),
('Classic Tofu Toast', 'Roast vegetables; toss with quinoa and feta; drizzle dressing.', 6, 13, 16, 2, 5, 4, 'Beginner', 9),
('Zesty Zucchini Toast', 'Cook rice; stir in beans and herbs; serve with avocado.', 10, 17, 41, 1, 5, 6, 'Beginner', 4),
('Crispy Beef Burger', 'Toast bread; layer with avocado and egg; season and serve.', 4, 23, 13, 5, 3, 5, 'Intermediate', 6),
('Delight Lentil Salad', 'Roast vegetables; toss with quinoa and feta; drizzle dressing.', 8, 5, 27, 4, 3, 2, 'Intermediate', 9),
('Savory Shrimp Tacos', 'Roast vegetables; toss with quinoa and feta; drizzle dressing.', 2, 22, 3, 3, 1, 7, 'Advanced', 6),
('Crispy Zucchini Salad', 'Roast vegetables; toss with quinoa and feta; drizzle dressing.', 3, 22, 8, 4, 5, 6, 'Advanced', 2),
('Crispy Zucchini Tacos', 'Grill shrimp with lemon; plate over herbed couscous.', 10, 26, 44, 4, 4, 5, 'Advanced', 6),
('Spicy Chicken Pasta', 'Scramble eggs with spinach; wrap in tortilla with salsa.', 10, 16, 37, 3, 1, 1, 'Advanced', 3),
('Toasty Zucchini Pizza', 'Simmer lentils with spices; top with yogurt and cilantro.', 6, 28, 24, 5, 5, 7, 'Advanced', 5),
('Crispy Egg Pizza', 'Boil pasta; mix with creamy pesto and cherry tomatoes.', 5, 9, 18, 4, 4, 4, 'Advanced', 5),
('Savory Avocado Burger', 'Fry tofu until golden; toss with teriyaki sauce and broccoli.', 8, 20, 16, 5, 2, 2, 'Intermediate', 4),
('Loaded Tofu Bowl', 'Fry tofu until golden; toss with teriyaki sauce and broccoli.', 2, 8, 25, 2, 3, 6, 'Beginner', 1),
('Zesty Turkey Toast', 'Scramble eggs with spinach; wrap in tortilla with salsa.', 4, 5, 37, 6, 2, 4, 'Advanced', 9),
('Spicy Zucchini Stir Fry', 'Roast vegetables; toss with quinoa and feta; drizzle dressing.', 3, 20, 22, 5, 5, 3, 'Advanced', 7),
('Savory Tofu Curry', 'Boil pasta; mix with creamy pesto and cherry tomatoes.', 10, 15, 5, 2, 5, 8, 'Intermediate', 9),
('Spicy Lentil Curry', 'Toast bread; layer with avocado and egg; season and serve.', 8, 26, 15, 3, 5, 5, 'Advanced', 3),
('Spicy Sweet Potato Curry', 'Cook rice; stir in beans and herbs; serve with avocado.', 3, 29, 5, 3, 2, 4, 'Advanced', 2),
('Spicy Turkey Toast', 'Season chicken; grill until golden; serve with side salad.', 7, 29, 6, 4, 5, 3, 'Advanced', 3),
('Toasty Mushroom Skillet', 'Grill shrimp with lemon; plate over herbed couscous.', 7, 23, 37, 5, 3, 8, 'Beginner', 6),
('Delight Mushroom Burger', 'Roast vegetables; toss with quinoa and feta; drizzle dressing.', 5, 29, 38, 6, 5, 9, 'Intermediate', 4),
('Creamy Turkey Stir Fry', 'Boil pasta; mix with creamy pesto and cherry tomatoes.', 8, 29, 36, 1, 5, 1, 'Advanced', 5),
('Toasty Lentil Tacos', 'Sauté mushrooms in garlic butter; serve over polenta.', 1, 6, 31, 5, 5, 2, 'Advanced', 2),
('Zesty Beef Bowl', 'Sauté mushrooms in garlic butter; serve over polenta.', 1, 21, 45, 4, 5, 6, 'Intermediate', 8),
('Delight Zucchini Stir Fry', 'Season chicken; grill until golden; serve with side salad.', 9, 13, 30, 4, 1, 3, 'Advanced', 1),
('Zesty Shrimp Toast', 'Scramble eggs with spinach; wrap in tortilla with salsa.', 3, 21, 20, 4, 5, 5, 'Intermediate', 3),
('Loaded Tofu Soup', 'Sauté mushrooms in garlic butter; serve over polenta.', 5, 28, 33, 6, 1, 7, 'Intermediate', 6),
('Tangy Tofu Skillet', 'Scramble eggs with spinach; wrap in tortilla with salsa.', 5, 18, 29, 1, 4, 1, 'Beginner', 5),
('Delight Tofu Salad', 'Simmer lentils with spices; top with yogurt and cilantro.', 4, 5, 20, 5, 5, 5, 'Advanced', 4),
('Toasty Lentil Skillet', 'Roast vegetables; toss with quinoa and feta; drizzle dressing.', 7, 13, 27, 5, 2, 3, 'Advanced', 5),
('Savory Mushroom Pasta', 'Grill shrimp with lemon; plate over herbed couscous.', 9, 9, 33, 3, 1, 4, 'Intermediate', 6),
('Crispy Mushroom Bowl', 'Toast bread; layer with avocado and egg; season and serve.', 7, 18, 15, 5, 5, 2, 'Beginner', 2),
('Tangy Avocado Wrap', 'Roast vegetables; toss with quinoa and feta; drizzle dressing.', 9, 25, 42, 4, 1, 8, 'Advanced', 6),
('Savory Chicken Toast', 'Cook rice; stir in beans and herbs; serve with avocado.', 4, 15, 44, 4, 4, 2, 'Advanced', 10),
('Fusion Beef Stir Fry', 'Scramble eggs with spinach; wrap in tortilla with salsa.', 2, 26, 22, 4, 3, 3, 'Beginner', 5),
('Classic Avocado Tacos', 'Toast bread; layer with avocado and egg; season and serve.', 8, 9, 5, 6, 5, 9, 'Beginner', 2),
('Creamy Shrimp Pizza', 'Cook rice; stir in beans and herbs; serve with avocado.', 6, 25, 4, 1, 5, 4, 'Intermediate', 6),
('Classic Tofu Curry', 'Simmer lentils with spices; top with yogurt and cilantro.', 8, 29, 22, 4, 1, 4, 'Advanced', 8),
('Delight Sweet Potato Bowl', 'Scramble eggs with spinach; wrap in tortilla with salsa.', 5, 22, 2, 4, 5, 6, 'Beginner', 6),
('Classic Chicken Soup', 'Boil pasta; mix with creamy pesto and cherry tomatoes.', 7, 14, 31, 4, 1, 9, 'Advanced', 4),
('Tangy Egg Burger', 'Cook rice; stir in beans and herbs; serve with avocado.', 1, 24, 5, 5, 2, 7, 'Beginner', 4),
('Tangy Avocado Pizza', 'Toast bread; layer with avocado and egg; season and serve.', 8, 6, 16, 2, 5, 6, 'Beginner', 10),
('Hearty Avocado Skillet', 'Toast bread; layer with avocado and egg; season and serve.', 5, 29, 28, 2, 3, 3, 'Intermediate', 8),
('Toasty Avocado Pasta', 'Grill shrimp with lemon; plate over herbed couscous.', 2, 29, 5, 2, 3, 6, 'Beginner', 6),
('Toasty Lentil Burger', 'Sauté mushrooms in garlic butter; serve over polenta.', 2, 24, 8, 4, 1, 5, 'Intermediate', 9),
('Crispy Mushroom Pizza', 'Sauté mushrooms in garlic butter; serve over polenta.', 1, 16, 24, 4, 5, 2, 'Advanced', 6),
('Creamy Sweet Potato Pasta', 'Scramble eggs with spinach; wrap in tortilla with salsa.', 7, 17, 27, 1, 4, 2, 'Advanced', 2),
('Crispy Eggplant Tacos', 'Toast bread; layer with avocado and egg; season and serve.', 3, 19, 26, 5, 3, 3, 'Intermediate', 3),
('Hearty Zucchini Bowl', 'Season chicken; grill until golden; serve with side salad.', 10, 16, 11, 4, 4, 7, 'Advanced', 9),
('Fusion Sweet Potato Tacos', 'Grill shrimp with lemon; plate over herbed couscous.', 7, 7, 12, 1, 1, 9, 'Intermediate', 2),
('Zesty Beef Burger', 'Boil pasta; mix with creamy pesto and cherry tomatoes.', 10, 16, 11, 6, 3, 3, 'Intermediate', 7),
('Tangy Sweet Potato Pasta', 'Grill shrimp with lemon; plate over herbed couscous.', 2, 7, 13, 3, 5, 1, 'Beginner', 10),
('Delight Turkey Pasta', 'Fry tofu until golden; toss with teriyaki sauce and broccoli.', 5, 19, 8, 5, 2, 3, 'Intermediate', 5),
('Classic Shrimp Pasta', 'Grill shrimp with lemon; plate over herbed couscous.', 9, 17, 13, 4, 5, 8, 'Beginner', 5),
('Crispy Lentil Pizza', 'Fry tofu until golden; toss with teriyaki sauce and broccoli.', 1, 24, 45, 1, 1, 6, 'Advanced', 2),
('Spicy Zucchini Pasta', 'Toast bread; layer with avocado and egg; season and serve.', 8, 11, 13, 6, 4, 7, 'Intermediate', 6),
('Hearty Tofu Pizza', 'Toast bread; layer with avocado and egg; season and serve.', 2, 19, 1, 3, 4, 2, 'Intermediate', 3),
('Classic Lentil Skillet', 'Grill shrimp with lemon; plate over herbed couscous.', 9, 16, 44, 5, 4, 4, 'Intermediate', 8),
('Delight Avocado Burger', 'Season chicken; grill until golden; serve with side salad.', 6, 24, 30, 4, 4, 2, 'Intermediate', 2),
('Fusion Sweet Potato Pizza', 'Boil pasta; mix with creamy pesto and cherry tomatoes.', 1, 11, 35, 4, 5, 4, 'Intermediate', 6),
('Zesty Beef Stir Fry', 'Grill shrimp with lemon; plate over herbed couscous.', 6, 20, 27, 4, 1, 5, 'Beginner', 8),
('Creamy Chicken Skillet', 'Toast bread; layer with avocado and egg; season and serve.', 6, 28, 11, 3, 1, 7, 'Intermediate', 7),
('Delight Turkey Bowl', 'Scramble eggs with spinach; wrap in tortilla with salsa.', 1, 19, 1, 1, 2, 8, 'Beginner', 7),
('Classic Lentil Pizza', 'Toast bread; layer with avocado and egg; season and serve.', 5, 19, 7, 4, 4, 5, 'Intermediate', 7),
('Zesty Turkey Bowl', 'Grill shrimp with lemon; plate over herbed couscous.', 9, 16, 7, 6, 3, 9, 'Beginner', 9),
('Creamy Eggplant Salad', 'Season chicken; grill until golden; serve with side salad.', 2, 18, 4, 6, 3, 5, 'Advanced', 7),
('Delight Beef Bowl', 'Season chicken; grill until golden; serve with side salad.', 6, 15, 2, 2, 4, 5, 'Advanced', 10),
('Toasty Lentil Stir Fry', 'Scramble eggs with spinach; wrap in tortilla with salsa.', 1, 12, 28, 1, 4, 1, 'Intermediate', 4),
('Creamy Beef Burger', 'Scramble eggs with spinach; wrap in tortilla with salsa.', 4, 6, 20, 5, 4, 8, 'Beginner', 3),
('Crispy Tofu Soup', 'Sauté mushrooms in garlic butter; serve over polenta.', 7, 30, 21, 3, 3, 2, 'Intermediate', 5),
('Zesty Eggplant Stir Fry', 'Sauté mushrooms in garlic butter; serve over polenta.', 1, 14, 32, 3, 1, 7, 'Intermediate', 10),
('Spicy Turkey Pizza', 'Sauté mushrooms in garlic butter; serve over polenta.', 7, 6, 7, 2, 4, 6, 'Advanced', 3),
('Toasty Chicken Pizza', 'Fry tofu until golden; toss with teriyaki sauce and broccoli.', 2, 27, 37, 1, 2, 2, 'Intermediate', 2),
('Loaded Turkey Bowl', 'Grill shrimp with lemon; plate over herbed couscous.', 5, 12, 34, 1, 1, 5, 'Advanced', 4),
('Classic Tofu Bowl', 'Grill shrimp with lemon; plate over herbed couscous.', 1, 11, 25, 4, 4, 4, 'Intermediate', 2),
('Tangy Mushroom Toast', 'Cook rice; stir in beans and herbs; serve with avocado.', 3, 17, 40, 4, 2, 8, 'Beginner', 9),
('Creamy Shrimp Pizza', 'Boil pasta; mix with creamy pesto and cherry tomatoes.', 10, 10, 11, 4, 3, 2, 'Advanced', 9),
('Savory Chicken Pizza', 'Season chicken; grill until golden; serve with side salad.', 9, 30, 31, 4, 3, 2, 'Intermediate', 1),
('Loaded Lentil Wrap', 'Roast vegetables; toss with quinoa and feta; drizzle dressing.', 8, 11, 14, 4, 2, 5, 'Advanced', 4),
('Classic Tofu Burger', 'Fry tofu until golden; toss with teriyaki sauce and broccoli.', 2, 19, 7, 4, 3, 9, 'Beginner', 2),
('Delight Shrimp Stir Fry', 'Toast bread; layer with avocado and egg; season and serve.', 2, 27, 44, 2, 5, 4, 'Beginner', 1),
('Creamy Avocado Wrap', 'Fry tofu until golden; toss with teriyaki sauce and broccoli.', 2, 25, 27, 6, 2, 7, 'Advanced', 8),
('Classic Lentil Stir Fry', 'Cook rice; stir in beans and herbs; serve with avocado.', 1, 15, 6, 5, 5, 8, 'Intermediate', 3),
('Spicy Turkey Pizza', 'Scramble eggs with spinach; wrap in tortilla with salsa.', 6, 6, 26, 1, 5, 4, 'Beginner', 9),
('Tangy Mushroom Pizza', 'Sauté mushrooms in garlic butter; serve over polenta.', 5, 27, 32, 3, 5, 6, 'Intermediate', 3),
('Tangy Egg Salad', 'Boil pasta; mix with creamy pesto and cherry tomatoes.', 8, 15, 37, 1, 1, 2, 'Intermediate', 1),
('Delight Mushroom Toast', 'Roast vegetables; toss with quinoa and feta; drizzle dressing.', 6, 16, 13, 5, 1, 8, 'Advanced', 4),
('Fusion Chicken Burger', 'Season chicken; grill until golden; serve with side salad.', 7, 22, 33, 2, 5, 6, 'Beginner', 2),
('Loaded Egg Pizza', 'Scramble eggs with spinach; wrap in tortilla with salsa.', 6, 27, 22, 5, 4, 6, 'Beginner', 4),
('Fusion Beef Stir Fry', 'Grill shrimp with lemon; plate over herbed couscous.', 10, 10, 12, 5, 3, 9, 'Advanced', 4),
('Crispy Zucchini Pasta', 'Sauté mushrooms in garlic butter; serve over polenta.', 3, 28, 22, 4, 1, 7, 'Intermediate', 7),
('Classic Eggplant Tacos', 'Grill shrimp with lemon; plate over herbed couscous.', 8, 11, 21, 2, 1, 6, 'Beginner', 9),
('Tangy Zucchini Salad', 'Toast bread; layer with avocado and egg; season and serve.', 8, 24, 28, 3, 2, 6, 'Intermediate', 4),
('Loaded Sweet Potato Bowl', 'Simmer lentils with spices; top with yogurt and cilantro.', 3, 22, 2, 3, 1, 1, 'Advanced', 5),
('Fusion Shrimp Pizza', 'Roast vegetables; toss with quinoa and feta; drizzle dressing.', 4, 26, 35, 2, 4, 8, 'Beginner', 10),
('Crispy Tofu Salad', 'Fry tofu until golden; toss with teriyaki sauce and broccoli.', 4, 23, 29, 6, 1, 8, 'Beginner', 9),
('Tangy Mushroom Pizza', 'Grill shrimp with lemon; plate over herbed couscous.', 1, 9, 1, 2, 2, 1, 'Beginner', 10),
('Loaded Lentil Pasta', 'Grill shrimp with lemon; plate over herbed couscous.', 3, 6, 17, 4, 1, 9, 'Advanced', 4),
('Classic Tofu Skillet', 'Cook rice; stir in beans and herbs; serve with avocado.', 5, 25, 40, 2, 4, 8, 'Intermediate', 1),
('Hearty Chicken Salad', 'Toast bread; layer with avocado and egg; season and serve.', 8, 13, 9, 4, 1, 4, 'Intermediate', 7),
('Tangy Turkey Pasta', 'Roast vegetables; toss with quinoa and feta; drizzle dressing.', 8, 17, 25, 4, 2, 5, 'Beginner', 9),
('Spicy Sweet Potato Salad', 'Sauté mushrooms in garlic butter; serve over polenta.', 8, 9, 40, 1, 5, 2, 'Intermediate', 5),
('Zesty Shrimp Toast', 'Season chicken; grill until golden; serve with side salad.', 6, 5, 10, 1, 4, 7, 'Beginner', 5),
('Zesty Tofu Soup', 'Roast vegetables; toss with quinoa and feta; drizzle dressing.', 7, 20, 32, 2, 2, 3, 'Intermediate', 8),
('Classic Lentil Soup', 'Sauté mushrooms in garlic butter; serve over polenta.', 8, 29, 38, 4, 2, 1, 'Beginner', 10),
('Fusion Shrimp Salad', 'Roast vegetables; toss with quinoa and feta; drizzle dressing.', 4, 16, 11, 3, 1, 4, 'Beginner', 4),
('Crispy Tofu Burger', 'Sauté mushrooms in garlic butter; serve over polenta.', 4, 5, 41, 4, 4, 1, 'Intermediate', 9),
('Hearty Beef Salad', 'Sauté mushrooms in garlic butter; serve over polenta.', 5, 8, 18, 2, 4, 2, 'Advanced', 10),
('Fusion Tofu Tacos', 'Season chicken; grill until golden; serve with side salad.', 3, 9, 0, 5, 5, 1, 'Advanced', 2),
('Zesty Zucchini Burger', 'Grill shrimp with lemon; plate over herbed couscous.', 10, 25, 35, 5, 3, 1, 'Beginner', 6),
('Hearty Mushroom Skillet', 'Fry tofu until golden; toss with teriyaki sauce and broccoli.', 8, 24, 26, 6, 1, 6, 'Beginner', 4),
('Fusion Turkey Skillet', 'Scramble eggs with spinach; wrap in tortilla with salsa.', 10, 19, 8, 1, 2, 6, 'Intermediate', 1),
('Spicy Mushroom Stir Fry', 'Roast vegetables; toss with quinoa and feta; drizzle dressing.', 6, 12, 13, 6, 2, 8, 'Intermediate', 8),
('Toasty Turkey Toast', 'Grill shrimp with lemon; plate over herbed couscous.', 10, 17, 38, 1, 1, 9, 'Beginner', 3),
('Toasty Zucchini Pizza', 'Cook rice; stir in beans and herbs; serve with avocado.', 2, 15, 17, 1, 1, 3, 'Intermediate', 4),
('Delight Lentil Burger', 'Grill shrimp with lemon; plate over herbed couscous.', 7, 21, 11, 3, 2, 1, 'Intermediate', 2),
('Zesty Sweet Potato Toast', 'Scramble eggs with spinach; wrap in tortilla with salsa.', 7, 13, 42, 6, 4, 9, 'Intermediate', 3),
('Crispy Egg Salad', 'Cook rice; stir in beans and herbs; serve with avocado.', 8, 15, 39, 6, 2, 4, 'Advanced', 9),
('Toasty Tofu Bowl', 'Roast vegetables; toss with quinoa and feta; drizzle dressing.', 10, 7, 38, 2, 1, 7, 'Advanced', 3),
('Tangy Lentil Skillet', 'Sauté mushrooms in garlic butter; serve over polenta.', 6, 7, 6, 4, 3, 1, 'Advanced', 1),
('Creamy Zucchini Pizza', 'Season chicken; grill until golden; serve with side salad.', 6, 8, 1, 5, 4, 2, 'Intermediate', 10),
('Spicy Turkey Burger', 'Scramble eggs with spinach; wrap in tortilla with salsa.', 6, 9, 30, 3, 3, 7, 'Intermediate', 2),
('Spicy Eggplant Stir Fry', 'Cook rice; stir in beans and herbs; serve with avocado.', 2, 23, 33, 4, 5, 1, 'Advanced', 1),
('Creamy Avocado Wrap', 'Fry tofu until golden; toss with teriyaki sauce and broccoli.', 3, 23, 21, 4, 5, 9, 'Beginner', 6),
('Creamy Mushroom Bowl', 'Cook rice; stir in beans and herbs; serve with avocado.', 3, 5, 36, 4, 1, 9, 'Intermediate', 9),
('Toasty Beef Salad', 'Toast bread; layer with avocado and egg; season and serve.', 3, 5, 30, 3, 3, 6, 'Beginner', 1),
('Savory Mushroom Tacos', 'Fry tofu until golden; toss with teriyaki sauce and broccoli.', 4, 10, 5, 4, 3, 5, 'Beginner', 7),
('Savory Chicken Tacos', 'Simmer lentils with spices; top with yogurt and cilantro.', 1, 6, 15, 4, 4, 9, 'Advanced', 6),
('Classic Eggplant Pizza', 'Sauté mushrooms in garlic butter; serve over polenta.', 7, 6, 21, 1, 4, 8, 'Intermediate', 8),
('Fusion Eggplant Soup', 'Cook rice; stir in beans and herbs; serve with avocado.', 1, 23, 16, 1, 5, 7, 'Intermediate', 7),
('Creamy Turkey Stir Fry', 'Grill shrimp with lemon; plate over herbed couscous.', 9, 20, 31, 4, 3, 5, 'Beginner', 9),
('Classic Lentil Tacos', 'Sauté mushrooms in garlic butter; serve over polenta.', 2, 30, 33, 3, 4, 9, 'Beginner', 5),
('Savory Lentil Soup', 'Roast vegetables; toss with quinoa and feta; drizzle dressing.', 3, 10, 18, 2, 1, 3, 'Intermediate', 7),
('Crispy Tofu Pizza', 'Season chicken; grill until golden; serve with side salad.', 9, 18, 33, 3, 2, 2, 'Intermediate', 9),
('Loaded Egg Curry', 'Simmer lentils with spices; top with yogurt and cilantro.', 2, 21, 45, 2, 2, 2, 'Intermediate', 10),
('Tangy Turkey Tacos', 'Fry tofu until golden; toss with teriyaki sauce and broccoli.', 1, 6, 30, 3, 5, 9, 'Advanced', 9),
('Creamy Lentil Bowl', 'Toast bread; layer with avocado and egg; season and serve.', 7, 24, 11, 3, 2, 7, 'Advanced', 8),
('Spicy Mushroom Toast', 'Fry tofu until golden; toss with teriyaki sauce and broccoli.', 5, 13, 4, 1, 3, 2, 'Advanced', 4),
('Crispy Zucchini Toast', 'Cook rice; stir in beans and herbs; serve with avocado.', 6, 9, 18, 6, 4, 9, 'Intermediate', 6),
('Zesty Chicken Burger', 'Season chicken; grill until golden; serve with side salad.', 4, 25, 31, 2, 5, 1, 'Intermediate', 1),
('Crispy Lentil Toast', 'Simmer lentils with spices; top with yogurt and cilantro.', 8, 13, 12, 5, 4, 3, 'Intermediate', 2),
('Toasty Turkey Wrap', 'Fry tofu until golden; toss with teriyaki sauce and broccoli.', 5, 26, 37, 6, 5, 9, 'Beginner', 9),
('Creamy Tofu Curry', 'Season chicken; grill until golden; serve with side salad.', 3, 16, 28, 6, 2, 6, 'Intermediate', 1),
('Savory Mushroom Skillet', 'Simmer lentils with spices; top with yogurt and cilantro.', 1, 11, 27, 1, 5, 6, 'Beginner', 9),
('Crispy Mushroom Soup', 'Roast vegetables; toss with quinoa and feta; drizzle dressing.', 9, 21, 31, 2, 1, 1, 'Intermediate', 6),
('Spicy Eggplant Pasta', 'Scramble eggs with spinach; wrap in tortilla with salsa.', 7, 8, 41, 1, 1, 8, 'Intermediate', 10),
('Classic Turkey Skillet', 'Grill shrimp with lemon; plate over herbed couscous.', 1, 29, 9, 2, 4, 8, 'Beginner', 1),
('Fusion Chicken Soup', 'Boil pasta; mix with creamy pesto and cherry tomatoes.', 1, 16, 30, 1, 3, 9, 'Beginner', 4),
('Tangy Sweet Potato Wrap', 'Cook rice; stir in beans and herbs; serve with avocado.', 8, 25, 40, 6, 2, 7, 'Intermediate', 1),
('Savory Tofu Bowl', 'Fry tofu until golden; toss with teriyaki sauce and broccoli.', 9, 28, 17, 4, 5, 8, 'Beginner', 9),
('Classic Zucchini Pasta', 'Roast vegetables; toss with quinoa and feta; drizzle dressing.', 10, 13, 11, 1, 5, 3, 'Beginner', 8),
('Zesty Tofu Wrap', 'Sauté mushrooms in garlic butter; serve over polenta.', 6, 6, 25, 6, 5, 6, 'Intermediate', 8),
('Classic Tofu Curry', 'Toast bread; layer with avocado and egg; season and serve.', 7, 5, 2, 3, 1, 2, 'Advanced', 9),
('Loaded Chicken Salad', 'Sauté mushrooms in garlic butter; serve over polenta.', 8, 22, 29, 3, 3, 7, 'Advanced', 3),
('Fusion Egg Tacos', 'Boil pasta; mix with creamy pesto and cherry tomatoes.', 5, 15, 17, 2, 3, 4, 'Advanced', 5),
('Spicy Eggplant Bowl', 'Cook rice; stir in beans and herbs; serve with avocado.', 7, 8, 5, 2, 3, 1, 'Beginner', 5),
('Delight Beef Soup', 'Simmer lentils with spices; top with yogurt and cilantro.', 8, 25, 20, 2, 3, 7, 'Intermediate', 5),
('Savory Zucchini Bowl', 'Cook rice; stir in beans and herbs; serve with avocado.', 2, 9, 33, 2, 5, 9, 'Advanced', 8),
('Hearty Zucchini Toast', 'Simmer lentils with spices; top with yogurt and cilantro.', 1, 29, 30, 6, 1, 4, 'Beginner', 9),
('Hearty Turkey Skillet', 'Simmer lentils with spices; top with yogurt and cilantro.', 6, 8, 32, 5, 2, 5, 'Intermediate', 6),
('Tangy Egg Salad', 'Cook rice; stir in beans and herbs; serve with avocado.', 6, 16, 30, 2, 1, 7, 'Intermediate', 9),
('Creamy Tofu Soup', 'Boil pasta; mix with creamy pesto and cherry tomatoes.', 5, 5, 17, 3, 3, 6, 'Intermediate', 5),
('Hearty Shrimp Pizza', 'Boil pasta; mix with creamy pesto and cherry tomatoes.', 10, 23, 3, 5, 2, 1, 'Beginner', 7),
('Zesty Chicken Soup', 'Season chicken; grill until golden; serve with side salad.', 10, 23, 38, 2, 2, 7, 'Advanced', 8),
('Spicy Lentil Tacos', 'Season chicken; grill until golden; serve with side salad.', 9, 11, 32, 3, 3, 7, 'Advanced', 6),
('Hearty Beef Toast', 'Cook rice; stir in beans and herbs; serve with avocado.', 10, 17, 4, 5, 5, 2, 'Intermediate', 3),
('Delight Tofu Pasta', 'Toast bread; layer with avocado and egg; season and serve.', 10, 6, 25, 2, 3, 2, 'Advanced', 7),
('Zesty Shrimp Pasta', 'Roast vegetables; toss with quinoa and feta; drizzle dressing.', 7, 17, 4, 1, 5, 5, 'Intermediate', 6),
('Toasty Lentil Toast', 'Toast bread; layer with avocado and egg; season and serve.', 10, 20, 13, 4, 5, 4, 'Advanced', 1),
('Zesty Tofu Tacos', 'Fry tofu until golden; toss with teriyaki sauce and broccoli.', 8, 27, 35, 4, 4, 5, 'Intermediate', 4),
('Spicy Egg Pasta', 'Sauté mushrooms in garlic butter; serve over polenta.', 4, 28, 34, 5, 5, 9, 'Advanced', 7),
('Hearty Beef Soup', 'Boil pasta; mix with creamy pesto and cherry tomatoes.', 1, 27, 7, 4, 3, 2, 'Beginner', 4),
('Hearty Mushroom Bowl', 'Roast vegetables; toss with quinoa and feta; drizzle dressing.', 3, 20, 8, 5, 1, 7, 'Beginner', 8),
('Classic Avocado Burger', 'Fry tofu until golden; toss with teriyaki sauce and broccoli.', 8, 29, 22, 5, 1, 6, 'Beginner', 7),
('Hearty Zucchini Wrap', 'Grill shrimp with lemon; plate over herbed couscous.', 4, 17, 14, 3, 3, 9, 'Intermediate', 2),
('Fusion Egg Stir Fry', 'Roast vegetables; toss with quinoa and feta; drizzle dressing.', 5, 6, 11, 3, 1, 7, 'Advanced', 8),
('Toasty Beef Salad', 'Fry tofu until golden; toss with teriyaki sauce and broccoli.', 6, 9, 1, 2, 4, 9, 'Beginner', 4),
('Toasty Eggplant Tacos', 'Roast vegetables; toss with quinoa and feta; drizzle dressing.', 2, 26, 43, 2, 4, 2, 'Advanced', 3),
('Creamy Chicken Pizza', 'Scramble eggs with spinach; wrap in tortilla with salsa.', 7, 13, 15, 5, 3, 8, 'Beginner', 5),
('Fusion Egg Toast', 'Roast vegetables; toss with quinoa and feta; drizzle dressing.', 7, 12, 10, 6, 3, 7, 'Intermediate', 4),
('Savory Sweet Potato Salad', 'Cook rice; stir in beans and herbs; serve with avocado.', 7, 25, 36, 1, 4, 9, 'Beginner', 1),
('Fusion Mushroom Pizza', 'Boil pasta; mix with creamy pesto and cherry tomatoes.', 4, 11, 40, 6, 2, 6, 'Beginner', 10),
('Tangy Lentil Stir Fry', 'Season chicken; grill until golden; serve with side salad.', 9, 28, 21, 6, 4, 8, 'Advanced', 8),
('Fusion Turkey Curry', 'Simmer lentils with spices; top with yogurt and cilantro.', 7, 27, 28, 1, 4, 3, 'Advanced', 8),
('Savory Sweet Potato Wrap', 'Cook rice; stir in beans and herbs; serve with avocado.', 4, 30, 27, 4, 1, 2, 'Beginner', 7),
('Classic Lentil Pasta', 'Fry tofu until golden; toss with teriyaki sauce and broccoli.', 6, 18, 32, 4, 5, 9, 'Advanced', 3),
('Savory Chicken Skillet', 'Scramble eggs with spinach; wrap in tortilla with salsa.', 10, 12, 44, 4, 5, 9, 'Intermediate', 3),
('Delight Egg Wrap', 'Sauté mushrooms in garlic butter; serve over polenta.', 4, 21, 8, 2, 3, 7, 'Beginner', 4),
('Loaded Lentil Pizza', 'Season chicken; grill until golden; serve with side salad.', 7, 11, 40, 2, 4, 7, 'Beginner', 1),
('Hearty Tofu Bowl', 'Toast bread; layer with avocado and egg; season and serve.', 5, 8, 5, 3, 4, 7, 'Beginner', 8),
('Classic Sweet Potato Skillet', 'Scramble eggs with spinach; wrap in tortilla with salsa.', 10, 19, 30, 2, 5, 5, 'Beginner', 4),
('Toasty Chicken Curry', 'Toast bread; layer with avocado and egg; season and serve.', 9, 9, 21, 3, 2, 7, 'Intermediate', 10),
('Fusion Sweet Potato Pasta', 'Season chicken; grill until golden; serve with side salad.', 10, 22, 24, 6, 5, 1, 'Beginner', 8),
('Delight Tofu Curry', 'Boil pasta; mix with creamy pesto and cherry tomatoes.', 9, 15, 4, 3, 4, 7, 'Advanced', 5),
('Crispy Mushroom Skillet', 'Grill shrimp with lemon; plate over herbed couscous.', 4, 14, 4, 4, 1, 3, 'Advanced', 10),
('Savory Sweet Potato Bowl', 'Fry tofu until golden; toss with teriyaki sauce and broccoli.', 5, 27, 33, 3, 2, 4, 'Intermediate', 6),
('Loaded Zucchini Toast', 'Season chicken; grill until golden; serve with side salad.', 4, 20, 5, 1, 4, 7, 'Intermediate', 2),
('Delight Avocado Tacos', 'Toast bread; layer with avocado and egg; season and serve.', 6, 13, 11, 3, 3, 6, 'Advanced', 10),
('Hearty Eggplant Soup', 'Roast vegetables; toss with quinoa and feta; drizzle dressing.', 1, 14, 40, 6, 1, 5, 'Intermediate', 5),
('Spicy Egg Pizza', 'Season chicken; grill until golden; serve with side salad.', 1, 18, 6, 2, 4, 2, 'Advanced', 2),
('Fusion Sweet Potato Salad', 'Boil pasta; mix with creamy pesto and cherry tomatoes.', 4, 21, 35, 2, 1, 3, 'Advanced', 5),
('Tangy Shrimp Salad', 'Sauté mushrooms in garlic butter; serve over polenta.', 9, 29, 6, 3, 1, 9, 'Intermediate', 7),
('Hearty Sweet Potato Wrap', 'Season chicken; grill until golden; serve with side salad.', 2, 5, 33, 3, 1, 7, 'Intermediate', 9),
('Savory Sweet Potato Burger', 'Sauté mushrooms in garlic butter; serve over polenta.', 5, 23, 30, 5, 3, 7, 'Intermediate', 10),
('Tangy Chicken Pizza', 'Cook rice; stir in beans and herbs; serve with avocado.', 2, 19, 41, 3, 3, 1, 'Intermediate', 9),
('Classic Shrimp Toast', 'Simmer lentils with spices; top with yogurt and cilantro.', 5, 21, 0, 1, 2, 7, 'Intermediate', 7),
('Zesty Beef Stir Fry', 'Cook rice; stir in beans and herbs; serve with avocado.', 7, 6, 45, 1, 2, 4, 'Intermediate', 8),
('Savory Shrimp Soup', 'Simmer lentils with spices; top with yogurt and cilantro.', 3, 12, 11, 3, 3, 9, 'Advanced', 10),
('Zesty Tofu Salad', 'Scramble eggs with spinach; wrap in tortilla with salsa.', 2, 9, 41, 4, 5, 3, 'Intermediate', 2),
('Delight Sweet Potato Pizza', 'Fry tofu until golden; toss with teriyaki sauce and broccoli.', 3, 23, 36, 5, 3, 7, 'Advanced', 2),
('Toasty Shrimp Tacos', 'Scramble eggs with spinach; wrap in tortilla with salsa.', 4, 29, 38, 6, 4, 9, 'Advanced', 6),
('Creamy Zucchini Wrap', 'Roast vegetables; toss with quinoa and feta; drizzle dressing.', 3, 15, 45, 5, 2, 4, 'Beginner', 6),
('Hearty Sweet Potato Curry', 'Boil pasta; mix with creamy pesto and cherry tomatoes.', 4, 18, 22, 4, 5, 4, 'Beginner', 6),
('Creamy Zucchini Bowl', 'Grill shrimp with lemon; plate over herbed couscous.', 1, 11, 17, 1, 3, 1, 'Advanced', 10),
('Delight Chicken Wrap', 'Cook rice; stir in beans and herbs; serve with avocado.', 10, 10, 18, 5, 4, 1, 'Advanced', 1),
('Hearty Avocado Soup', 'Grill shrimp with lemon; plate over herbed couscous.', 8, 28, 32, 4, 2, 7, 'Beginner', 7),
('Creamy Zucchini Tacos', 'Scramble eggs with spinach; wrap in tortilla with salsa.', 1, 14, 38, 6, 3, 2, 'Beginner', 4),
('Delight Chicken Wrap', 'Season chicken; grill until golden; serve with side salad.', 3, 6, 20, 4, 5, 2, 'Intermediate', 3),
('Classic Sweet Potato Curry', 'Simmer lentils with spices; top with yogurt and cilantro.', 3, 19, 19, 3, 2, 2, 'Beginner', 9),
('Classic Chicken Soup', 'Cook rice; stir in beans and herbs; serve with avocado.', 8, 7, 37, 1, 1, 5, 'Beginner', 6),
('Hearty Chicken Salad', 'Roast vegetables; toss with quinoa and feta; drizzle dressing.', 2, 11, 0, 4, 4, 1, 'Beginner', 6),
('Creamy Sweet Potato Wrap', 'Roast vegetables; toss with quinoa and feta; drizzle dressing.', 5, 17, 2, 4, 2, 9, 'Advanced', 2),
('Tangy Eggplant Salad', 'Boil pasta; mix with creamy pesto and cherry tomatoes.', 3, 16, 36, 5, 3, 2, 'Intermediate', 3),
('Crispy Avocado Skillet', 'Cook rice; stir in beans and herbs; serve with avocado.', 4, 30, 7, 5, 5, 3, 'Advanced', 6),
('Zesty Beef Curry', 'Roast vegetables; toss with quinoa and feta; drizzle dressing.', 2, 20, 3, 5, 4, 9, 'Intermediate', 3),
('Crispy Chicken Pasta', 'Grill shrimp with lemon; plate over herbed couscous.', 7, 19, 18, 6, 2, 5, 'Advanced', 5),
('Classic Tofu Toast', 'Boil pasta; mix with creamy pesto and cherry tomatoes.', 2, 7, 34, 4, 4, 9, 'Advanced', 6),
('Tangy Tofu Stir Fry', 'Boil pasta; mix with creamy pesto and cherry tomatoes.', 5, 27, 33, 3, 5, 4, 'Intermediate', 3),
('Zesty Mushroom Skillet', 'Cook rice; stir in beans and herbs; serve with avocado.', 9, 28, 5, 1, 3, 8, 'Intermediate', 10),
('Loaded Egg Burger', 'Simmer lentils with spices; top with yogurt and cilantro.', 7, 5, 13, 3, 2, 2, 'Intermediate', 4),
('Toasty Turkey Salad', 'Toast bread; layer with avocado and egg; season and serve.', 3, 21, 6, 5, 3, 6, 'Beginner', 5),
('Delight Beef Salad', 'Season chicken; grill until golden; serve with side salad.', 9, 22, 29, 5, 4, 3, 'Advanced', 4),
('Tangy Avocado Stir Fry', 'Fry tofu until golden; toss with teriyaki sauce and broccoli.', 1, 28, 41, 2, 5, 8, 'Advanced', 7),
('Tangy Beef Wrap', 'Season chicken; grill until golden; serve with side salad.', 8, 26, 26, 3, 4, 1, 'Intermediate', 9),
('Zesty Zucchini Burger', 'Roast vegetables; toss with quinoa and feta; drizzle dressing.', 9, 11, 18, 5, 4, 9, 'Advanced', 1),
('Loaded Lentil Bowl', 'Simmer lentils with spices; top with yogurt and cilantro.', 4, 20, 11, 5, 5, 9, 'Beginner', 7),
('Creamy Eggplant Soup', 'Simmer lentils with spices; top with yogurt and cilantro.', 10, 23, 8, 6, 4, 3, 'Intermediate', 4),
('Loaded Egg Pasta', 'Simmer lentils with spices; top with yogurt and cilantro.', 1, 16, 33, 1, 4, 5, 'Beginner', 10),
('Crispy Egg Salad', 'Roast vegetables; toss with quinoa and feta; drizzle dressing.', 4, 28, 17, 3, 2, 7, 'Beginner', 9),
('Loaded Egg Bowl', 'Toast bread; layer with avocado and egg; season and serve.', 1, 15, 14, 6, 3, 6, 'Intermediate', 2),
('Spicy Sweet Potato Pizza', 'Fry tofu until golden; toss with teriyaki sauce and broccoli.', 7, 5, 43, 1, 5, 7, 'Advanced', 4),
('Spicy Eggplant Tacos', 'Grill shrimp with lemon; plate over herbed couscous.', 9, 16, 33, 1, 1, 8, 'Beginner', 1),
('Delight Mushroom Toast', 'Grill shrimp with lemon; plate over herbed couscous.', 5, 8, 17, 6, 1, 9, 'Beginner', 1),
('Loaded Avocado Pizza', 'Simmer lentils with spices; top with yogurt and cilantro.', 3, 18, 30, 1, 1, 9, 'Advanced', 10),
('Classic Turkey Pasta', 'Toast bread; layer with avocado and egg; season and serve.', 1, 8, 6, 3, 3, 5, 'Beginner', 9),
('Classic Turkey Pizza', 'Season chicken; grill until golden; serve with side salad.', 8, 30, 13, 3, 1, 6, 'Beginner', 3),
('Savory Sweet Potato Bowl', 'Fry tofu until golden; toss with teriyaki sauce and broccoli.', 2, 11, 21, 2, 3, 4, 'Advanced', 6),
('Toasty Sweet Potato Salad', 'Season chicken; grill until golden; serve with side salad.', 6, 21, 20, 2, 1, 4, 'Advanced', 5),
('Creamy Beef Tacos', 'Boil pasta; mix with creamy pesto and cherry tomatoes.', 7, 8, 35, 1, 4, 2, 'Advanced', 2),
('Spicy Zucchini Tacos', 'Toast bread; layer with avocado and egg; season and serve.', 6, 13, 31, 2, 1, 3, 'Intermediate', 1),
('Zesty Chicken Stir Fry', 'Grill shrimp with lemon; plate over herbed couscous.', 2, 18, 10, 6, 4, 2, 'Beginner', 1),
('Loaded Eggplant Soup', 'Sauté mushrooms in garlic butter; serve over polenta.', 8, 17, 45, 4, 2, 5, 'Beginner', 2),
('Toasty Tofu Bowl', 'Cook rice; stir in beans and herbs; serve with avocado.', 2, 27, 42, 3, 2, 9, 'Beginner', 3),
('Fusion Shrimp Stir Fry', 'Cook rice; stir in beans and herbs; serve with avocado.', 9, 18, 24, 3, 3, 3, 'Advanced', 9),
('Savory Zucchini Stir Fry', 'Grill shrimp with lemon; plate over herbed couscous.', 7, 5, 9, 4, 5, 5, 'Advanced', 1),
('Hearty Lentil Toast', 'Toast bread; layer with avocado and egg; season and serve.', 6, 27, 31, 5, 4, 5, 'Beginner', 3),
('Delight Chicken Pizza', 'Toast bread; layer with avocado and egg; season and serve.', 2, 27, 28, 6, 1, 3, 'Intermediate', 5),
('Fusion Chicken Stir Fry', 'Sauté mushrooms in garlic butter; serve over polenta.', 1, 26, 0, 6, 4, 5, 'Beginner', 1),
('Crispy Eggplant Toast', 'Roast vegetables; toss with quinoa and feta; drizzle dressing.', 1, 8, 20, 6, 1, 7, 'Intermediate', 3),
('Crispy Beef Curry', 'Cook rice; stir in beans and herbs; serve with avocado.', 2, 19, 42, 3, 3, 8, 'Beginner', 4),
('Spicy Avocado Pizza', 'Season chicken; grill until golden; serve with side salad.', 5, 16, 15, 5, 1, 6, 'Advanced', 3),
('Tangy Mushroom Salad', 'Season chicken; grill until golden; serve with side salad.', 6, 16, 3, 6, 1, 6, 'Intermediate', 10),
('Toasty Eggplant Wrap', 'Boil pasta; mix with creamy pesto and cherry tomatoes.', 9, 17, 33, 1, 5, 8, 'Intermediate', 4),
('Savory Zucchini Pasta', 'Sauté mushrooms in garlic butter; serve over polenta.', 5, 25, 16, 1, 1, 5, 'Beginner', 10),
('Creamy Beef Toast', 'Grill shrimp with lemon; plate over herbed couscous.', 6, 15, 28, 1, 2, 1, 'Advanced', 5),
('Crispy Mushroom Soup', 'Scramble eggs with spinach; wrap in tortilla with salsa.', 2, 7, 13, 5, 4, 5, 'Beginner', 1),
('Tangy Egg Pasta', 'Fry tofu until golden; toss with teriyaki sauce and broccoli.', 8, 12, 24, 2, 3, 2, 'Intermediate', 2),
('Toasty Sweet Potato Pasta', 'Toast bread; layer with avocado and egg; season and serve.', 1, 18, 42, 1, 2, 8, 'Beginner', 10),
('Spicy Egg Salad', 'Cook rice; stir in beans and herbs; serve with avocado.', 4, 15, 44, 3, 2, 9, 'Beginner', 3),
('Fusion Shrimp Burger', 'Boil pasta; mix with creamy pesto and cherry tomatoes.', 7, 18, 23, 2, 4, 6, 'Advanced', 9),
('Creamy Beef Pizza', 'Simmer lentils with spices; top with yogurt and cilantro.', 10, 7, 11, 4, 4, 8, 'Intermediate', 5),
('Hearty Shrimp Stir Fry', 'Scramble eggs with spinach; wrap in tortilla with salsa.', 5, 29, 22, 3, 5, 5, 'Advanced', 9),
('Savory Avocado Curry', 'Cook rice; stir in beans and herbs; serve with avocado.', 8, 13, 22, 3, 5, 8, 'Intermediate', 8),
('Toasty Sweet Potato Bowl', 'Roast vegetables; toss with quinoa and feta; drizzle dressing.', 6, 5, 2, 4, 4, 6, 'Beginner', 6),
('Fusion Shrimp Pizza', 'Season chicken; grill until golden; serve with side salad.', 5, 13, 6, 5, 5, 6, 'Intermediate', 10),
('Hearty Eggplant Burger', 'Grill shrimp with lemon; plate over herbed couscous.', 1, 9, 38, 2, 1, 9, 'Beginner', 6),
('Savory Turkey Tacos', 'Roast vegetables; toss with quinoa and feta; drizzle dressing.', 3, 28, 18, 5, 5, 7, 'Intermediate', 5),
('Toasty Zucchini Salad', 'Toast bread; layer with avocado and egg; season and serve.', 10, 22, 9, 1, 5, 1, 'Advanced', 6),
('Hearty Egg Toast', 'Fry tofu until golden; toss with teriyaki sauce and broccoli.', 10, 13, 22, 5, 2, 1, 'Advanced', 10),
('Creamy Mushroom Skillet', 'Sauté mushrooms in garlic butter; serve over polenta.', 5, 10, 29, 6, 2, 2, 'Intermediate', 7),
('Creamy Chicken Pasta', 'Simmer lentils with spices; top with yogurt and cilantro.', 8, 26, 30, 4, 1, 1, 'Intermediate', 6),
('Creamy Tofu Soup', 'Simmer lentils with spices; top with yogurt and cilantro.', 7, 9, 18, 5, 3, 8, 'Intermediate', 3),
('Classic Egg Pasta', 'Season chicken; grill until golden; serve with side salad.', 10, 30, 13, 2, 4, 8, 'Beginner', 3),
('Creamy Egg Tacos', 'Grill shrimp with lemon; plate over herbed couscous.', 1, 7, 39, 1, 4, 5, 'Advanced', 9),
('Tangy Turkey Pasta', 'Simmer lentils with spices; top with yogurt and cilantro.', 6, 13, 15, 5, 2, 4, 'Advanced', 10),
('Spicy Shrimp Bowl', 'Toast bread; layer with avocado and egg; season and serve.', 1, 24, 23, 2, 1, 7, 'Advanced', 1),
('Loaded Chicken Skillet', 'Boil pasta; mix with creamy pesto and cherry tomatoes.', 5, 18, 38, 4, 4, 3, 'Advanced', 1),
('Toasty Avocado Skillet', 'Sauté mushrooms in garlic butter; serve over polenta.', 1, 15, 32, 4, 4, 1, 'Beginner', 1),
('Creamy Egg Pizza', 'Roast vegetables; toss with quinoa and feta; drizzle dressing.', 8, 16, 3, 3, 1, 7, 'Intermediate', 8),
('Toasty Sweet Potato Pasta', 'Cook rice; stir in beans and herbs; serve with avocado.', 10, 8, 26, 5, 4, 7, 'Intermediate', 8),
('Classic Egg Soup', 'Toast bread; layer with avocado and egg; season and serve.', 8, 28, 43, 3, 1, 8, 'Advanced', 9),
('Loaded Beef Bowl', 'Simmer lentils with spices; top with yogurt and cilantro.', 7, 15, 17, 3, 4, 6, 'Intermediate', 10),
('Creamy Eggplant Burger', 'Season chicken; grill until golden; serve with side salad.', 2, 19, 22, 1, 3, 3, 'Advanced', 8),
('Savory Lentil Skillet', 'Sauté mushrooms in garlic butter; serve over polenta.', 3, 30, 32, 6, 4, 8, 'Intermediate', 1),
('Savory Shrimp Pasta', 'Boil pasta; mix with creamy pesto and cherry tomatoes.', 6, 12, 25, 3, 4, 5, 'Intermediate', 7),
('Classic Tofu Burger', 'Cook rice; stir in beans and herbs; serve with avocado.', 7, 9, 31, 5, 2, 1, 'Beginner', 4),
('Loaded Lentil Bowl', 'Fry tofu until golden; toss with teriyaki sauce and broccoli.', 8, 19, 30, 2, 4, 3, 'Intermediate', 3),
('Classic Egg Stir Fry', 'Boil pasta; mix with creamy pesto and cherry tomatoes.', 1, 12, 21, 3, 3, 9, 'Beginner', 5),
('Tangy Zucchini Wrap', 'Roast vegetables; toss with quinoa and feta; drizzle dressing.', 10, 24, 12, 1, 3, 6, 'Advanced', 6),
('Toasty Turkey Burger', 'Roast vegetables; toss with quinoa and feta; drizzle dressing.', 1, 28, 14, 3, 3, 5, 'Intermediate', 10),
('Crispy Eggplant Salad', 'Boil pasta; mix with creamy pesto and cherry tomatoes.', 6, 14, 6, 5, 1, 7, 'Advanced', 7),
('Loaded Lentil Burger', 'Fry tofu until golden; toss with teriyaki sauce and broccoli.', 6, 6, 23, 4, 5, 6, 'Beginner', 10),
('Creamy Tofu Tacos', 'Roast vegetables; toss with quinoa and feta; drizzle dressing.', 5, 20, 29, 3, 5, 2, 'Intermediate', 4),
('Creamy Avocado Soup', 'Sauté mushrooms in garlic butter; serve over polenta.', 10, 25, 39, 3, 4, 2, 'Beginner', 9),
('Toasty Mushroom Soup', 'Roast vegetables; toss with quinoa and feta; drizzle dressing.', 6, 30, 7, 5, 3, 3, 'Beginner', 8),
('Spicy Shrimp Tacos', 'Cook rice; stir in beans and herbs; serve with avocado.', 7, 26, 40, 6, 3, 2, 'Advanced', 8),
('Fusion Eggplant Stir Fry', 'Simmer lentils with spices; top with yogurt and cilantro.', 8, 13, 35, 6, 4, 2, 'Intermediate', 2),
('Crispy Mushroom Pizza', 'Simmer lentils with spices; top with yogurt and cilantro.', 1, 5, 2, 5, 1, 3, 'Intermediate', 9),
('Delight Avocado Tacos', 'Simmer lentils with spices; top with yogurt and cilantro.', 10, 22, 41, 3, 1, 4, 'Advanced', 5),
('Creamy Beef Bowl', 'Season chicken; grill until golden; serve with side salad.', 9, 6, 39, 1, 3, 1, 'Beginner', 7),
('Spicy Sweet Potato Bowl', 'Fry tofu until golden; toss with teriyaki sauce and broccoli.', 9, 27, 23, 6, 3, 1, 'Intermediate', 3),
('Spicy Chicken Wrap', 'Grill shrimp with lemon; plate over herbed couscous.', 5, 28, 24, 4, 2, 1, 'Beginner', 6),
('Creamy Egg Wrap', 'Simmer lentils with spices; top with yogurt and cilantro.', 4, 13, 32, 5, 5, 2, 'Intermediate', 7),
('Toasty Egg Salad', 'Boil pasta; mix with creamy pesto and cherry tomatoes.', 4, 25, 23, 3, 4, 5, 'Intermediate', 8),
('Savory Mushroom Pizza', 'Sauté mushrooms in garlic butter; serve over polenta.', 6, 28, 15, 5, 2, 3, 'Advanced', 8),
('Savory Lentil Bowl', 'Season chicken; grill until golden; serve with side salad.', 10, 15, 22, 6, 3, 3, 'Beginner', 2),
('Delight Shrimp Burger', 'Toast bread; layer with avocado and egg; season and serve.', 10, 6, 45, 2, 3, 9, 'Intermediate', 5),
('Toasty Sweet Potato Pasta', 'Fry tofu until golden; toss with teriyaki sauce and broccoli.', 6, 16, 37, 5, 4, 3, 'Beginner', 5),
('Loaded Zucchini Bowl', 'Scramble eggs with spinach; wrap in tortilla with salsa.', 2, 30, 15, 4, 5, 2, 'Beginner', 7),
('Toasty Eggplant Stir Fry', 'Simmer lentils with spices; top with yogurt and cilantro.', 10, 20, 38, 4, 3, 2, 'Beginner', 6),
('Spicy Eggplant Tacos', 'Roast vegetables; toss with quinoa and feta; drizzle dressing.', 9, 20, 19, 2, 4, 4, 'Advanced', 3),
('Creamy Tofu Wrap', 'Toast bread; layer with avocado and egg; season and serve.', 1, 9, 26, 3, 5, 7, 'Intermediate', 9),
('Hearty Sweet Potato Soup', 'Fry tofu until golden; toss with teriyaki sauce and broccoli.', 9, 21, 26, 3, 3, 2, 'Advanced', 10),
('Spicy Mushroom Pizza', 'Toast bread; layer with avocado and egg; season and serve.', 2, 5, 24, 5, 3, 3, 'Beginner', 1),
('Toasty Mushroom Tacos', 'Roast vegetables; toss with quinoa and feta; drizzle dressing.', 4, 16, 40, 2, 4, 4, 'Beginner', 4),
('Savory Chicken Toast', 'Scramble eggs with spinach; wrap in tortilla with salsa.', 7, 21, 14, 4, 1, 1, 'Advanced', 8),
('Hearty Sweet Potato Soup', 'Roast vegetables; toss with quinoa and feta; drizzle dressing.', 1, 30, 35, 1, 1, 4, 'Beginner', 8),
('Classic Sweet Potato Pizza', 'Simmer lentils with spices; top with yogurt and cilantro.', 1, 19, 23, 3, 4, 2, 'Beginner', 10),
('Delight Shrimp Stir Fry', 'Cook rice; stir in beans and herbs; serve with avocado.', 6, 5, 38, 1, 4, 6, 'Advanced', 7),
('Savory Zucchini Pizza', 'Sauté mushrooms in garlic butter; serve over polenta.', 8, 27, 1, 1, 3, 6, 'Advanced', 8),
('Tangy Zucchini Soup', 'Toast bread; layer with avocado and egg; season and serve.', 6, 15, 4, 1, 1, 5, 'Beginner', 5),
('Classic Avocado Pasta', 'Boil pasta; mix with creamy pesto and cherry tomatoes.', 6, 22, 29, 2, 4, 6, 'Intermediate', 7),
('Hearty Sweet Potato Bowl', 'Cook rice; stir in beans and herbs; serve with avocado.', 1, 22, 20, 2, 4, 3, 'Beginner', 8),
('Delight Tofu Pasta', 'Grill shrimp with lemon; plate over herbed couscous.', 8, 24, 16, 4, 4, 3, 'Intermediate', 10),
('Classic Eggplant Stir Fry', 'Fry tofu until golden; toss with teriyaki sauce and broccoli.', 7, 20, 31, 6, 5, 1, 'Advanced', 5),
('Creamy Sweet Potato Curry', 'Simmer lentils with spices; top with yogurt and cilantro.', 3, 21, 8, 3, 3, 7, 'Intermediate', 1),
('Delight Mushroom Tacos', 'Scramble eggs with spinach; wrap in tortilla with salsa.', 1, 28, 4, 1, 4, 4, 'Advanced', 5),
('Delight Zucchini Bowl', 'Boil pasta; mix with creamy pesto and cherry tomatoes.', 7, 9, 15, 6, 5, 2, 'Intermediate', 6),
('Delight Egg Pasta', 'Sauté mushrooms in garlic butter; serve over polenta.', 2, 23, 2, 6, 2, 7, 'Intermediate', 9),
('Fusion Tofu Tacos', 'Boil pasta; mix with creamy pesto and cherry tomatoes.', 6, 29, 8, 3, 4, 8, 'Intermediate', 6),
('Loaded Chicken Stir Fry', 'Scramble eggs with spinach; wrap in tortilla with salsa.', 1, 18, 13, 3, 1, 5, 'Intermediate', 1),
('Spicy Mushroom Pizza', 'Boil pasta; mix with creamy pesto and cherry tomatoes.', 5, 20, 40, 5, 2, 1, 'Intermediate', 7),
('Tangy Zucchini Tacos', 'Season chicken; grill until golden; serve with side salad.', 6, 13, 9, 6, 1, 3, 'Beginner', 9),
('Savory Chicken Toast', 'Scramble eggs with spinach; wrap in tortilla with salsa.', 5, 27, 18, 3, 5, 2, 'Advanced', 8),
('Delight Sweet Potato Toast', 'Sauté mushrooms in garlic butter; serve over polenta.', 8, 29, 45, 2, 2, 8, 'Advanced', 1),
('Hearty Beef Soup', 'Cook rice; stir in beans and herbs; serve with avocado.', 10, 28, 40, 6, 1, 3, 'Advanced', 5),
('Tangy Eggplant Bowl', 'Roast vegetables; toss with quinoa and feta; drizzle dressing.', 2, 18, 13, 3, 4, 4, 'Advanced', 2),
('Loaded Egg Pasta', 'Fry tofu until golden; toss with teriyaki sauce and broccoli.', 5, 30, 18, 4, 3, 9, 'Intermediate', 8),
('Creamy Mushroom Pizza', 'Cook rice; stir in beans and herbs; serve with avocado.', 1, 19, 15, 3, 4, 7, 'Intermediate', 2),
('Loaded Eggplant Wrap', 'Boil pasta; mix with creamy pesto and cherry tomatoes.', 5, 6, 7, 3, 2, 2, 'Intermediate', 7),
('Creamy Lentil Burger', 'Cook rice; stir in beans and herbs; serve with avocado.', 10, 6, 36, 2, 3, 1, 'Intermediate', 5),
('Creamy Egg Pasta', 'Fry tofu until golden; toss with teriyaki sauce and broccoli.', 8, 18, 9, 3, 2, 5, 'Beginner', 10),
('Savory Lentil Burger', 'Sauté mushrooms in garlic butter; serve over polenta.', 1, 8, 6, 5, 3, 7, 'Advanced', 2),
('Tangy Tofu Salad', 'Simmer lentils with spices; top with yogurt and cilantro.', 10, 5, 24, 2, 4, 7, 'Intermediate', 7),
('Fusion Zucchini Stir Fry', 'Roast vegetables; toss with quinoa and feta; drizzle dressing.', 4, 7, 23, 3, 2, 8, 'Intermediate', 3),
('Classic Turkey Skillet', 'Cook rice; stir in beans and herbs; serve with avocado.', 7, 6, 9, 1, 4, 9, 'Advanced', 3),
('Crispy Tofu Curry', 'Roast vegetables; toss with quinoa and feta; drizzle dressing.', 10, 20, 42, 1, 3, 9, 'Intermediate', 9),
('Hearty Tofu Soup', 'Simmer lentils with spices; top with yogurt and cilantro.', 2, 16, 8, 6, 4, 8, 'Beginner', 4),
('Crispy Turkey Curry', 'Toast bread; layer with avocado and egg; season and serve.', 4, 28, 21, 4, 4, 7, 'Beginner', 4),
('Spicy Tofu Toast', 'Sauté mushrooms in garlic butter; serve over polenta.', 6, 13, 36, 3, 3, 1, 'Beginner', 7),
('Savory Beef Pizza', 'Roast vegetables; toss with quinoa and feta; drizzle dressing.', 10, 23, 22, 1, 4, 2, 'Advanced', 2),
('Loaded Mushroom Curry', 'Grill shrimp with lemon; plate over herbed couscous.', 6, 21, 14, 4, 3, 1, 'Beginner', 1),
('Fusion Shrimp Soup', 'Fry tofu until golden; toss with teriyaki sauce and broccoli.', 2, 23, 33, 6, 3, 8, 'Beginner', 3),
('Classic Zucchini Pizza', 'Season chicken; grill until golden; serve with side salad.', 6, 23, 27, 1, 4, 5, 'Intermediate', 5),
('Crispy Zucchini Wrap', 'Season chicken; grill until golden; serve with side salad.', 7, 16, 30, 3, 2, 9, 'Intermediate', 8),
('Toasty Sweet Potato Pizza', 'Sauté mushrooms in garlic butter; serve over polenta.', 9, 14, 28, 2, 4, 4, 'Advanced', 4),
('Toasty Lentil Pizza', 'Fry tofu until golden; toss with teriyaki sauce and broccoli.', 8, 8, 36, 1, 1, 4, 'Intermediate', 6),
('Zesty Zucchini Bowl', 'Cook rice; stir in beans and herbs; serve with avocado.', 8, 26, 22, 6, 4, 5, 'Beginner', 2),
('Hearty Beef Wrap', 'Boil pasta; mix with creamy pesto and cherry tomatoes.', 6, 29, 36, 1, 2, 4, 'Intermediate', 8),
('Hearty Egg Stir Fry', 'Simmer lentils with spices; top with yogurt and cilantro.', 10, 29, 11, 5, 1, 5, 'Advanced', 7),
('Classic Lentil Skillet', 'Scramble eggs with spinach; wrap in tortilla with salsa.', 7, 21, 13, 4, 3, 6, 'Beginner', 2),
('Spicy Eggplant Pizza', 'Roast vegetables; toss with quinoa and feta; drizzle dressing.', 6, 25, 6, 1, 1, 4, 'Beginner', 2),
('Tangy Chicken Soup', 'Fry tofu until golden; toss with teriyaki sauce and broccoli.', 5, 9, 0, 3, 3, 2, 'Advanced', 4),
('Delight Mushroom Curry', 'Season chicken; grill until golden; serve with side salad.', 8, 11, 34, 3, 5, 3, 'Beginner', 5),
('Tangy Chicken Soup', 'Simmer lentils with spices; top with yogurt and cilantro.', 7, 5, 23, 1, 1, 5, 'Advanced', 1),
('Savory Beef Bowl', 'Sauté mushrooms in garlic butter; serve over polenta.', 6, 6, 26, 6, 2, 8, 'Beginner', 9),
('Delight Mushroom Salad', 'Fry tofu until golden; toss with teriyaki sauce and broccoli.', 10, 20, 38, 4, 3, 5, 'Beginner', 8),
('Crispy Eggplant Soup', 'Roast vegetables; toss with quinoa and feta; drizzle dressing.', 1, 13, 8, 3, 3, 2, 'Advanced', 4),
('Delight Sweet Potato Stir Fry', 'Scramble eggs with spinach; wrap in tortilla with salsa.', 9, 29, 15, 3, 1, 5, 'Advanced', 9),
('Spicy Chicken Curry', 'Season chicken; grill until golden; serve with side salad.', 1, 24, 33, 4, 1, 2, 'Advanced', 7),
('Toasty Mushroom Pizza', 'Sauté mushrooms in garlic butter; serve over polenta.', 9, 9, 8, 5, 4, 6, 'Intermediate', 4),
('Savory Sweet Potato Pizza', 'Boil pasta; mix with creamy pesto and cherry tomatoes.', 9, 16, 10, 6, 3, 5, 'Advanced', 3),
('Fusion Sweet Potato Soup', 'Fry tofu until golden; toss with teriyaki sauce and broccoli.', 5, 17, 10, 3, 2, 9, 'Beginner', 3),
('Classic Shrimp Soup', 'Fry tofu until golden; toss with teriyaki sauce and broccoli.', 9, 8, 33, 2, 2, 1, 'Intermediate', 3),
('Spicy Sweet Potato Burger', 'Simmer lentils with spices; top with yogurt and cilantro.', 1, 24, 0, 6, 3, 3, 'Intermediate', 10),
('Fusion Egg Toast', 'Sauté mushrooms in garlic butter; serve over polenta.', 8, 8, 28, 6, 4, 5, 'Intermediate', 6),
('Tangy Avocado Skillet', 'Cook rice; stir in beans and herbs; serve with avocado.', 2, 7, 19, 6, 3, 9, 'Advanced', 3),
('Toasty Lentil Skillet', 'Sauté mushrooms in garlic butter; serve over polenta.', 1, 28, 9, 5, 1, 2, 'Intermediate', 1),
('Classic Chicken Salad', 'Roast vegetables; toss with quinoa and feta; drizzle dressing.', 2, 30, 18, 5, 1, 9, 'Advanced', 5),
('Savory Lentil Stir Fry', 'Toast bread; layer with avocado and egg; season and serve.', 8, 30, 22, 6, 3, 3, 'Intermediate', 2),
('Spicy Shrimp Salad', 'Boil pasta; mix with creamy pesto and cherry tomatoes.', 10, 22, 14, 2, 1, 5, 'Intermediate', 2),
('Tangy Chicken Bowl', 'Roast vegetables; toss with quinoa and feta; drizzle dressing.', 3, 21, 2, 3, 1, 6, 'Beginner', 3),
('Delight Eggplant Salad', 'Season chicken; grill until golden; serve with side salad.', 2, 20, 39, 5, 3, 3, 'Beginner', 10),
('Toasty Avocado Skillet', 'Toast bread; layer with avocado and egg; season and serve.', 8, 21, 24, 1, 4, 1, 'Advanced', 6),
('Toasty Eggplant Stir Fry', 'Sauté mushrooms in garlic butter; serve over polenta.', 1, 7, 14, 2, 1, 4, 'Advanced', 1),
('Classic Zucchini Soup', 'Sauté mushrooms in garlic butter; serve over polenta.', 5, 9, 44, 1, 2, 8, 'Beginner', 2),
('Savory Egg Salad', 'Boil pasta; mix with creamy pesto and cherry tomatoes.', 4, 11, 20, 4, 5, 7, 'Intermediate', 10),
('Savory Eggplant Bowl', 'Scramble eggs with spinach; wrap in tortilla with salsa.', 1, 18, 33, 1, 1, 3, 'Beginner', 7),
('Tangy Tofu Salad', 'Boil pasta; mix with creamy pesto and cherry tomatoes.', 3, 18, 18, 3, 2, 9, 'Intermediate', 10),
('Loaded Mushroom Pizza', 'Scramble eggs with spinach; wrap in tortilla with salsa.', 9, 5, 44, 1, 5, 7, 'Advanced', 2),
('Toasty Sweet Potato Skillet', 'Grill shrimp with lemon; plate over herbed couscous.', 4, 7, 0, 6, 1, 9, 'Beginner', 7),
('Toasty Zucchini Burger', 'Roast vegetables; toss with quinoa and feta; drizzle dressing.', 8, 24, 27, 5, 1, 7, 'Beginner', 2),
('Zesty Zucchini Burger', 'Fry tofu until golden; toss with teriyaki sauce and broccoli.', 1, 5, 45, 6, 5, 5, 'Beginner', 7),
('Classic Shrimp Pasta', 'Fry tofu until golden; toss with teriyaki sauce and broccoli.', 3, 7, 34, 1, 3, 7, 'Beginner', 6),
('Toasty Mushroom Burger', 'Roast vegetables; toss with quinoa and feta; drizzle dressing.', 10, 9, 18, 6, 2, 6, 'Beginner', 9),
('Classic Egg Burger', 'Season chicken; grill until golden; serve with side salad.', 2, 21, 41, 3, 4, 8, 'Beginner', 4),
('Classic Avocado Stir Fry', 'Scramble eggs with spinach; wrap in tortilla with salsa.', 9, 24, 35, 4, 3, 6, 'Intermediate', 4),
('Delight Egg Toast', 'Roast vegetables; toss with quinoa and feta; drizzle dressing.', 7, 7, 32, 1, 2, 3, 'Beginner', 9),
('Toasty Turkey Soup', 'Toast bread; layer with avocado and egg; season and serve.', 3, 5, 10, 1, 3, 9, 'Advanced', 1),
('Classic Egg Toast', 'Sauté mushrooms in garlic butter; serve over polenta.', 2, 21, 19, 1, 3, 1, 'Intermediate', 3),
('Toasty Chicken Stir Fry', 'Roast vegetables; toss with quinoa and feta; drizzle dressing.', 7, 14, 34, 1, 5, 2, 'Intermediate', 1),
('Spicy Avocado Curry', 'Boil pasta; mix with creamy pesto and cherry tomatoes.', 4, 28, 24, 6, 4, 8, 'Advanced', 7),
('Delight Tofu Pasta', 'Grill shrimp with lemon; plate over herbed couscous.', 3, 13, 4, 3, 3, 8, 'Beginner', 10),
('Classic Egg Pasta', 'Simmer lentils with spices; top with yogurt and cilantro.', 6, 20, 31, 2, 5, 5, 'Advanced', 9),
('Toasty Turkey Pizza', 'Toast bread; layer with avocado and egg; season and serve.', 9, 23, 44, 5, 4, 1, 'Beginner', 8),
('Zesty Chicken Burger', 'Sauté mushrooms in garlic butter; serve over polenta.', 9, 26, 41, 5, 2, 5, 'Advanced', 5),
('Creamy Lentil Pasta', 'Cook rice; stir in beans and herbs; serve with avocado.', 4, 17, 37, 5, 4, 5, 'Beginner', 9),
('Zesty Tofu Burger', 'Boil pasta; mix with creamy pesto and cherry tomatoes.', 7, 9, 27, 5, 1, 5, 'Beginner', 4),
('Savory Avocado Skillet', 'Boil pasta; mix with creamy pesto and cherry tomatoes.', 6, 20, 26, 3, 5, 2, 'Beginner', 3),
('Fusion Sweet Potato Wrap', 'Boil pasta; mix with creamy pesto and cherry tomatoes.', 9, 8, 3, 4, 2, 1, 'Advanced', 5),
('Spicy Beef Salad', 'Scramble eggs with spinach; wrap in tortilla with salsa.', 9, 11, 28, 4, 1, 3, 'Beginner', 6),
('Delight Avocado Soup', 'Simmer lentils with spices; top with yogurt and cilantro.', 7, 25, 6, 3, 1, 8, 'Advanced', 1),
('Classic Sweet Potato Stir Fry', 'Scramble eggs with spinach; wrap in tortilla with salsa.', 2, 27, 42, 1, 4, 3, 'Intermediate', 6),
('Toasty Egg Burger', 'Cook rice; stir in beans and herbs; serve with avocado.', 9, 25, 6, 6, 1, 1, 'Advanced', 4),
('Creamy Avocado Bowl', 'Sauté mushrooms in garlic butter; serve over polenta.', 1, 29, 1, 1, 1, 2, 'Advanced', 10),
('Tangy Avocado Stir Fry', 'Simmer lentils with spices; top with yogurt and cilantro.', 9, 22, 19, 4, 5, 5, 'Beginner', 7),
('Tangy Beef Salad', 'Grill shrimp with lemon; plate over herbed couscous.', 6, 11, 12, 1, 3, 1, 'Advanced', 7),
('Toasty Tofu Pizza', 'Boil pasta; mix with creamy pesto and cherry tomatoes.', 1, 12, 14, 5, 1, 3, 'Beginner', 1),
('Classic Eggplant Curry', 'Boil pasta; mix with creamy pesto and cherry tomatoes.', 4, 17, 41, 6, 1, 1, 'Beginner', 6),
('Crispy Eggplant Burger', 'Fry tofu until golden; toss with teriyaki sauce and broccoli.', 3, 21, 2, 5, 5, 9, 'Advanced', 2),
('Toasty Mushroom Wrap', 'Roast vegetables; toss with quinoa and feta; drizzle dressing.', 7, 10, 0, 3, 3, 5, 'Advanced', 5),
('Loaded Turkey Wrap', 'Boil pasta; mix with creamy pesto and cherry tomatoes.', 1, 19, 31, 6, 5, 3, 'Advanced', 3),
('Spicy Lentil Bowl', 'Roast vegetables; toss with quinoa and feta; drizzle dressing.', 10, 12, 17, 2, 1, 1, 'Advanced', 10),
('Hearty Beef Toast', 'Toast bread; layer with avocado and egg; season and serve.', 9, 12, 27, 6, 1, 7, 'Advanced', 7),
('Loaded Chicken Curry', 'Simmer lentils with spices; top with yogurt and cilantro.', 5, 14, 26, 6, 5, 4, 'Advanced', 8),
('Toasty Zucchini Toast', 'Grill shrimp with lemon; plate over herbed couscous.', 2, 16, 9, 6, 5, 3, 'Advanced', 3),
('Creamy Shrimp Soup', 'Grill shrimp with lemon; plate over herbed couscous.', 4, 9, 30, 6, 5, 2, 'Intermediate', 1),
('Classic Tofu Bowl', 'Roast vegetables; toss with quinoa and feta; drizzle dressing.', 4, 7, 5, 2, 5, 2, 'Beginner', 4),
('Tangy Sweet Potato Pasta', 'Sauté mushrooms in garlic butter; serve over polenta.', 10, 25, 34, 2, 2, 2, 'Intermediate', 2),
('Crispy Eggplant Wrap', 'Boil pasta; mix with creamy pesto and cherry tomatoes.', 9, 18, 13, 2, 3, 5, 'Advanced', 9),
('Hearty Avocado Wrap', 'Cook rice; stir in beans and herbs; serve with avocado.', 10, 23, 4, 5, 1, 7, 'Beginner', 7),
('Creamy Tofu Pasta', 'Simmer lentils with spices; top with yogurt and cilantro.', 2, 9, 14, 3, 1, 4, 'Intermediate', 5),
('Classic Egg Soup', 'Roast vegetables; toss with quinoa and feta; drizzle dressing.', 5, 15, 28, 5, 3, 6, 'Advanced', 9),
('Savory Egg Toast', 'Cook rice; stir in beans and herbs; serve with avocado.', 9, 20, 39, 2, 5, 5, 'Beginner', 2),
('Loaded Lentil Soup', 'Toast bread; layer with avocado and egg; season and serve.', 9, 25, 28, 2, 1, 3, 'Intermediate', 4),
('Delight Zucchini Stir Fry', 'Season chicken; grill until golden; serve with side salad.', 9, 25, 14, 1, 5, 2, 'Advanced', 5),
('Loaded Egg Toast', 'Boil pasta; mix with creamy pesto and cherry tomatoes.', 2, 14, 29, 4, 4, 7, 'Beginner', 7),
('Creamy Chicken Salad', 'Simmer lentils with spices; top with yogurt and cilantro.', 7, 28, 20, 1, 2, 8, 'Intermediate', 4),
('Crispy Egg Pizza', 'Season chicken; grill until golden; serve with side salad.', 7, 10, 44, 5, 3, 1, 'Beginner', 4),
('Crispy Shrimp Wrap', 'Sauté mushrooms in garlic butter; serve over polenta.', 5, 22, 19, 2, 5, 3, 'Advanced', 4),
('Creamy Mushroom Salad', 'Simmer lentils with spices; top with yogurt and cilantro.', 1, 25, 14, 2, 2, 5, 'Advanced', 6),
('Creamy Shrimp Wrap', 'Simmer lentils with spices; top with yogurt and cilantro.', 1, 6, 31, 5, 1, 2, 'Beginner', 6),
('Zesty Avocado Curry', 'Simmer lentils with spices; top with yogurt and cilantro.', 6, 6, 42, 2, 2, 1, 'Intermediate', 6),
('Hearty Egg Salad', 'Scramble eggs with spinach; wrap in tortilla with salsa.', 4, 13, 40, 6, 1, 9, 'Beginner', 5),
('Savory Turkey Salad', 'Cook rice; stir in beans and herbs; serve with avocado.', 7, 30, 32, 3, 1, 2, 'Intermediate', 3),
('Delight Zucchini Pasta', 'Cook rice; stir in beans and herbs; serve with avocado.', 4, 12, 30, 6, 3, 7, 'Intermediate', 2),
('Zesty Egg Toast', 'Fry tofu until golden; toss with teriyaki sauce and broccoli.', 7, 22, 12, 2, 2, 9, 'Advanced', 10),
('Toasty Shrimp Salad', 'Cook rice; stir in beans and herbs; serve with avocado.', 3, 18, 30, 6, 5, 9, 'Intermediate', 6),
('Loaded Turkey Curry', 'Sauté mushrooms in garlic butter; serve over polenta.', 7, 5, 22, 2, 4, 2, 'Intermediate', 3),
('Hearty Turkey Skillet', 'Grill shrimp with lemon; plate over herbed couscous.', 1, 18, 21, 3, 1, 9, 'Beginner', 5),
('Toasty Beef Wrap', 'Sauté mushrooms in garlic butter; serve over polenta.', 2, 5, 3, 3, 2, 8, 'Beginner', 3),
('Loaded Beef Bowl', 'Boil pasta; mix with creamy pesto and cherry tomatoes.', 1, 21, 10, 1, 4, 7, 'Intermediate', 7),
('Delight Avocado Soup', 'Scramble eggs with spinach; wrap in tortilla with salsa.', 5, 23, 30, 3, 2, 4, 'Intermediate', 6),
('Loaded Egg Soup', 'Season chicken; grill until golden; serve with side salad.', 2, 9, 27, 3, 2, 6, 'Intermediate', 10),
('Crispy Lentil Burger', 'Simmer lentils with spices; top with yogurt and cilantro.', 7, 6, 44, 5, 5, 9, 'Beginner', 3),
('Zesty Shrimp Burger', 'Roast vegetables; toss with quinoa and feta; drizzle dressing.', 9, 8, 10, 1, 3, 5, 'Beginner', 2),
('Hearty Beef Tacos', 'Boil pasta; mix with creamy pesto and cherry tomatoes.', 6, 16, 24, 1, 2, 4, 'Beginner', 2),
('Toasty Mushroom Salad', 'Grill shrimp with lemon; plate over herbed couscous.', 1, 10, 4, 5, 5, 9, 'Beginner', 4),
('Delight Chicken Wrap', 'Boil pasta; mix with creamy pesto and cherry tomatoes.', 4, 27, 36, 3, 4, 3, 'Advanced', 5);
