INSERT INTO category (categoryName, categoryImageUrl) VALUES 
('Breakfast', '/images/categories/breakfast-60x60.png'),
('Lunch', '/images/categories/lunch-60x60.png'),
('Dinner', '/images/categories/dinner-60x60.png'),
('Desserts', '/images/categories/desserts-60x60.png');

-- Insert common diet types
INSERT INTO diet (dietName, dietDescription) VALUES
('Vegetarian', 'No meat, fish, or poultry'),
('Vegan', 'No animal products'),
('Gluten-Free', 'No gluten-containing ingredients'),
('Keto', 'Low-carb, high-fat diet'),
('Paleo', 'Based on foods presumed eaten during the Paleolithic era'),
('Pescatarian', 'Vegetarian diet that includes fish'),
('Dairy-Free', 'No dairy products'),
('Low-Carb', 'Reduced carbohydrate intake'),
('None', 'No specific dietary restrictions');

-- Insert cuisine types
INSERT INTO cuisine (cuisineName, cuisineDescription) VALUES 
('Italian', 'Traditional Italian dishes including pasta, pizza, and Mediterranean flavors'),
('Chinese', 'Various regional Chinese cuisines featuring stir-fries, noodles, and rice dishes'),
('Mexican', 'Traditional Mexican dishes with tortillas, beans, and diverse spices'),
('Indian', 'Rich and diverse Indian cuisine with curries, tandoor dishes, and flatbreads'),
('Japanese', 'Japanese cuisine featuring sushi, noodles, and traditional dishes'),
('Thai', 'Thai dishes with sweet, sour, and spicy flavors'),
('Mediterranean', 'Healthy Mediterranean diet with olive oil, fresh vegetables, and seafood'),
('American', 'Classic American comfort food and regional specialties'),
('French', 'Elegant French cuisine with rich sauces and sophisticated techniques'),
('Korean', 'Korean dishes featuring kimchi, barbecue, and rice-based meals'),
('Vietnamese', 'Fresh Vietnamese cuisine with herbs and light preparations'),
('Middle Eastern', 'Middle Eastern fare with kebabs, hummus, and aromatic spices'),
('Greek', 'Traditional Greek dishes with olives, feta, and Mediterranean herbs'),
('Spanish', 'Spanish cuisine featuring paella, tapas, and seafood dishes');

-- Insert into recipe
INSERT INTO recipe (recipeName, description, userId, categoryId, prep_time, cook_time, servings, cuisineId, dietId, cookingLevel) VALUES
('Savory Vegetable Stir Fry Delight', 'Spicy and satisfying dish.', 8, 3, 23, 58, 5, 4, 1, 'Easy'),
('Zesty Tofu Stir Fry Skillet', 'Healthy and flavorful meal.', 8, 5, 7, 52, 1, 5, 2, 'Intermediate'),
('Hearty Tofu Stir Fry Medley', 'Low-carb, high-protein recipe.', 10, 2, 6, 17, 2, 5, 3, 'Advanced'),
('Hearty Lentil Soup Fusion', 'Light yet filling meal.', 7, 4, 22, 48, 7, 3, 3, 'Intermediate'),
('Tangy Tofu Stir Fry Special', 'Spicy and satisfying dish.', 6, 2, 22, 14, 6, 1, 2, 'Intermediate'),
('Low-Carb Beef Tacos Medley', 'Perfect for meal prepping.', 4, 5, 19, 45, 6, 3, 2, 'Advanced'),
('Classic Grilled Chicken Salad and Chickpeas', 'Quick weeknight dinner idea.', 2, 1, 29, 12, 1, 3, 3, 'Easy'),
('Simple Spaghetti Bolognese Bake', 'Quick weeknight dinner idea.', 9, 5, 16, 39, 2, 1, 5, 'Advanced'),
('Low-Carb Vegetable Stir Fry Surprise', 'Comfort food with a twist.', 2, 1, 23, 29, 3, 5, 5, 'Easy'),
('Creamy Beef Tacos and Chickpeas', 'Spicy and satisfying dish.', 5, 5, 19, 46, 8, 5, 2, 'Advanced'),
('Tangy Grilled Chicken Salad with Rice', 'Great for family gatherings.', 6, 5, 21, 50, 1, 2, 5, 'Easy'),
('Creamy Grilled Chicken Salad Skillet', 'Low-carb, high-protein recipe.', 5, 5, 20, 52, 1, 3, 1, 'Advanced'),
('Vegan Spaghetti Bolognese with Cheese', 'Spicy and satisfying dish.', 8, 1, 14, 14, 5, 2, 3, 'Intermediate'),
('Fresh Chicken Curry Fusion', 'Quick weeknight dinner idea.', 6, 3, 25, 30, 1, 4, 3, 'Easy'),
('Classic Tofu Stir Fry Special', 'Comfort food with a twist.', 5, 5, 8, 13, 6, 1, 4, 'Easy'),
('Smoky Shrimp Alfredo Medley', 'Low-carb, high-protein recipe.', 9, 1, 27, 39, 4, 5, 3, 'Intermediate'),
('Hearty Lentil Soup Skillet', 'A delicious and easy dish to prepare.', 5, 1, 16, 57, 4, 2, 1, 'Easy'),
('Classic Grilled Chicken Salad Bake', 'Light yet filling meal.', 3, 5, 26, 38, 4, 3, 1, 'Easy'),
('Savory Spaghetti Bolognese with Rice', 'Spicy and satisfying dish.', 5, 2, 26, 29, 3, 1, 4, 'Intermediate'),
('Smoky Grilled Chicken Salad Fiesta', 'A delicious and easy dish to prepare.', 7, 4, 27, 50, 2, 3, 4, 'Easy'),
('Simple Quinoa Bowl Fiesta', 'A delicious and easy dish to prepare.', 10, 5, 25, 42, 5, 4, 2, 'Advanced'),
('Crunchy Tofu Stir Fry and Chickpeas', 'Light yet filling meal.', 10, 1, 26, 47, 4, 5, 3, 'Advanced'),
('Hearty Quinoa Bowl with Rice', 'A delicious and easy dish to prepare.', 5, 1, 5, 51, 7, 3, 2, 'Advanced'),
('Zesty Spaghetti Bolognese with Basil', 'Perfect for meal prepping.', 10, 3, 30, 40, 6, 5, 4, 'Intermediate'),
('Spicy Grilled Chicken Salad Special', 'Spicy and satisfying dish.', 10, 5, 8, 45, 7, 5, 1, 'Advanced'),
('Zesty Quinoa Bowl and Chickpeas', 'Quick weeknight dinner idea.', 3, 3, 28, 51, 8, 3, 1, 'Advanced'),
('Fresh Quinoa Bowl Special', 'A delicious and easy dish to prepare.', 10, 4, 19, 37, 8, 3, 2, 'Advanced'),
('Tangy Chicken Curry Bake', 'Perfect for meal prepping.', 2, 5, 17, 28, 4, 4, 2, 'Intermediate'),
('Spicy Chicken Curry Wraps', 'Light yet filling meal.', 10, 3, 8, 22, 1, 4, 2, 'Easy'),
('Smoky Beef Tacos Delight', 'Quick weeknight dinner idea.', 10, 1, 21, 23, 6, 5, 5, 'Intermediate'),
('Hearty Tofu Stir Fry Wraps', 'Light yet filling meal.', 6, 2, 28, 19, 1, 4, 5, 'Intermediate'),
('Spicy Pasta Primavera with Rice', 'Healthy and flavorful meal.', 6, 2, 13, 51, 5, 2, 2, 'Intermediate'),
('Low-Carb Shrimp Alfredo Medley', 'Light yet filling meal.', 8, 4, 20, 47, 2, 4, 5, 'Easy'),
('Savory Shrimp Alfredo Medley', 'Healthy and flavorful meal.', 4, 3, 8, 21, 5, 4, 5, 'Easy'),
('Spicy Lentil Soup and Chickpeas', 'A delicious and easy dish to prepare.', 10, 1, 27, 59, 2, 4, 2, 'Advanced'),
('Gluten-Free Quinoa Bowl with Rice', 'Perfect for meal prepping.', 7, 5, 28, 37, 4, 1, 4, 'Advanced'),
('Simple Vegetable Stir Fry and Chickpeas', 'Healthy and flavorful meal.', 2, 1, 21, 35, 3, 1, 3, 'Easy'),
('Low-Carb Grilled Chicken Salad with Cheese', 'A delicious and easy dish to prepare.', 3, 2, 5, 40, 5, 4, 2, 'Advanced'),
('Classic Spaghetti Bolognese and Chickpeas', 'Comfort food with a twist.', 9, 4, 30, 57, 8, 1, 3, 'Intermediate'),
('Crunchy Pasta Primavera Surprise', 'Spicy and satisfying dish.', 2, 3, 30, 33, 8, 2, 3, 'Intermediate'),
('Fresh Chicken Curry Surprise', 'Perfect for meal prepping.', 5, 3, 20, 39, 1, 3, 3, 'Advanced'),
('Simple Grilled Chicken Salad Fusion', 'Spicy and satisfying dish.', 5, 5, 6, 56, 8, 5, 4, 'Easy'),
('Crunchy Vegetable Stir Fry Delight', 'A delicious and easy dish to prepare.', 9, 4, 6, 21, 6, 4, 5, 'Advanced'),
('Creamy Pasta Primavera Wraps', 'Perfect for meal prepping.', 6, 3, 22, 54, 3, 1, 1, 'Easy'),
('Crunchy Spaghetti Bolognese Skillet', 'A delicious and easy dish to prepare.', 7, 2, 12, 23, 7, 3, 1, 'Intermediate'),
('Simple Grilled Chicken Salad Wraps', 'Healthy and flavorful meal.', 4, 2, 6, 55, 3, 2, 5, 'Easy'),
('Vegan Shrimp Alfredo with Basil', 'A delicious and easy dish to prepare.', 1, 1, 25, 25, 7, 4, 1, 'Easy'),
('Fresh Spaghetti Bolognese Toppers', 'Comfort food with a twist.', 6, 5, 12, 49, 6, 2, 4, 'Advanced'),
('Vegan Vegetable Stir Fry Fusion', 'Quick weeknight dinner idea.', 3, 4, 26, 18, 4, 2, 5, 'Intermediate'),
('Fresh Pasta Primavera Fusion', 'Low-carb, high-protein recipe.', 3, 5, 10, 52, 6, 4, 1, 'Easy'),
('Gluten-Free Tofu Stir Fry Fiesta', 'Spicy and satisfying dish.', 7, 2, 5, 56, 6, 5, 4, 'Easy'),
('Spicy Spaghetti Bolognese with Cheese', 'Quick weeknight dinner idea.', 10, 1, 15, 11, 3, 4, 2, 'Easy'),
('Vegan Grilled Chicken Salad Bake', 'Quick weeknight dinner idea.', 6, 2, 30, 15, 4, 5, 5, 'Intermediate'),
('Zesty Vegetable Stir Fry Fusion', 'Low-carb, high-protein recipe.', 1, 2, 14, 17, 8, 1, 2, 'Easy'),
('Low-Carb Pasta Primavera with Rice', 'Classic recipe loved by all.', 6, 2, 5, 35, 6, 1, 4, 'Easy'),
('Tangy Chicken Curry Special', 'Perfect for meal prepping.', 5, 4, 26, 41, 5, 5, 5, 'Easy'),
('Hearty Lentil Soup with Basil', 'Low-carb, high-protein recipe.', 2, 1, 16, 18, 6, 1, 5, 'Intermediate'),
('Low-Carb Vegetable Stir Fry Medley', 'A delicious and easy dish to prepare.', 7, 2, 27, 25, 6, 3, 4, 'Advanced'),
('Vegan Tofu Stir Fry Medley', 'Light yet filling meal.', 4, 5, 29, 28, 1, 2, 1, 'Intermediate'),
('Tangy Spaghetti Bolognese with Rice', 'Classic recipe loved by all.', 10, 5, 29, 31, 8, 2, 5, 'Advanced'),
('Simple Lentil Soup with Cheese', 'Great for family gatherings.', 8, 3, 19, 31, 5, 1, 3, 'Easy'),
('Low-Carb Lentil Soup Wraps', 'Comfort food with a twist.', 3, 1, 5, 14, 2, 5, 3, 'Easy'),
('Hearty Quinoa Bowl Surprise', 'Classic recipe loved by all.', 2, 5, 14, 11, 1, 2, 1, 'Intermediate'),
('Zesty Vegetable Stir Fry Skillet', 'Spicy and satisfying dish.', 1, 1, 29, 37, 6, 2, 5, 'Advanced'),
('Creamy Vegetable Stir Fry Fiesta', 'Perfect for meal prepping.', 4, 3, 12, 59, 8, 2, 3, 'Easy'),
('Vegan Spaghetti Bolognese Skillet', 'Perfect for meal prepping.', 7, 2, 5, 21, 6, 1, 2, 'Advanced'),
('Hearty Shrimp Alfredo Delight', 'Perfect for meal prepping.', 3, 1, 14, 30, 8, 4, 1, 'Easy'),
('Vegan Chicken Curry Skillet', 'Perfect for meal prepping.', 5, 5, 11, 59, 1, 5, 4, 'Advanced'),
('Low-Carb Chicken Curry with Basil', 'Classic recipe loved by all.', 1, 1, 27, 39, 3, 2, 1, 'Easy'),
('Crunchy Lentil Soup Surprise', 'Spicy and satisfying dish.', 3, 4, 5, 17, 6, 1, 5, 'Advanced'),
('Gluten-Free Lentil Soup Fusion', 'Low-carb, high-protein recipe.', 10, 5, 30, 43, 7, 1, 4, 'Advanced'),
('Crunchy Lentil Soup Delight', 'Comfort food with a twist.', 1, 1, 22, 58, 2, 5, 4, 'Intermediate'),
('Zesty Lentil Soup Fusion', 'Classic recipe loved by all.', 8, 1, 29, 59, 8, 2, 1, 'Intermediate'),
('Crunchy Quinoa Bowl Surprise', 'A delicious and easy dish to prepare.', 5, 2, 28, 44, 5, 5, 2, 'Easy'),
('Simple Chicken Curry Delight', 'Light yet filling meal.', 8, 4, 28, 46, 3, 3, 4, 'Intermediate'),
('Zesty Chicken Curry Delight', 'Spicy and satisfying dish.', 9, 3, 22, 53, 3, 2, 1, 'Advanced'),
('Vegan Spaghetti Bolognese Fusion', 'Healthy and flavorful meal.', 8, 1, 16, 57, 7, 5, 4, 'Intermediate'),
('Gluten-Free Chicken Curry Skillet', 'Low-carb, high-protein recipe.', 8, 4, 22, 47, 3, 1, 5, 'Advanced'),
('Tangy Lentil Soup Medley', 'Comfort food with a twist.', 10, 3, 22, 46, 7, 5, 4, 'Advanced'),
('Low-Carb Pasta Primavera Surprise', 'Light yet filling meal.', 6, 4, 12, 41, 6, 3, 2, 'Advanced'),
('Low-Carb Beef Tacos with Cheese', 'Great for family gatherings.', 6, 5, 24, 17, 4, 4, 4, 'Easy'),
('Spicy Vegetable Stir Fry Bake', 'Light yet filling meal.', 8, 1, 7, 28, 8, 1, 5, 'Advanced'),
('Tangy Shrimp Alfredo Fusion', 'Light yet filling meal.', 5, 3, 25, 55, 3, 3, 5, 'Advanced'),
('Savory Shrimp Alfredo Wraps', 'Great for family gatherings.', 3, 3, 12, 29, 1, 4, 2, 'Advanced'),
('Simple Lentil Soup Wraps', 'Classic recipe loved by all.', 6, 1, 14, 54, 1, 4, 2, 'Easy'),
('Smoky Beef Tacos and Chickpeas', 'Quick weeknight dinner idea.', 6, 2, 8, 51, 8, 4, 1, 'Intermediate'),
('Savory Quinoa Bowl Surprise', 'Healthy and flavorful meal.', 5, 4, 27, 34, 2, 5, 5, 'Easy'),
('Simple Chicken Curry Surprise', 'Classic recipe loved by all.', 1, 4, 11, 37, 7, 2, 1, 'Advanced'),
('Hearty Pasta Primavera Fusion', 'Light yet filling meal.', 10, 5, 25, 21, 6, 5, 4, 'Intermediate'),
('Vegan Shrimp Alfredo Wraps', 'Healthy and flavorful meal.', 2, 1, 15, 33, 5, 2, 3, 'Easy'),
('Tangy Grilled Chicken Salad with Cheese', 'A delicious and easy dish to prepare.', 10, 3, 30, 48, 6, 5, 2, 'Intermediate'),
('Tangy Chicken Curry with Cheese', 'Perfect for meal prepping.', 5, 5, 22, 31, 5, 5, 1, 'Advanced'),
('Crunchy Grilled Chicken Salad Special', 'Spicy and satisfying dish.', 1, 5, 14, 37, 2, 3, 4, 'Advanced'),
('Low-Carb Spaghetti Bolognese with Cheese', 'Quick weeknight dinner idea.', 3, 5, 13, 60, 4, 1, 3, 'Easy'),
('Spicy Spaghetti Bolognese and Chickpeas', 'Low-carb, high-protein recipe.', 10, 1, 22, 45, 3, 2, 1, 'Easy'),
('Hearty Pasta Primavera Medley', 'Comfort food with a twist.', 6, 2, 9, 56, 3, 1, 1, 'Intermediate'),
('Fresh Beef Tacos Bake', 'Light yet filling meal.', 10, 5, 11, 49, 6, 3, 1, 'Advanced'),
('Savory Quinoa Bowl with Cheese', 'Quick weeknight dinner idea.', 1, 2, 6, 51, 7, 4, 2, 'Easy'),
('Gluten-Free Vegetable Stir Fry Toppers', 'Healthy and flavorful meal.', 1, 5, 30, 11, 1, 3, 5, 'Intermediate'),
('Hearty Grilled Chicken Salad Skillet', 'Perfect for meal prepping.', 5, 1, 14, 19, 1, 3, 3, 'Advanced'),
('Creamy Lentil Soup with Rice', 'Light yet filling meal.', 5, 5, 28, 20, 2, 3, 2, 'Advanced'),
('Fresh Chicken Curry and Chickpeas', 'Healthy and flavorful meal.', 10, 1, 10, 15, 8, 1, 2, 'Easy'),
('Hearty Lentil Soup with Rice', 'Comfort food with a twist.', 5, 5, 24, 40, 4, 4, 4, 'Advanced'),
('Low-Carb Spaghetti Bolognese Medley', 'Light yet filling meal.', 8, 1, 21, 45, 8, 4, 5, 'Advanced'),
('Fresh Tofu Stir Fry Delight', 'Perfect for meal prepping.', 4, 1, 8, 29, 2, 2, 1, 'Advanced'),
('Vegan Beef Tacos with Basil', 'Light yet filling meal.', 8, 1, 21, 47, 4, 4, 5, 'Intermediate'),
('Fresh Spaghetti Bolognese and Chickpeas', 'Spicy and satisfying dish.', 8, 1, 14, 47, 2, 5, 2, 'Advanced'),
('Vegan Quinoa Bowl Delight', 'Spicy and satisfying dish.', 4, 3, 18, 33, 6, 3, 1, 'Easy'),
('Fresh Vegetable Stir Fry Wraps', 'Spicy and satisfying dish.', 6, 4, 20, 34, 5, 5, 1, 'Easy'),
('Vegan Chicken Curry and Chickpeas', 'Perfect for meal prepping.', 7, 4, 10, 16, 3, 4, 3, 'Easy'),
('Simple Shrimp Alfredo Bake', 'Comfort food with a twist.', 2, 2, 7, 10, 8, 3, 4, 'Advanced'),
('Smoky Beef Tacos Fiesta', 'Comfort food with a twist.', 1, 2, 19, 56, 6, 1, 2, 'Easy'),
('Hearty Vegetable Stir Fry Toppers', 'A delicious and easy dish to prepare.', 2, 5, 17, 51, 7, 4, 5, 'Intermediate'),
('Hearty Lentil Soup Toppers', 'A delicious and easy dish to prepare.', 10, 1, 12, 52, 8, 3, 5, 'Advanced'),
('Low-Carb Quinoa Bowl and Chickpeas', 'Perfect for meal prepping.', 1, 1, 16, 11, 1, 1, 4, 'Intermediate'),
('Creamy Beef Tacos Delight', 'Light yet filling meal.', 9, 2, 19, 33, 7, 1, 5, 'Easy'),
('Tangy Vegetable Stir Fry Special', 'Classic recipe loved by all.', 5, 4, 10, 35, 4, 5, 2, 'Easy'),
('Simple Shrimp Alfredo Medley', 'Light yet filling meal.', 6, 1, 6, 46, 4, 1, 2, 'Intermediate'),
('Hearty Chicken Curry Fiesta', 'A delicious and easy dish to prepare.', 6, 1, 7, 23, 6, 3, 4, 'Intermediate'),
('Classic Beef Tacos with Basil', 'Classic recipe loved by all.', 3, 4, 14, 45, 4, 4, 5, 'Advanced'),
('Vegan Chicken Curry Wraps', 'Classic recipe loved by all.', 1, 5, 14, 60, 3, 4, 2, 'Intermediate'),
('Simple Spaghetti Bolognese and Chickpeas', 'Comfort food with a twist.', 7, 1, 6, 54, 8, 3, 1, 'Advanced'),
('Simple Vegetable Stir Fry Fiesta', 'Healthy and flavorful meal.', 8, 1, 29, 56, 7, 2, 4, 'Intermediate'),
('Hearty Shrimp Alfredo Special', 'Great for family gatherings.', 9, 3, 30, 13, 3, 5, 5, 'Easy'),
('Tangy Beef Tacos and Chickpeas', 'Low-carb, high-protein recipe.', 8, 2, 24, 35, 4, 3, 4, 'Intermediate'),
('Crunchy Lentil Soup Fusion', 'Great for family gatherings.', 5, 2, 30, 21, 6, 1, 4, 'Intermediate'),
('Zesty Quinoa Bowl Special', 'Perfect for meal prepping.', 1, 3, 8, 52, 8, 5, 1, 'Intermediate'),
('Fresh Quinoa Bowl Skillet', 'Low-carb, high-protein recipe.', 4, 1, 17, 34, 2, 3, 1, 'Easy'),
('Crunchy Beef Tacos Surprise', 'Great for family gatherings.', 5, 3, 5, 14, 7, 2, 5, 'Easy'),
('Spicy Lentil Soup Wraps', 'Classic recipe loved by all.', 5, 1, 23, 22, 4, 5, 5, 'Advanced'),
('Vegan Lentil Soup Delight', 'Perfect for meal prepping.', 10, 1, 14, 60, 7, 3, 3, 'Advanced'),
('Savory Shrimp Alfredo Skillet', 'Quick weeknight dinner idea.', 5, 2, 14, 29, 4, 2, 3, 'Advanced'),
('Tangy Shrimp Alfredo with Cheese', 'Great for family gatherings.', 7, 4, 7, 23, 6, 4, 2, 'Intermediate'),
('Creamy Chicken Curry with Cheese', 'Perfect for meal prepping.', 1, 5, 17, 43, 1, 1, 4, 'Easy'),
('Simple Pasta Primavera with Basil', 'Classic recipe loved by all.', 3, 4, 15, 41, 7, 1, 2, 'Intermediate'),
('Classic Lentil Soup Special', 'Spicy and satisfying dish.', 8, 5, 13, 41, 7, 2, 5, 'Easy'),
('Classic Grilled Chicken Salad Delight', 'A delicious and easy dish to prepare.', 4, 2, 8, 24, 2, 4, 5, 'Easy'),
('Zesty Quinoa Bowl Fiesta', 'Spicy and satisfying dish.', 1, 3, 8, 12, 2, 5, 1, 'Easy'),
('Tangy Tofu Stir Fry Fiesta', 'Light yet filling meal.', 6, 5, 24, 34, 2, 4, 3, 'Easy'),
('Savory Grilled Chicken Salad Fiesta', 'Comfort food with a twist.', 7, 4, 18, 34, 3, 1, 3, 'Advanced'),
('Vegan Chicken Curry Bake', 'Light yet filling meal.', 5, 3, 10, 37, 1, 1, 3, 'Easy'),
('Savory Grilled Chicken Salad Medley', 'Spicy and satisfying dish.', 4, 2, 21, 23, 5, 1, 3, 'Intermediate'),
('Spicy Vegetable Stir Fry with Rice', 'A delicious and easy dish to prepare.', 10, 2, 18, 51, 1, 5, 3, 'Intermediate'),
('Gluten-Free Grilled Chicken Salad Surprise', 'Perfect for meal prepping.', 4, 5, 18, 51, 8, 5, 5, 'Advanced'),
('Zesty Beef Tacos Wraps', 'Perfect for meal prepping.', 7, 3, 6, 27, 8, 4, 1, 'Easy'),
('Spicy Lentil Soup Fusion', 'Healthy and flavorful meal.', 2, 4, 14, 20, 6, 3, 4, 'Intermediate'),
('Zesty Tofu Stir Fry Toppers', 'A delicious and easy dish to prepare.', 1, 5, 28, 46, 4, 3, 3, 'Intermediate'),
('Fresh Tofu Stir Fry with Basil', 'Light yet filling meal.', 4, 1, 12, 22, 3, 3, 3, 'Advanced'),
('Savory Tofu Stir Fry Special', 'Spicy and satisfying dish.', 2, 1, 15, 47, 1, 2, 2, 'Intermediate'),
('Hearty Grilled Chicken Salad Wraps', 'Comfort food with a twist.', 3, 1, 20, 43, 7, 4, 3, 'Advanced'),
('Creamy Chicken Curry Wraps', 'Spicy and satisfying dish.', 6, 5, 27, 21, 4, 1, 1, 'Intermediate'),
('Hearty Quinoa Bowl with Basil', 'Comfort food with a twist.', 4, 2, 23, 44, 2, 3, 3, 'Easy'),
('Creamy Pasta Primavera Toppers', 'Perfect for meal prepping.', 9, 4, 27, 47, 1, 5, 5, 'Easy'),
('Gluten-Free Pasta Primavera Fiesta', 'Healthy and flavorful meal.', 8, 2, 6, 33, 7, 4, 3, 'Intermediate'),
('Spicy Lentil Soup Skillet', 'Low-carb, high-protein recipe.', 10, 5, 21, 58, 5, 1, 4, 'Easy'),
('Creamy Chicken Curry Toppers', 'Perfect for meal prepping.', 7, 4, 21, 34, 1, 2, 5, 'Intermediate'),
('Vegan Shrimp Alfredo Bake', 'Great for family gatherings.', 6, 2, 7, 16, 1, 5, 3, 'Intermediate'),
('Tangy Quinoa Bowl Fiesta', 'Low-carb, high-protein recipe.', 8, 3, 6, 42, 1, 4, 4, 'Intermediate'),
('Simple Vegetable Stir Fry Fusion', 'A delicious and easy dish to prepare.', 3, 2, 25, 22, 4, 2, 4, 'Easy'),
('Smoky Spaghetti Bolognese Special', 'A delicious and easy dish to prepare.', 9, 1, 28, 25, 5, 3, 3, 'Easy'),
('Fresh Pasta Primavera with Basil', 'Great for family gatherings.', 8, 1, 7, 36, 6, 2, 5, 'Advanced'),
('Fresh Vegetable Stir Fry with Cheese', 'Spicy and satisfying dish.', 2, 3, 19, 59, 8, 2, 3, 'Advanced'),
('Low-Carb Tofu Stir Fry Skillet', 'Spicy and satisfying dish.', 3, 5, 6, 15, 5, 2, 2, 'Easy'),
('Savory Tofu Stir Fry Surprise', 'Classic recipe loved by all.', 1, 3, 29, 16, 3, 4, 5, 'Advanced'),
('Classic Grilled Chicken Salad with Rice', 'Great for family gatherings.', 8, 5, 29, 40, 7, 1, 2, 'Intermediate'),
('Gluten-Free Shrimp Alfredo and Chickpeas', 'Comfort food with a twist.', 9, 1, 17, 35, 8, 2, 5, 'Intermediate'),
('Spicy Vegetable Stir Fry Wraps', 'Classic recipe loved by all.', 10, 3, 15, 16, 5, 2, 2, 'Advanced'),
('Spicy Tofu Stir Fry Wraps', 'A delicious and easy dish to prepare.', 10, 4, 6, 55, 1, 4, 3, 'Easy'),
('Simple Quinoa Bowl Fusion', 'A delicious and easy dish to prepare.', 3, 5, 6, 54, 3, 3, 2, 'Easy'),
('Vegan Grilled Chicken Salad with Rice', 'Spicy and satisfying dish.', 10, 2, 13, 38, 8, 5, 3, 'Easy'),
('Classic Chicken Curry with Rice', 'Classic recipe loved by all.', 3, 2, 6, 52, 6, 5, 2, 'Advanced'),
('Low-Carb Shrimp Alfredo Surprise', 'Light yet filling meal.', 10, 5, 20, 39, 8, 5, 5, 'Advanced'),
('Crunchy Shrimp Alfredo Toppers', 'Perfect for meal prepping.', 5, 2, 16, 15, 2, 3, 3, 'Intermediate'),
('Vegan Tofu Stir Fry Toppers', 'Healthy and flavorful meal.', 5, 3, 10, 44, 1, 1, 1, 'Easy'),
('Creamy Grilled Chicken Salad Fiesta', 'Great for family gatherings.', 5, 4, 7, 24, 2, 3, 4, 'Advanced'),
('Savory Shrimp Alfredo Surprise', 'Comfort food with a twist.', 10, 5, 8, 31, 8, 2, 3, 'Intermediate'),
('Spicy Chicken Curry Surprise', 'Healthy and flavorful meal.', 5, 3, 23, 47, 3, 2, 3, 'Intermediate'),
('Tangy Chicken Curry Toppers', 'Spicy and satisfying dish.', 9, 1, 8, 22, 3, 2, 4, 'Intermediate'),
('Hearty Lentil Soup Bake', 'Classic recipe loved by all.', 4, 5, 15, 59, 7, 1, 4, 'Intermediate'),
('Hearty Tofu Stir Fry Special', 'Light yet filling meal.', 6, 1, 18, 45, 1, 4, 2, 'Advanced'),
('Tangy Shrimp Alfredo Bake', 'Healthy and flavorful meal.', 7, 3, 8, 45, 4, 4, 4, 'Advanced'),
('Crunchy Lentil Soup with Rice', 'Spicy and satisfying dish.', 2, 4, 7, 43, 2, 1, 2, 'Intermediate'),
('Zesty Spaghetti Bolognese Fusion', 'Classic recipe loved by all.', 7, 5, 22, 27, 5, 5, 1, 'Intermediate'),
('Fresh Shrimp Alfredo Medley', 'Healthy and flavorful meal.', 5, 1, 15, 37, 5, 5, 3, 'Advanced'),
('Smoky Lentil Soup with Basil', 'Comfort food with a twist.', 2, 2, 26, 46, 8, 2, 2, 'Easy'),
('Gluten-Free Beef Tacos with Rice', 'Spicy and satisfying dish.', 3, 3, 21, 37, 1, 1, 3, 'Advanced'),
('Crunchy Vegetable Stir Fry Toppers', 'Great for family gatherings.', 10, 3, 20, 52, 4, 1, 2, 'Intermediate'),
('Hearty Chicken Curry Toppers', 'Light yet filling meal.', 3, 3, 30, 58, 8, 5, 5, 'Advanced'),
('Vegan Pasta Primavera Fiesta', 'Perfect for meal prepping.', 2, 1, 25, 20, 7, 3, 3, 'Easy'),
('Fresh Chicken Curry with Basil', 'Classic recipe loved by all.', 6, 2, 25, 20, 2, 5, 5, 'Intermediate'),
('Crunchy Chicken Curry with Rice', 'Comfort food with a twist.', 2, 1, 26, 47, 2, 2, 1, 'Advanced'),
('Savory Chicken Curry Fusion', 'Great for family gatherings.', 2, 3, 23, 34, 7, 4, 3, 'Intermediate'),
('Fresh Beef Tacos with Basil', 'Classic recipe loved by all.', 9, 4, 13, 44, 4, 5, 5, 'Intermediate'),
('Hearty Tofu Stir Fry and Chickpeas', 'Light yet filling meal.', 3, 5, 30, 37, 3, 3, 5, 'Easy'),
('Smoky Chicken Curry with Basil', 'Comfort food with a twist.', 8, 1, 11, 20, 2, 5, 1, 'Intermediate'),
('Creamy Pasta Primavera with Cheese', 'Healthy and flavorful meal.', 9, 3, 29, 60, 7, 2, 1, 'Advanced'),
('Crunchy Shrimp Alfredo with Cheese', 'Classic recipe loved by all.', 4, 4, 17, 56, 5, 5, 2, 'Easy'),
('Fresh Grilled Chicken Salad with Cheese', 'Spicy and satisfying dish.', 2, 2, 13, 41, 3, 1, 2, 'Advanced'),
('Hearty Pasta Primavera Wraps', 'Perfect for meal prepping.', 10, 3, 5, 31, 1, 1, 5, 'Advanced'),
('Gluten-Free Spaghetti Bolognese Bake', 'Comfort food with a twist.', 3, 1, 26, 21, 1, 3, 4, 'Advanced'),
('Vegan Vegetable Stir Fry Bake', 'A delicious and easy dish to prepare.', 8, 2, 21, 50, 7, 1, 4, 'Advanced'),
('Smoky Pasta Primavera Wraps', 'Comfort food with a twist.', 2, 5, 30, 43, 3, 1, 2, 'Easy'),
('Smoky Quinoa Bowl Medley', 'Perfect for meal prepping.', 5, 3, 30, 24, 7, 1, 5, 'Intermediate'),
('Simple Grilled Chicken Salad Delight', 'Spicy and satisfying dish.', 5, 4, 9, 28, 7, 3, 2, 'Advanced'),
('Smoky Chicken Curry and Chickpeas', 'Comfort food with a twist.', 2, 3, 7, 52, 3, 1, 4, 'Advanced'),
('Crunchy Grilled Chicken Salad Wraps', 'Spicy and satisfying dish.', 9, 2, 5, 41, 7, 4, 3, 'Easy'),
('Spicy Beef Tacos Fiesta', 'Light yet filling meal.', 5, 4, 18, 46, 3, 4, 2, 'Easy'),
('Classic Pasta Primavera Delight', 'Quick weeknight dinner idea.', 9, 2, 10, 31, 1, 5, 4, 'Easy'),
('Creamy Spaghetti Bolognese Special', 'Low-carb, high-protein recipe.', 10, 4, 13, 41, 2, 3, 5, 'Intermediate'),
('Tangy Chicken Curry Fusion', 'Classic recipe loved by all.', 2, 3, 25, 40, 1, 4, 2, 'Intermediate'),
('Smoky Quinoa Bowl with Rice', 'A delicious and easy dish to prepare.', 7, 4, 11, 56, 5, 1, 4, 'Intermediate'),
('Spicy Quinoa Bowl Wraps', 'Spicy and satisfying dish.', 1, 3, 14, 32, 6, 4, 5, 'Intermediate'),
('Vegan Quinoa Bowl and Chickpeas', 'Comfort food with a twist.', 1, 1, 18, 57, 2, 3, 5, 'Advanced'),
('Simple Vegetable Stir Fry Special', 'Classic recipe loved by all.', 4, 5, 24, 57, 7, 2, 3, 'Intermediate'),
('Tangy Beef Tacos Fiesta', 'Classic recipe loved by all.', 7, 5, 5, 59, 8, 2, 1, 'Advanced'),
('Zesty Tofu Stir Fry Fusion', 'Comfort food with a twist.', 1, 4, 12, 56, 3, 5, 4, 'Intermediate'),
('Classic Shrimp Alfredo Delight', 'Low-carb, high-protein recipe.', 6, 2, 19, 11, 6, 3, 4, 'Easy'),
('Vegan Beef Tacos Toppers', 'Comfort food with a twist.', 3, 2, 28, 57, 1, 1, 1, 'Easy'),
('Smoky Shrimp Alfredo Bake', 'Classic recipe loved by all.', 1, 1, 27, 48, 6, 4, 5, 'Advanced'),
('Crunchy Lentil Soup with Basil', 'Quick weeknight dinner idea.', 9, 3, 18, 38, 8, 1, 3, 'Advanced'),
('Simple Lentil Soup Surprise', 'Perfect for meal prepping.', 9, 2, 19, 18, 7, 4, 5, 'Advanced'),
('Low-Carb Spaghetti Bolognese Delight', 'A delicious and easy dish to prepare.', 2, 5, 7, 13, 7, 1, 3, 'Intermediate'),
('Low-Carb Vegetable Stir Fry and Chickpeas', 'Classic recipe loved by all.', 3, 3, 9, 41, 3, 4, 2, 'Easy'),
('Tangy Quinoa Bowl Toppers', 'Low-carb, high-protein recipe.', 10, 3, 18, 18, 6, 3, 5, 'Advanced'),
('Gluten-Free Chicken Curry with Rice', 'Light yet filling meal.', 7, 5, 20, 22, 3, 4, 3, 'Advanced'),
('Simple Vegetable Stir Fry Surprise', 'Quick weeknight dinner idea.', 9, 5, 27, 12, 2, 2, 1, 'Easy'),
('Creamy Chicken Curry Skillet', 'Great for family gatherings.', 10, 1, 13, 13, 1, 3, 4, 'Advanced'),
('Spicy Chicken Curry Special', 'Perfect for meal prepping.', 2, 1, 23, 39, 6, 2, 3, 'Easy'),
('Gluten-Free Grilled Chicken Salad Toppers', 'Great for family gatherings.', 7, 2, 27, 28, 7, 1, 5, 'Easy'),
('Spicy Vegetable Stir Fry and Chickpeas', 'Classic recipe loved by all.', 3, 3, 21, 51, 1, 3, 4, 'Advanced'),
('Simple Quinoa Bowl Wraps', 'Quick weeknight dinner idea.', 6, 4, 7, 42, 6, 1, 3, 'Advanced'),
('Zesty Beef Tacos Surprise', 'Spicy and satisfying dish.', 9, 1, 30, 49, 7, 4, 5, 'Advanced'),
('Smoky Spaghetti Bolognese with Rice', 'Classic recipe loved by all.', 4, 3, 18, 50, 4, 4, 4, 'Intermediate'),
('Gluten-Free Vegetable Stir Fry with Cheese', 'Spicy and satisfying dish.', 10, 5, 19, 59, 1, 1, 4, 'Advanced'),
('Tangy Pasta Primavera with Cheese', 'Great for family gatherings.', 6, 2, 19, 40, 5, 4, 1, 'Intermediate'),
('Low-Carb Grilled Chicken Salad Delight', 'A delicious and easy dish to prepare.', 6, 3, 16, 58, 6, 2, 4, 'Easy'),
('Smoky Tofu Stir Fry Toppers', 'A delicious and easy dish to prepare.', 7, 1, 23, 41, 3, 5, 2, 'Intermediate'),
('Creamy Quinoa Bowl with Cheese', 'Great for family gatherings.', 7, 5, 11, 40, 8, 5, 1, 'Intermediate'),
('Vegan Shrimp Alfredo Fiesta', 'Light yet filling meal.', 10, 3, 25, 32, 1, 4, 5, 'Easy'),
('Spicy Lentil Soup Delight', 'Spicy and satisfying dish.', 5, 1, 22, 16, 1, 3, 2, 'Advanced'),
('Smoky Lentil Soup Bake', 'Great for family gatherings.', 7, 3, 23, 45, 6, 5, 4, 'Easy'),
('Creamy Shrimp Alfredo Skillet', 'Low-carb, high-protein recipe.', 1, 3, 10, 54, 4, 5, 5, 'Advanced'),
('Creamy Chicken Curry Special', 'Spicy and satisfying dish.', 9, 3, 21, 11, 6, 3, 3, 'Advanced'),
('Vegan Vegetable Stir Fry Skillet', 'Spicy and satisfying dish.', 7, 4, 28, 11, 6, 1, 4, 'Advanced'),
('Savory Shrimp Alfredo Delight', 'Comfort food with a twist.', 10, 4, 30, 26, 5, 3, 4, 'Intermediate'),
('Hearty Chicken Curry with Rice', 'Healthy and flavorful meal.', 5, 5, 17, 45, 4, 2, 2, 'Easy'),
('Vegan Shrimp Alfredo Delight', 'Healthy and flavorful meal.', 4, 1, 18, 10, 6, 1, 5, 'Advanced'),
('Simple Chicken Curry Wraps', 'Comfort food with a twist.', 8, 5, 6, 13, 1, 2, 3, 'Intermediate'),
('Hearty Chicken Curry Delight', 'Light yet filling meal.', 5, 5, 15, 50, 7, 5, 5, 'Easy'),
('Savory Tofu Stir Fry Bake', 'Light yet filling meal.', 1, 4, 12, 40, 8, 2, 4, 'Intermediate'),
('Creamy Lentil Soup and Chickpeas', 'Quick weeknight dinner idea.', 2, 5, 7, 24, 7, 4, 1, 'Advanced'),
('Smoky Lentil Soup Medley', 'A delicious and easy dish to prepare.', 10, 1, 11, 28, 5, 2, 2, 'Intermediate'),
('Gluten-Free Chicken Curry with Cheese', 'Quick weeknight dinner idea.', 6, 2, 17, 34, 5, 4, 3, 'Intermediate'),
('Zesty Beef Tacos Delight', 'Great for family gatherings.', 8, 3, 8, 13, 6, 3, 5, 'Easy'),
('Gluten-Free Tofu Stir Fry with Rice', 'Low-carb, high-protein recipe.', 9, 2, 9, 19, 6, 2, 2, 'Advanced'),
('Vegan Beef Tacos Delight', 'Healthy and flavorful meal.', 8, 5, 12, 29, 5, 1, 2, 'Advanced'),
('Gluten-Free Shrimp Alfredo Fiesta', 'Comfort food with a twist.', 6, 3, 16, 43, 1, 4, 4, 'Intermediate'),
('Gluten-Free Chicken Curry Delight', 'Perfect for meal prepping.', 8, 4, 8, 51, 6, 2, 5, 'Intermediate'),
('Gluten-Free Grilled Chicken Salad Wraps', 'Classic recipe loved by all.', 1, 2, 17, 17, 8, 2, 3, 'Advanced'),
('Fresh Pasta Primavera Fiesta', 'A delicious and easy dish to prepare.', 1, 5, 15, 28, 5, 3, 4, 'Intermediate'),
('Gluten-Free Pasta Primavera Surprise', 'Classic recipe loved by all.', 5, 5, 14, 37, 1, 2, 5, 'Advanced'),
('Savory Lentil Soup and Chickpeas', 'Low-carb, high-protein recipe.', 2, 5, 24, 39, 7, 2, 4, 'Advanced'),
('Tangy Pasta Primavera Fusion', 'Low-carb, high-protein recipe.', 7, 5, 13, 38, 3, 2, 3, 'Intermediate'),
('Classic Chicken Curry Special', 'Comfort food with a twist.', 2, 5, 13, 21, 8, 4, 5, 'Easy'),
('Gluten-Free Vegetable Stir Fry with Basil', 'A delicious and easy dish to prepare.', 6, 2, 21, 26, 6, 1, 1, 'Intermediate'),
('Gluten-Free Lentil Soup Surprise', 'Light yet filling meal.', 5, 3, 16, 11, 2, 4, 3, 'Intermediate'),
('Tangy Spaghetti Bolognese Fusion', 'Comfort food with a twist.', 9, 4, 28, 28, 3, 2, 4, 'Advanced'),
('Zesty Tofu Stir Fry Bake', 'Quick weeknight dinner idea.', 1, 2, 12, 10, 3, 3, 4, 'Advanced'),
('Creamy Spaghetti Bolognese with Cheese', 'Healthy and flavorful meal.', 10, 2, 23, 36, 8, 2, 1, 'Advanced'),
('Tangy Quinoa Bowl Bake', 'Spicy and satisfying dish.', 9, 1, 22, 18, 8, 4, 5, 'Advanced'),
('Creamy Lentil Soup Medley', 'Healthy and flavorful meal.', 7, 5, 8, 42, 7, 1, 3, 'Intermediate'),
('Spicy Shrimp Alfredo Fusion', 'Healthy and flavorful meal.', 3, 5, 9, 22, 1, 3, 4, 'Advanced'),
('Smoky Shrimp Alfredo Delight', 'Healthy and flavorful meal.', 8, 5, 27, 47, 6, 1, 4, 'Intermediate'),
('Vegan Lentil Soup with Basil', 'Spicy and satisfying dish.', 3, 5, 27, 25, 1, 5, 5, 'Intermediate'),
('Fresh Grilled Chicken Salad Surprise', 'Low-carb, high-protein recipe.', 7, 1, 21, 58, 6, 5, 2, 'Advanced'),
('Spicy Tofu Stir Fry Special', 'Comfort food with a twist.', 9, 2, 22, 18, 5, 1, 5, 'Intermediate'),
('Fresh Quinoa Bowl Wraps', 'Great for family gatherings.', 6, 5, 19, 26, 8, 3, 4, 'Intermediate'),
('Hearty Quinoa Bowl Fusion', 'A delicious and easy dish to prepare.', 7, 3, 19, 35, 3, 3, 5, 'Easy'),
('Savory Lentil Soup Wraps', 'Quick weeknight dinner idea.', 5, 2, 21, 56, 2, 2, 3, 'Easy'),
('Simple Lentil Soup Medley', 'Great for family gatherings.', 5, 5, 17, 20, 7, 1, 5, 'Intermediate'),
('Zesty Beef Tacos Special', 'Light yet filling meal.', 10, 1, 26, 44, 6, 2, 3, 'Intermediate'),
('Zesty Shrimp Alfredo Skillet', 'Comfort food with a twist.', 9, 5, 26, 27, 1, 5, 5, 'Advanced'),
('Smoky Spaghetti Bolognese Bake', 'Great for family gatherings.', 9, 1, 18, 51, 4, 1, 1, 'Advanced'),
('Vegan Spaghetti Bolognese Fiesta', 'Comfort food with a twist.', 6, 1, 16, 42, 6, 3, 1, 'Advanced'),
('Vegan Lentil Soup Bake', 'Great for family gatherings.', 9, 1, 6, 31, 6, 3, 5, 'Easy'),
('Classic Grilled Chicken Salad Wraps', 'Light yet filling meal.', 7, 1, 7, 27, 7, 3, 4, 'Intermediate'),
('Hearty Beef Tacos Delight', 'Comfort food with a twist.', 10, 5, 12, 41, 1, 4, 2, 'Intermediate'),
('Simple Shrimp Alfredo with Basil', 'Light yet filling meal.', 3, 2, 25, 55, 5, 2, 5, 'Advanced'),
('Hearty Vegetable Stir Fry Special', 'Spicy and satisfying dish.', 10, 5, 28, 30, 8, 1, 4, 'Easy'),
('Savory Chicken Curry with Rice', 'Healthy and flavorful meal.', 10, 2, 26, 53, 5, 1, 4, 'Intermediate'),
('Gluten-Free Shrimp Alfredo with Basil', 'Low-carb, high-protein recipe.', 9, 1, 9, 19, 6, 4, 2, 'Advanced'),
('Simple Beef Tacos Medley', 'Low-carb, high-protein recipe.', 4, 2, 30, 27, 1, 5, 1, 'Easy'),
('Vegan Vegetable Stir Fry and Chickpeas', 'Healthy and flavorful meal.', 8, 1, 5, 54, 1, 4, 2, 'Intermediate'),
('Crunchy Grilled Chicken Salad Medley', 'Low-carb, high-protein recipe.', 2, 1, 16, 16, 6, 5, 3, 'Intermediate'),
('Gluten-Free Tofu Stir Fry Wraps', 'Spicy and satisfying dish.', 4, 2, 14, 20, 2, 1, 3, 'Advanced'),
('Smoky Tofu Stir Fry Medley', 'Quick weeknight dinner idea.', 7, 2, 24, 47, 1, 3, 5, 'Intermediate'),
('Savory Shrimp Alfredo with Cheese', 'Healthy and flavorful meal.', 3, 5, 5, 35, 2, 3, 1, 'Intermediate'),
('Zesty Pasta Primavera Toppers', 'Classic recipe loved by all.', 6, 1, 11, 44, 6, 4, 2, 'Intermediate'),
('Crunchy Beef Tacos Skillet', 'Low-carb, high-protein recipe.', 10, 4, 23, 10, 6, 5, 4, 'Advanced'),
('Simple Shrimp Alfredo Fiesta', 'A delicious and easy dish to prepare.', 6, 2, 26, 12, 7, 4, 1, 'Intermediate'),
('Low-Carb Chicken Curry Special', 'Perfect for meal prepping.', 8, 2, 28, 27, 4, 3, 4, 'Easy'),
('Creamy Beef Tacos with Cheese', 'Light yet filling meal.', 5, 4, 29, 34, 8, 5, 4, 'Intermediate'),
('Smoky Chicken Curry Delight', 'Spicy and satisfying dish.', 3, 4, 8, 44, 8, 2, 1, 'Intermediate'),
('Tangy Grilled Chicken Salad Fusion', 'Classic recipe loved by all.', 1, 2, 30, 52, 3, 1, 5, 'Easy'),
('Low-Carb Beef Tacos Fiesta', 'Low-carb, high-protein recipe.', 10, 5, 28, 48, 7, 2, 5, 'Advanced'),
('Simple Chicken Curry Fiesta', 'Spicy and satisfying dish.', 1, 1, 11, 32, 8, 4, 3, 'Intermediate'),
('Smoky Beef Tacos Wraps', 'Classic recipe loved by all.', 5, 4, 15, 13, 1, 2, 3, 'Advanced'),
('Classic Pasta Primavera Toppers', 'A delicious and easy dish to prepare.', 3, 5, 12, 40, 3, 2, 4, 'Advanced'),
('Fresh Grilled Chicken Salad Wraps', 'Healthy and flavorful meal.', 3, 5, 15, 27, 7, 3, 2, 'Advanced'),
('Zesty Quinoa Bowl with Basil', 'Comfort food with a twist.', 5, 4, 10, 58, 5, 3, 2, 'Intermediate'),
('Classic Tofu Stir Fry Toppers', 'Perfect for meal prepping.', 7, 5, 19, 36, 7, 5, 1, 'Easy'),
('Hearty Vegetable Stir Fry with Cheese', 'Spicy and satisfying dish.', 4, 1, 22, 23, 6, 5, 1, 'Advanced'),
('Classic Spaghetti Bolognese Medley', 'A delicious and easy dish to prepare.', 9, 3, 7, 34, 4, 1, 5, 'Advanced'),
('Crunchy Tofu Stir Fry with Basil', 'Comfort food with a twist.', 6, 3, 25, 25, 7, 5, 3, 'Intermediate'),
('Gluten-Free Tofu Stir Fry Skillet', 'Light yet filling meal.', 8, 4, 24, 36, 5, 4, 2, 'Easy'),
('Creamy Beef Tacos with Rice', 'Classic recipe loved by all.', 4, 4, 28, 54, 2, 5, 3, 'Intermediate'),
('Low-Carb Shrimp Alfredo Wraps', 'Quick weeknight dinner idea.', 7, 3, 15, 18, 3, 5, 1, 'Advanced'),
('Smoky Quinoa Bowl Toppers', 'Quick weeknight dinner idea.', 9, 1, 7, 39, 3, 5, 3, 'Intermediate'),
('Hearty Vegetable Stir Fry with Rice', 'Great for family gatherings.', 7, 2, 16, 35, 6, 4, 5, 'Advanced'),
('Creamy Spaghetti Bolognese Medley', 'Quick weeknight dinner idea.', 10, 1, 26, 56, 6, 5, 1, 'Advanced'),
('Low-Carb Quinoa Bowl Toppers', 'Perfect for meal prepping.', 4, 5, 6, 20, 5, 5, 2, 'Easy'),
('Gluten-Free Grilled Chicken Salad with Cheese', 'A delicious and easy dish to prepare.', 7, 4, 11, 35, 7, 2, 1, 'Intermediate'),
('Simple Shrimp Alfredo Wraps', 'Healthy and flavorful meal.', 6, 5, 22, 13, 2, 5, 2, 'Easy'),
('Smoky Beef Tacos with Cheese', 'Light yet filling meal.', 9, 1, 13, 21, 8, 1, 2, 'Easy'),
('Gluten-Free Tofu Stir Fry Fusion', 'Quick weeknight dinner idea.', 8, 2, 30, 60, 8, 1, 3, 'Easy'),
('Hearty Beef Tacos with Cheese', 'Healthy and flavorful meal.', 5, 3, 20, 57, 2, 3, 2, 'Advanced'),
('Crunchy Tofu Stir Fry Wraps', 'Perfect for meal prepping.', 8, 1, 8, 16, 1, 3, 3, 'Intermediate'),
('Crunchy Quinoa Bowl Fusion', 'Quick weeknight dinner idea.', 1, 2, 23, 54, 6, 4, 1, 'Advanced'),
('Zesty Quinoa Bowl Delight', 'Perfect for meal prepping.', 8, 3, 11, 27, 5, 4, 4, 'Intermediate'),
('Spicy Shrimp Alfredo Wraps', 'Quick weeknight dinner idea.', 1, 4, 30, 55, 4, 2, 2, 'Easy'),
('Spicy Tofu Stir Fry Fusion', 'Comfort food with a twist.', 4, 3, 22, 30, 3, 4, 1, 'Easy'),
('Smoky Lentil Soup with Rice', 'Great for family gatherings.', 5, 5, 20, 46, 5, 1, 4, 'Easy'),
('Simple Chicken Curry Medley', 'Quick weeknight dinner idea.', 2, 3, 30, 17, 1, 2, 3, 'Easy'),
('Savory Grilled Chicken Salad Bake', 'Classic recipe loved by all.', 1, 2, 20, 48, 7, 3, 3, 'Advanced'),
('Tangy Spaghetti Bolognese and Chickpeas', 'Healthy and flavorful meal.', 5, 3, 10, 51, 8, 5, 3, 'Advanced'),
('Savory Spaghetti Bolognese Wraps', 'Great for family gatherings.', 8, 2, 10, 45, 8, 2, 1, 'Advanced'),
('Fresh Shrimp Alfredo with Rice', 'Quick weeknight dinner idea.', 6, 5, 26, 50, 2, 2, 1, 'Intermediate'),
('Simple Spaghetti Bolognese Wraps', 'Low-carb, high-protein recipe.', 8, 4, 10, 24, 4, 3, 2, 'Intermediate'),
('Creamy Vegetable Stir Fry with Rice', 'Perfect for meal prepping.', 4, 1, 6, 31, 2, 5, 2, 'Easy'),
('Hearty Shrimp Alfredo Surprise', 'Great for family gatherings.', 7, 3, 10, 25, 6, 3, 1, 'Intermediate'),
('Creamy Quinoa Bowl Wraps', 'A delicious and easy dish to prepare.', 10, 4, 27, 59, 8, 1, 1, 'Advanced'),
('Smoky Tofu Stir Fry Bake', 'A delicious and easy dish to prepare.', 3, 4, 17, 17, 8, 4, 4, 'Intermediate'),
('Simple Tofu Stir Fry Delight', 'Low-carb, high-protein recipe.', 4, 5, 11, 10, 1, 4, 2, 'Intermediate'),
('Smoky Shrimp Alfredo Wraps', 'Light yet filling meal.', 7, 5, 14, 28, 8, 5, 3, 'Advanced'),
('Classic Quinoa Bowl with Rice', 'Classic recipe loved by all.', 9, 5, 6, 31, 1, 1, 5, 'Intermediate'),
('Gluten-Free Quinoa Bowl Special', 'Great for family gatherings.', 5, 1, 10, 55, 3, 3, 5, 'Easy'),
('Creamy Shrimp Alfredo Bake', 'A delicious and easy dish to prepare.', 9, 5, 12, 49, 7, 5, 4, 'Intermediate'),
('Classic Grilled Chicken Salad Special', 'Great for family gatherings.', 9, 2, 27, 30, 4, 3, 2, 'Intermediate'),
('Savory Spaghetti Bolognese Surprise', 'Perfect for meal prepping.', 6, 4, 13, 41, 3, 2, 2, 'Advanced'),
('Hearty Spaghetti Bolognese Toppers', 'Healthy and flavorful meal.', 1, 5, 27, 29, 3, 5, 3, 'Easy'),
('Tangy Grilled Chicken Salad with Basil', 'Low-carb, high-protein recipe.', 6, 3, 9, 17, 2, 3, 3, 'Easy'),
('Savory Quinoa Bowl Fiesta', 'Great for family gatherings.', 4, 3, 25, 60, 7, 2, 1, 'Advanced'),
('Simple Quinoa Bowl with Rice', 'Spicy and satisfying dish.', 3, 2, 18, 14, 5, 2, 2, 'Advanced'),
('Classic Vegetable Stir Fry Wraps', 'Spicy and satisfying dish.', 7, 4, 26, 15, 2, 4, 3, 'Easy'),
('Hearty Pasta Primavera Delight', 'Light yet filling meal.', 8, 5, 15, 35, 1, 5, 1, 'Intermediate'),
('Fresh Shrimp Alfredo Wraps', 'Classic recipe loved by all.', 8, 4, 26, 56, 6, 1, 3, 'Intermediate'),
('Low-Carb Pasta Primavera Fiesta', 'Spicy and satisfying dish.', 4, 3, 22, 21, 3, 2, 3, 'Advanced'),
('Spicy Quinoa Bowl Fusion', 'Great for family gatherings.', 7, 1, 19, 50, 7, 5, 2, 'Intermediate'),
('Creamy Beef Tacos Medley', 'A delicious and easy dish to prepare.', 9, 5, 22, 42, 4, 3, 2, 'Intermediate'),
('Fresh Lentil Soup with Cheese', 'Light yet filling meal.', 3, 5, 29, 15, 6, 1, 3, 'Intermediate'),
('Fresh Quinoa Bowl Fusion', 'Low-carb, high-protein recipe.', 2, 5, 26, 13, 8, 5, 2, 'Advanced'),
('Creamy Spaghetti Bolognese and Chickpeas', 'Quick weeknight dinner idea.', 4, 4, 23, 55, 6, 1, 4, 'Intermediate'),
('Classic Beef Tacos and Chickpeas', 'Comfort food with a twist.', 8, 2, 13, 16, 6, 4, 2, 'Easy'),
('Gluten-Free Lentil Soup Delight', 'Classic recipe loved by all.', 4, 1, 20, 27, 3, 2, 2, 'Easy'),
('Low-Carb Spaghetti Bolognese with Basil', 'Perfect for meal prepping.', 1, 4, 12, 27, 2, 5, 3, 'Intermediate'),
('Gluten-Free Beef Tacos with Basil', 'Light yet filling meal.', 2, 1, 24, 28, 6, 3, 2, 'Advanced'),
('Spicy Vegetable Stir Fry Medley', 'Great for family gatherings.', 5, 4, 5, 36, 7, 3, 3, 'Easy'),
('Crunchy Beef Tacos Special', 'Classic recipe loved by all.', 3, 5, 5, 11, 5, 5, 2, 'Intermediate'),
('Smoky Beef Tacos with Basil', 'Low-carb, high-protein recipe.', 4, 2, 7, 40, 6, 1, 1, 'Advanced'),
('Creamy Chicken Curry with Basil', 'Low-carb, high-protein recipe.', 6, 4, 27, 21, 6, 5, 5, 'Intermediate'),
('Savory Tofu Stir Fry Fiesta', 'Healthy and flavorful meal.', 6, 2, 10, 11, 5, 4, 3, 'Advanced'),
('Smoky Quinoa Bowl with Cheese', 'Great for family gatherings.', 1, 3, 29, 59, 3, 1, 2, 'Intermediate'),
('Spicy Lentil Soup Toppers', 'Comfort food with a twist.', 4, 3, 17, 16, 6, 3, 5, 'Advanced'),
('Simple Pasta Primavera with Rice', 'Great for family gatherings.', 4, 4, 10, 22, 6, 1, 5, 'Advanced'),
('Crunchy Quinoa Bowl with Cheese', 'Light yet filling meal.', 7, 4, 15, 11, 3, 4, 1, 'Intermediate'),
('Fresh Vegetable Stir Fry Fiesta', 'Comfort food with a twist.', 6, 1, 9, 31, 2, 4, 2, 'Easy'),
('Gluten-Free Tofu Stir Fry Bake', 'Perfect for meal prepping.', 4, 4, 25, 45, 8, 3, 1, 'Intermediate'),
('Low-Carb Chicken Curry with Cheese', 'Light yet filling meal.', 2, 1, 29, 26, 8, 4, 3, 'Intermediate'),
('Simple Pasta Primavera Fusion', 'Perfect for meal prepping.', 4, 4, 6, 45, 7, 1, 1, 'Advanced'),
('Creamy Grilled Chicken Salad Surprise', 'Healthy and flavorful meal.', 2, 1, 22, 31, 6, 3, 4, 'Advanced'),
('Hearty Pasta Primavera and Chickpeas', 'Spicy and satisfying dish.', 6, 2, 13, 55, 4, 4, 3, 'Advanced'),
('Smoky Spaghetti Bolognese Medley', 'Light yet filling meal.', 5, 1, 23, 44, 1, 2, 1, 'Easy'),
('Fresh Spaghetti Bolognese Medley', 'Quick weeknight dinner idea.', 9, 1, 23, 53, 5, 5, 1, 'Easy'),
('Low-Carb Vegetable Stir Fry Wraps', 'Great for family gatherings.', 8, 3, 6, 25, 2, 2, 4, 'Intermediate'),
('Gluten-Free Beef Tacos Special', 'Classic recipe loved by all.', 7, 3, 8, 13, 3, 2, 2, 'Advanced'),
('Simple Shrimp Alfredo with Rice', 'Perfect for meal prepping.', 1, 3, 26, 57, 7, 3, 5, 'Intermediate'),
('Creamy Tofu Stir Fry Fiesta', 'A delicious and easy dish to prepare.', 9, 5, 9, 37, 8, 2, 3, 'Advanced'),
('Tangy Quinoa Bowl Special', 'Perfect for meal prepping.', 4, 1, 15, 51, 1, 3, 5, 'Easy'),
('Fresh Grilled Chicken Salad Fusion', 'Comfort food with a twist.', 3, 3, 10, 36, 1, 3, 4, 'Easy'),
('Crunchy Beef Tacos Fiesta', 'Perfect for meal prepping.', 4, 3, 18, 32, 6, 3, 2, 'Advanced'),
('Fresh Chicken Curry Fiesta', 'Great for family gatherings.', 8, 2, 14, 20, 3, 2, 3, 'Advanced'),
('Spicy Shrimp Alfredo with Basil', 'Perfect for meal prepping.', 7, 2, 26, 60, 8, 4, 4, 'Easy'),
('Low-Carb Vegetable Stir Fry with Basil', 'Comfort food with a twist.', 7, 3, 6, 53, 4, 1, 3, 'Easy'),
('Tangy Vegetable Stir Fry Skillet', 'Perfect for meal prepping.', 4, 5, 22, 34, 6, 5, 4, 'Intermediate'),
('Simple Spaghetti Bolognese Medley', 'Perfect for meal prepping.', 8, 4, 5, 40, 7, 4, 4, 'Intermediate'),
('Low-Carb Beef Tacos Special', 'A delicious and easy dish to prepare.', 6, 4, 10, 45, 2, 5, 4, 'Easy'),
('Hearty Grilled Chicken Salad with Cheese', 'Comfort food with a twist.', 3, 3, 21, 26, 4, 3, 1, 'Easy'),
('Tangy Tofu Stir Fry Medley', 'Spicy and satisfying dish.', 3, 5, 16, 20, 5, 3, 4, 'Easy'),
('Smoky Tofu Stir Fry with Basil', 'Light yet filling meal.', 4, 4, 25, 38, 3, 1, 2, 'Advanced'),
('Vegan Tofu Stir Fry Bake', 'A delicious and easy dish to prepare.', 1, 3, 24, 50, 1, 3, 5, 'Easy'),
('Simple Pasta Primavera Delight', 'Healthy and flavorful meal.', 6, 2, 16, 16, 7, 3, 2, 'Easy'),
('Fresh Chicken Curry Delight', 'Healthy and flavorful meal.', 8, 3, 9, 58, 3, 5, 2, 'Intermediate'),
('Simple Grilled Chicken Salad with Rice', 'Quick weeknight dinner idea.', 4, 5, 28, 23, 4, 1, 1, 'Easy'),
('Creamy Spaghetti Bolognese Skillet', 'Great for family gatherings.', 7, 1, 10, 49, 3, 2, 4, 'Advanced'),
('Simple Lentil Soup with Basil', 'Healthy and flavorful meal.', 10, 4, 8, 43, 5, 2, 1, 'Easy'),
('Spicy Shrimp Alfredo Skillet', 'Perfect for meal prepping.', 6, 3, 22, 50, 4, 3, 2, 'Advanced'),
('Hearty Tofu Stir Fry with Cheese', 'Low-carb, high-protein recipe.', 5, 4, 19, 20, 4, 1, 2, 'Advanced'),
('Low-Carb Lentil Soup Toppers', 'Spicy and satisfying dish.', 2, 2, 5, 13, 4, 2, 4, 'Intermediate'),
('Tangy Tofu Stir Fry Fusion', 'Light yet filling meal.', 9, 2, 25, 10, 5, 3, 2, 'Advanced'),
('Smoky Vegetable Stir Fry Surprise', 'Classic recipe loved by all.', 8, 1, 8, 48, 7, 5, 4, 'Intermediate'),
('Savory Spaghetti Bolognese Special', 'Light yet filling meal.', 8, 5, 29, 51, 4, 3, 1, 'Easy'),
('Gluten-Free Quinoa Bowl Surprise', 'Classic recipe loved by all.', 10, 1, 28, 52, 4, 2, 1, 'Easy'),
('Low-Carb Lentil Soup with Basil', 'Healthy and flavorful meal.', 7, 4, 16, 29, 2, 2, 1, 'Intermediate'),
('Smoky Tofu Stir Fry Fusion', 'Low-carb, high-protein recipe.', 1, 2, 7, 56, 7, 4, 3, 'Intermediate'),
('Savory Chicken Curry with Basil', 'Comfort food with a twist.', 8, 3, 22, 14, 7, 1, 2, 'Advanced'),
('Tangy Spaghetti Bolognese Medley', 'Great for family gatherings.', 3, 3, 16, 46, 6, 5, 5, 'Advanced'),
('Low-Carb Quinoa Bowl Wraps', 'Perfect for meal prepping.', 6, 1, 10, 12, 3, 4, 4, 'Easy'),
('Crunchy Shrimp Alfredo Surprise', 'Low-carb, high-protein recipe.', 8, 1, 20, 54, 8, 4, 5, 'Easy'),
('Vegan Vegetable Stir Fry Special', 'Classic recipe loved by all.', 5, 2, 5, 60, 3, 1, 3, 'Intermediate'),
('Zesty Spaghetti Bolognese with Cheese', 'Great for family gatherings.', 7, 1, 16, 60, 3, 1, 1, 'Intermediate'),
('Creamy Shrimp Alfredo with Basil', 'Light yet filling meal.', 1, 3, 5, 53, 4, 5, 2, 'Easy'),
('Crunchy Spaghetti Bolognese Special', 'Spicy and satisfying dish.', 8, 3, 26, 60, 2, 3, 4, 'Easy'),
('Gluten-Free Spaghetti Bolognese Toppers', 'A delicious and easy dish to prepare.', 10, 1, 25, 42, 1, 1, 5, 'Intermediate'),
('Zesty Spaghetti Bolognese Fiesta', 'Comfort food with a twist.', 8, 1, 14, 19, 7, 5, 2, 'Advanced'),
('Tangy Shrimp Alfredo with Rice', 'Classic recipe loved by all.', 3, 5, 28, 33, 4, 5, 2, 'Easy'),
('Hearty Shrimp Alfredo Wraps', 'Perfect for meal prepping.', 6, 5, 13, 41, 7, 4, 1, 'Easy'),
('Gluten-Free Tofu Stir Fry Special', 'Quick weeknight dinner idea.', 8, 3, 5, 54, 6, 3, 2, 'Advanced'),
('Savory Shrimp Alfredo Fiesta', 'Perfect for meal prepping.', 5, 2, 27, 41, 8, 5, 5, 'Intermediate'),
('Spicy Beef Tacos Medley', 'Healthy and flavorful meal.', 9, 4, 13, 23, 4, 3, 2, 'Advanced'),
('Zesty Shrimp Alfredo Special', 'Classic recipe loved by all.', 10, 2, 11, 17, 2, 2, 4, 'Easy'),
('Crunchy Grilled Chicken Salad Delight', 'Comfort food with a twist.', 2, 3, 20, 54, 1, 3, 3, 'Easy'),
('Classic Chicken Curry Surprise', 'A delicious and easy dish to prepare.', 8, 3, 11, 32, 8, 4, 2, 'Easy'),
('Smoky Vegetable Stir Fry Bake', 'Light yet filling meal.', 5, 5, 12, 30, 2, 4, 1, 'Intermediate'),
('Smoky Tofu Stir Fry Fiesta', 'Spicy and satisfying dish.', 3, 1, 22, 30, 3, 3, 4, 'Intermediate'),
('Vegan Tofu Stir Fry with Basil', 'Quick weeknight dinner idea.', 3, 4, 7, 50, 7, 2, 1, 'Intermediate'),
('Spicy Lentil Soup Medley', 'Perfect for meal prepping.', 8, 1, 22, 20, 4, 3, 2, 'Easy'),
('Spicy Spaghetti Bolognese Surprise', 'Great for family gatherings.', 4, 4, 19, 24, 4, 4, 3, 'Easy'),
('Low-Carb Quinoa Bowl Delight', 'Classic recipe loved by all.', 9, 3, 23, 48, 5, 1, 1, 'Easy'),
('Savory Chicken Curry with Cheese', 'Healthy and flavorful meal.', 10, 3, 11, 40, 7, 5, 5, 'Intermediate'),
('Creamy Quinoa Bowl and Chickpeas', 'Low-carb, high-protein recipe.', 7, 2, 9, 49, 8, 3, 5, 'Easy'),
('Zesty Grilled Chicken Salad and Chickpeas', 'Healthy and flavorful meal.', 8, 2, 20, 13, 3, 2, 1, 'Advanced'),
('Low-Carb Spaghetti Bolognese Surprise', 'Healthy and flavorful meal.', 6, 2, 26, 14, 1, 2, 3, 'Intermediate'),
('Classic Pasta Primavera Skillet', 'Comfort food with a twist.', 5, 2, 8, 31, 8, 1, 2, 'Intermediate'),
('Low-Carb Pasta Primavera and Chickpeas', 'Low-carb, high-protein recipe.', 5, 3, 19, 11, 3, 2, 1, 'Advanced'),
('Classic Grilled Chicken Salad Fiesta', 'A delicious and easy dish to prepare.', 9, 2, 17, 29, 2, 5, 4, 'Easy'),
('Classic Quinoa Bowl Special', 'Comfort food with a twist.', 8, 3, 17, 18, 5, 2, 2, 'Advanced'),
('Tangy Vegetable Stir Fry Toppers', 'Quick weeknight dinner idea.', 2, 4, 10, 37, 8, 3, 2, 'Advanced'),
('Spicy Spaghetti Bolognese Delight', 'Perfect for meal prepping.', 8, 2, 21, 21, 5, 4, 5, 'Easy'),
('Hearty Grilled Chicken Salad Fusion', 'Light yet filling meal.', 7, 1, 30, 29, 5, 3, 3, 'Easy'),
('Savory Vegetable Stir Fry Medley', 'Quick weeknight dinner idea.', 10, 1, 17, 34, 6, 2, 1, 'Advanced'),
('Crunchy Quinoa Bowl Fiesta', 'A delicious and easy dish to prepare.', 10, 2, 17, 33, 5, 3, 1, 'Intermediate'),
('Savory Vegetable Stir Fry Wraps', 'A delicious and easy dish to prepare.', 2, 5, 26, 16, 4, 3, 1, 'Intermediate'),
('Tangy Pasta Primavera Special', 'Healthy and flavorful meal.', 1, 2, 23, 15, 1, 1, 2, 'Advanced'),
('Spicy Spaghetti Bolognese Skillet', 'A delicious and easy dish to prepare.', 9, 1, 12, 18, 7, 2, 3, 'Advanced'),
('Simple Vegetable Stir Fry Skillet', 'Perfect for meal prepping.', 10, 3, 23, 33, 3, 3, 4, 'Easy'),
('Vegan Beef Tacos Special', 'A delicious and easy dish to prepare.', 2, 5, 21, 27, 7, 3, 4, 'Intermediate'),
('Classic Spaghetti Bolognese with Cheese', 'Healthy and flavorful meal.', 1, 5, 20, 43, 5, 5, 1, 'Intermediate'),
('Zesty Chicken Curry Medley', 'Quick weeknight dinner idea.', 1, 3, 19, 24, 7, 3, 5, 'Easy'),
('Low-Carb Spaghetti Bolognese with Rice', 'A delicious and easy dish to prepare.', 2, 5, 24, 60, 6, 1, 4, 'Advanced'),
('Smoky Pasta Primavera Delight', 'Perfect for meal prepping.', 3, 5, 24, 57, 3, 2, 1, 'Easy'),
('Simple Lentil Soup Skillet', 'Spicy and satisfying dish.', 9, 1, 14, 52, 6, 4, 3, 'Easy'),
('Creamy Beef Tacos Fusion', 'Great for family gatherings.', 10, 3, 9, 55, 6, 3, 1, 'Intermediate'),
('Tangy Spaghetti Bolognese Skillet', 'Classic recipe loved by all.', 5, 5, 7, 53, 4, 3, 5, 'Easy'),
('Low-Carb Shrimp Alfredo Fusion', 'Light yet filling meal.', 1, 5, 23, 26, 6, 5, 3, 'Intermediate'),
('Spicy Shrimp Alfredo with Rice', 'A delicious and easy dish to prepare.', 10, 2, 27, 16, 5, 1, 4, 'Intermediate'),
('Classic Vegetable Stir Fry Fusion', 'Great for family gatherings.', 2, 1, 16, 40, 6, 2, 5, 'Easy'),
('Gluten-Free Tofu Stir Fry Delight', 'Low-carb, high-protein recipe.', 3, 2, 15, 11, 2, 2, 4, 'Easy'),
('Crunchy Beef Tacos Medley', 'Comfort food with a twist.', 6, 3, 16, 40, 3, 5, 3, 'Intermediate'),
('Spicy Shrimp Alfredo Surprise', 'Comfort food with a twist.', 1, 5, 26, 53, 2, 1, 3, 'Intermediate'),
('Spicy Grilled Chicken Salad and Chickpeas', 'Comfort food with a twist.', 1, 4, 11, 13, 8, 5, 3, 'Easy'),
('Tangy Quinoa Bowl Medley', 'Light yet filling meal.', 2, 5, 14, 14, 8, 4, 4, 'Advanced'),
('Simple Grilled Chicken Salad Skillet', 'Perfect for meal prepping.', 7, 3, 13, 48, 2, 3, 5, 'Intermediate'),
('Classic Quinoa Bowl Wraps', 'Healthy and flavorful meal.', 8, 4, 7, 32, 8, 3, 1, 'Advanced'),
('Tangy Beef Tacos Fusion', 'Low-carb, high-protein recipe.', 5, 5, 22, 39, 6, 2, 2, 'Intermediate'),
('Zesty Pasta Primavera Surprise', 'Light yet filling meal.', 3, 3, 15, 18, 4, 4, 2, 'Intermediate'),
('Savory Vegetable Stir Fry with Rice', 'A delicious and easy dish to prepare.', 10, 1, 5, 14, 3, 3, 3, 'Intermediate'),
('Savory Chicken Curry and Chickpeas', 'Spicy and satisfying dish.', 7, 1, 18, 57, 4, 1, 4, 'Easy'),
('Tangy Pasta Primavera Medley', 'Classic recipe loved by all.', 9, 4, 21, 12, 5, 5, 4, 'Intermediate'),
('Spicy Grilled Chicken Salad with Basil', 'Comfort food with a twist.', 9, 5, 12, 26, 7, 4, 1, 'Intermediate'),
('Simple Chicken Curry and Chickpeas', 'Perfect for meal prepping.', 3, 2, 6, 31, 8, 2, 3, 'Intermediate'),
('Savory Beef Tacos Fiesta', 'A delicious and easy dish to prepare.', 6, 1, 16, 40, 5, 3, 1, 'Intermediate'),
('Fresh Shrimp Alfredo Surprise', 'Healthy and flavorful meal.', 8, 4, 9, 48, 8, 2, 5, 'Easy'),
('Gluten-Free Pasta Primavera Fusion', 'Light yet filling meal.', 9, 4, 9, 22, 4, 1, 5, 'Intermediate'),
('Gluten-Free Lentil Soup Special', 'Spicy and satisfying dish.', 6, 3, 9, 37, 4, 4, 5, 'Easy'),
('Smoky Beef Tacos Medley', 'Comfort food with a twist.', 8, 4, 30, 48, 8, 2, 3, 'Intermediate'),
('Smoky Vegetable Stir Fry with Basil', 'Comfort food with a twist.', 5, 2, 24, 21, 3, 3, 2, 'Intermediate'),
('Gluten-Free Grilled Chicken Salad with Basil', 'Low-carb, high-protein recipe.', 2, 5, 23, 11, 3, 3, 4, 'Advanced'),
('Smoky Vegetable Stir Fry Delight', 'Classic recipe loved by all.', 9, 4, 28, 32, 3, 4, 5, 'Advanced'),
('Smoky Quinoa Bowl Delight', 'Classic recipe loved by all.', 4, 4, 12, 34, 1, 1, 2, 'Intermediate'),
('Low-Carb Vegetable Stir Fry Special', 'Perfect for meal prepping.', 4, 4, 22, 18, 3, 5, 3, 'Easy'),
('Simple Tofu Stir Fry Fusion', 'Perfect for meal prepping.', 4, 2, 21, 45, 2, 1, 1, 'Easy'),
('Fresh Beef Tacos Skillet', 'Light yet filling meal.', 8, 1, 8, 42, 4, 2, 2, 'Intermediate'),
('Crunchy Pasta Primavera Toppers', 'Healthy and flavorful meal.', 5, 1, 15, 15, 4, 3, 5, 'Easy'),
('Crunchy Quinoa Bowl Toppers', 'Classic recipe loved by all.', 8, 4, 20, 11, 6, 5, 4, 'Easy'),
('Tangy Chicken Curry Wraps', 'Classic recipe loved by all.', 9, 3, 23, 11, 7, 5, 3, 'Advanced'),
('Fresh Lentil Soup Delight', 'Low-carb, high-protein recipe.', 9, 1, 14, 30, 5, 2, 1, 'Intermediate'),
('Crunchy Pasta Primavera Medley', 'Quick weeknight dinner idea.', 4, 1, 19, 22, 5, 3, 5, 'Easy'),
('Hearty Grilled Chicken Salad Surprise', 'Classic recipe loved by all.', 5, 1, 17, 18, 6, 5, 1, 'Advanced'),
('Zesty Spaghetti Bolognese Bake', 'Great for family gatherings.', 7, 5, 24, 53, 8, 2, 2, 'Intermediate'),
('Crunchy Grilled Chicken Salad Surprise', 'Comfort food with a twist.', 5, 4, 20, 53, 5, 5, 5, 'Intermediate');